-- =============================================================================
-- Grammar SRS Migration
-- Run this in the Supabase SQL Editor (Project → SQL Editor → New query)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. grammar_sentences
--    Shared pool of fill-in-the-blank sentences per grammar point.
--    Generated by AI and cached here so all users share the same pool.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grammar_sentences (
  id                      UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  grammar_id              TEXT        NOT NULL,          -- e.g. "mnn1-01-1"
  sentence_before         TEXT        NOT NULL DEFAULT '', -- text before the blank (kanji)
  sentence_before_reading TEXT        NOT NULL DEFAULT '', -- kana reading of before
  sentence_after          TEXT        NOT NULL DEFAULT '', -- text after the blank (kanji)
  sentence_after_reading  TEXT        NOT NULL DEFAULT '', -- kana reading of after
  answer                  TEXT        NOT NULL DEFAULT '', -- correct grammar pattern
  answer_alts             JSONB       NOT NULL DEFAULT '[]', -- ["alt1","alt2"]
  translation_es          TEXT        NOT NULL DEFAULT '',
  translation_ca          TEXT        NOT NULL DEFAULT '',
  translation_en          TEXT        NOT NULL DEFAULT '',
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS grammar_sentences_grammar_id_idx
  ON grammar_sentences (grammar_id);

-- RLS: public read, any authenticated user can insert (sentence generation)
ALTER TABLE grammar_sentences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "grammar_sentences_select" ON grammar_sentences;
CREATE POLICY "grammar_sentences_select"
  ON grammar_sentences FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "grammar_sentences_insert" ON grammar_sentences;
CREATE POLICY "grammar_sentences_insert"
  ON grammar_sentences FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------------
-- 2. grammar_srs_progress
--    Per-user SRS progress for each grammar point.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grammar_srs_progress (
  user_id     UUID    NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  grammar_id  TEXT    NOT NULL,          -- e.g. "mnn1-01-1"
  level       INTEGER NOT NULL DEFAULT 0, -- 0 (new) … 7 (mastered)
  next_review BIGINT  NOT NULL DEFAULT 0, -- Unix ms; 0 = due immediately
  PRIMARY KEY (user_id, grammar_id)
);

-- RLS: users can only see and modify their own rows
ALTER TABLE grammar_srs_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "grammar_srs_progress_all" ON grammar_srs_progress;
CREATE POLICY "grammar_srs_progress_all"
  ON grammar_srs_progress FOR ALL
  USING      (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
