import type { GrammarPoint } from './grammar-test-mnn1'

// ─── Minna no Nihongo Chūkyū I ──────────────────────────────────────────────
// みんなの日本語 中級I · Lecciones 1-20 · JLPT N3

const ch1: GrammarPoint[] = [
  {
    id: 'mnnc1-1-1',
    lesson: 1,
    number: 1,
    jlpt: 'N3',
    pattern: 'N にとって',
    name_es: 'Para ~, desde el punto de vista de ~',
    name_ca: 'Per a ~, des del punt de vista de ~',
    name_en: 'For ~, from the perspective of ~',
    explanation_es: 'Indica el punto de vista de una persona o grupo respecto a algo. Expresa cómo algo parece, afecta o tiene valor para alguien específico.',
    explanation_ca: "Indica el punt de vista d'una persona o grup respecte a alguna cosa. Expressa com alguna cosa sembla, afecta o té valor per a algú específic.",
    explanation_en: 'Indicates the standpoint of a person or group regarding something. Expresses how something seems, affects, or has value for someone.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'persona/grupo', label_ca: 'persona/grup', label_en: 'person/group' },
      { text: 'にとって', role: 'particle', isSlot: false },
      { text: '述語', role: 'key', isSlot: true, label_es: 'predicado', label_ca: 'predicat', label_en: 'predicate' },
    ],
    example: [
      { text: '日本語は', furigana: 'にほんごは', role: 'topic', gloss_es: 'el japonés', gloss_ca: 'el japonès', gloss_en: 'Japanese' },
      { text: '私に', furigana: 'わたしに', role: 'noun', gloss_es: 'para mí', gloss_ca: 'per a mi', gloss_en: 'for me' },
      { text: 'とって', role: 'particle', gloss_es: '(perspectiva)', gloss_ca: '(perspectiva)', gloss_en: '(perspective)' },
      { text: '難しい', furigana: 'むずかしい', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'です。', role: 'copula', gloss_es: 'es', gloss_ca: 'és', gloss_en: 'is' },
    ],
    tip_es: 'No confundir con ～のために (propósito). にとって solo expresa perspectiva o evaluación subjetiva.',
    tip_ca: 'No confondre amb ～のために (propòsit). にとって només expressa perspectiva o avaluació subjectiva.',
    tip_en: "Don't confuse with ～のために (purpose). にとって only expresses perspective or subjective evaluation.",
  },
  {
    id: 'mnnc1-1-2',
    lesson: 1,
    number: 2,
    jlpt: 'N3',
    pattern: '〜ということだ',
    name_es: 'Lo que significa es ~, dicen que ~',
    name_ca: 'El que significa és ~, diuen que ~',
    name_en: 'That means ~, I heard that ~',
    explanation_es: 'Dos usos: (1) reformular o aclarar el significado de algo ("eso significa que"); (2) transmitir información de segunda mano ("dicen que", "he oído que").',
    explanation_ca: "Dos usos: (1) reformular o aclarir el significat d'alguna cosa (\"això significa\"); (2) transmetre informació de segona mà (\"diuen que\", \"he sentit que\").",
    explanation_en: 'Two uses: (1) to rephrase or clarify something ("that means"); (2) to convey second-hand information ("they say", "I heard that").',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'forma ordinaria', label_ca: 'forma ordinària', label_en: 'plain form' },
      { text: 'ということだ', role: 'key', isSlot: false },
    ],
    example: [
      { text: '試験に', furigana: 'しけんに', role: 'location', gloss_es: 'en el examen', gloss_ca: "a l'examen", gloss_en: 'in the exam' },
      { text: '合格した', furigana: 'ごうかくした', role: 'verb', gloss_es: 'aprobó', gloss_ca: 'va aprovar', gloss_en: 'passed' },
      { text: 'ということは、', role: 'key', gloss_es: 'lo que significa es que', gloss_ca: 'el que significa és que', gloss_en: 'which means' },
      { text: '努力した', furigana: 'どりょくした', role: 'verb', gloss_es: 'se esforzó', gloss_ca: 'es va esforçar', gloss_en: 'worked hard' },
      { text: 'ということだ。', role: 'key', gloss_es: 'eso significa', gloss_ca: 'això significa', gloss_en: 'that means' },
    ],
    tip_es: 'En lenguaje coloquial, ということ se contrae a って. Compara con らしい y そうだ para información indirecta.',
    tip_ca: "En llengua col·loquial, ということ es contrau a って. Compara amb らしい i そうだ per a informació indirecta.",
    tip_en: 'In casual speech ということ contracts to って. Compare with らしい and そうだ for indirect information.',
  },
]

const ch2: GrammarPoint[] = [
  {
    id: 'mnnc1-2-1',
    lesson: 2,
    number: 3,
    jlpt: 'N3',
    pattern: '〜うちに',
    name_es: 'Mientras ~, antes de que cambie',
    name_ca: 'Mentre ~, abans que canviï',
    name_en: 'While ~, before it changes',
    explanation_es: 'Indica que hay que aprovechar una situación mientras dura, antes de que cambie. La primera cláusula describe una condición temporal.',
    explanation_ca: "Indica que cal aprofitar una situació mentre dura, abans que canviï. La primera clàusula descriu una condició temporal.",
    explanation_en: 'Indicates that something should be done while a situation lasts, before it changes. The first clause describes a temporary condition.',
    structure: [
      { text: 'V/い adj (普通形)', role: 'verb', isSlot: true, label_es: 'condición temporal', label_ca: 'condició temporal', label_en: 'temporary condition' },
      { text: 'うちに', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción recomendada', label_ca: 'acció recomanada', label_en: 'recommended action' },
    ],
    example: [
      { text: '熱い', furigana: 'あつい', role: 'adjective', gloss_es: 'caliente', gloss_ca: 'calent', gloss_en: 'hot' },
      { text: 'うちに', role: 'particle', gloss_es: 'mientras está', gloss_ca: 'mentre estigui', gloss_en: "while it's still" },
      { text: '食べて', furigana: 'たべて', role: 'verb', gloss_es: 'come', gloss_ca: 'menja', gloss_en: 'eat' },
      { text: 'ください。', role: 'key', gloss_es: 'por favor', gloss_ca: 'si us plau', gloss_en: 'please' },
    ],
    tip_es: 'Distinto de ～間に (durante un período fijo). うちに implica que la condición puede cambiar pronto.',
    tip_ca: 'Diferent de ～間に (durant un període fix). うちに implica que la condició pot canviar aviat.',
    tip_en: 'Different from ～間に (during a fixed period). うちに implies the condition may change soon.',
  },
  {
    id: 'mnnc1-2-2',
    lesson: 2,
    number: 4,
    jlpt: 'N3',
    pattern: '〜ことから',
    name_es: 'A partir del hecho de que ~, por ~',
    name_ca: "A partir del fet que ~, per ~",
    name_en: 'From the fact that ~, because ~',
    explanation_es: 'Expresa la base o razón para una conclusión o denominación. A menudo explica el origen de nombres o costumbres a partir de un hecho observable.',
    explanation_ca: "Expressa la base o raó per a una conclusió o denominació. Sovint explica l'origen de noms o costums a partir d'un fet observable.",
    explanation_en: 'Expresses the basis for a conclusion or naming. Often explains the origin of names or customs from an observable fact.',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'hecho observable', label_ca: 'fet observable', label_en: 'observable fact' },
      { text: 'ことから', role: 'key', isSlot: false },
      { text: '〜と呼ばれる', role: 'verb', isSlot: true, label_es: 'conclusión/denominación', label_ca: 'conclusió/denominació', label_en: 'conclusion/naming' },
    ],
    example: [
      { text: '花が', furigana: 'はなが', role: 'subject', gloss_es: 'flores', gloss_ca: 'flors', gloss_en: 'flowers' },
      { text: '多い', furigana: 'おおい', role: 'adjective', gloss_es: 'hay muchas', gloss_ca: "n'hi ha moltes", gloss_en: 'there are many' },
      { text: 'ことから、', role: 'key', gloss_es: 'a partir de este hecho,', gloss_ca: "a partir d'aquest fet,", gloss_en: 'from this fact,' },
      { text: '「花の都」と', furigana: 'はなのみやこ', role: 'noun', gloss_es: '«ciudad de las flores»', gloss_ca: '«ciutat de les flors»', gloss_en: '"City of Flowers"' },
      { text: '呼ばれています。', furigana: 'よばれています', role: 'verb', gloss_es: 'se llama', gloss_ca: 'es diu', gloss_en: 'is called' },
    ],
  },
]

const ch3: GrammarPoint[] = [
  {
    id: 'mnnc1-3-1',
    lesson: 3,
    number: 5,
    jlpt: 'N3',
    pattern: 'N に反して',
    name_es: 'Contrariamente a ~, en contra de ~',
    name_ca: 'Contràriament a ~, en contra de ~',
    name_en: 'Contrary to ~, against ~',
    explanation_es: 'Indica que algo ocurre de manera opuesta a lo esperado, deseado o establecido. Se usa con expectativas, reglas u órdenes.',
    explanation_ca: "Indica que alguna cosa ocorre de manera oposada al que s'esperava, desitjava o establia. S'usa amb expectatives, regles o ordres.",
    explanation_en: 'Indicates that something happens contrary to expectations, desires, or rules.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'expectativa/regla', label_ca: 'expectativa/regla', label_en: 'expectation/rule' },
      { text: 'に反して', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado contrario', label_ca: 'resultat contrari', label_en: 'contrary result' },
    ],
    example: [
      { text: '予想に', furigana: 'よそうに', role: 'noun', gloss_es: 'a las expectativas', gloss_ca: 'a les expectatives', gloss_en: 'contrary to expectations' },
      { text: '反して、', role: 'particle', gloss_es: 'en contra de,', gloss_ca: 'en contra de,', gloss_en: 'against,' },
      { text: '試験は', furigana: 'しけんは', role: 'topic', gloss_es: 'el examen', gloss_ca: "l'examen", gloss_en: 'the exam' },
      { text: '難しく', furigana: 'むずかしく', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'なかった。', role: 'verb', gloss_es: 'no fue', gloss_ca: 'no va ser', gloss_en: 'was not' },
    ],
    tip_es: 'Nouns típicos: 予想・期待・意思・規則・命令. La forma adjetival es に反した N.',
    tip_ca: 'Noms típics: 予想・期待・意思・規則・命令. La forma adjectival és に反した N.',
    tip_en: 'Typical nouns: 予想・期待・意思・規則・命令 (expectation, will, rule, order). Adjectival form: に反した N.',
  },
  {
    id: 'mnnc1-3-2',
    lesson: 3,
    number: 6,
    jlpt: 'N3',
    pattern: '〜わけではない',
    name_es: 'No es que ~, no necesariamente ~',
    name_ca: 'No és que ~, no necessàriament ~',
    name_en: "It's not that ~, not necessarily ~",
    explanation_es: 'Corrige o matiza una posible interpretación del oyente. Niega parcialmente una implicación sin negar el hecho completo.',
    explanation_ca: "Corregeix o matisa una possible interpretació de l'oient. Nega parcialment una implicació sense negar el fet complet.",
    explanation_en: "Corrects or nuances a possible interpretation. Partially denies an implication without negating the whole fact.",
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'implicación a negar', label_ca: 'implicació a negar', label_en: 'implication to deny' },
      { text: 'わけではない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '嫌いな', furigana: 'きらいな', role: 'adjective', gloss_es: 'que me disguste', gloss_ca: 'que em disgusti', gloss_en: 'that I dislike it' },
      { text: 'わけでは', role: 'key', gloss_es: 'no es que', gloss_ca: 'no és que', gloss_en: "it's not that" },
      { text: 'ない', role: 'key', gloss_es: '(negación)', gloss_ca: '(negació)', gloss_en: '(negation)' },
      { text: 'が、', role: 'conjunction', gloss_es: 'pero', gloss_ca: 'però', gloss_en: 'but' },
      { text: '今は食べたくない。', furigana: 'いまはたべたくない', role: 'verb', gloss_es: 'ahora no quiero comerlo', gloss_ca: 'ara no el vull menjar', gloss_en: "I just don't want to eat it now" },
    ],
    tip_es: 'Compara: わけがない (imposibilidad total), わけにはいかない (no puede hacerse). わけではない solo niega parcialmente.',
    tip_ca: "Compara: わけがない (impossibilitat total), わけにはいかない (no pot fer-se). わけではない només nega parcialment.",
    tip_en: 'Compare: わけがない (total impossibility), わけにはいかない (cannot be done). わけではない only partially denies.',
  },
]

const ch4: GrammarPoint[] = [
  {
    id: 'mnnc1-4-1',
    lesson: 4,
    number: 7,
    jlpt: 'N3',
    pattern: 'N に比べて',
    name_es: 'Comparado con ~, en comparación con ~',
    name_ca: 'Comparat amb ~, en comparació amb ~',
    name_en: 'Compared to ~, in comparison with ~',
    explanation_es: 'Establece una comparación entre dos elementos. La forma に比べ (sin て) es más formal y se usa en escritura.',
    explanation_ca: 'Estableix una comparació entre dos elements. La forma に比べ (sense て) és més formal i es usa en escriptura.',
    explanation_en: 'Establishes a comparison between two elements. The form に比べ (without て) is more formal and used in writing.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'base de comparación', label_ca: 'base de comparació', label_en: 'comparison base' },
      { text: 'に比べて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado', label_ca: 'resultat', label_en: 'result' },
    ],
    example: [
      { text: '去年に', furigana: 'きょねんに', role: 'time', gloss_es: 'al año pasado', gloss_ca: "a l'any passat", gloss_en: 'to last year' },
      { text: '比べて、', furigana: 'くらべて', role: 'particle', gloss_es: 'comparado con,', gloss_ca: 'comparat amb,', gloss_en: 'compared to,' },
      { text: '今年は', furigana: 'ことしは', role: 'topic', gloss_es: 'este año', gloss_ca: 'aquest any', gloss_en: 'this year' },
      { text: '暖かい。', furigana: 'あたたかい', role: 'adjective', gloss_es: 'es más cálido', gloss_ca: 'és més càlid', gloss_en: 'is warmer' },
    ],
    tip_es: 'También se puede decir ～と比べて. Con adjetivos suele acompañarse de ～より o ～のほうが.',
    tip_ca: 'També es pot dir ～と比べて. Amb adjectius sol acompanyar-se de ～より o ～のほうが.',
    tip_en: 'Can also use ～と比べて. With adjectives often paired with ～より or ～のほうが.',
  },
  {
    id: 'mnnc1-4-2',
    lesson: 4,
    number: 8,
    jlpt: 'N3',
    pattern: '〜一方で',
    name_es: 'Por otro lado ~, mientras que ~',
    name_ca: "D'altra banda ~, mentre que ~",
    name_en: 'On the other hand ~, while ~',
    explanation_es: 'Contrasta dos aspectos de un mismo tema. Puede indicar contraste ("por un lado... por otro") o acciones que ocurren en paralelo.',
    explanation_ca: "Contrasta dos aspectes d'un mateix tema. Pot indicar contrast o accions que ocorren en paral·lel.",
    explanation_en: 'Contrasts two aspects of the same topic. Can indicate contrast or parallel actions.',
    structure: [
      { text: 'V/N/adj (普通形)', role: 'verb', isSlot: true, label_es: 'aspecto 1', label_ca: 'aspecte 1', label_en: 'aspect 1' },
      { text: '一方で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'aspecto 2 (contraste)', label_ca: 'aspecte 2 (contrast)', label_en: 'aspect 2 (contrast)' },
    ],
    example: [
      { text: 'この薬は', furigana: 'このくすりは', role: 'topic', gloss_es: 'este medicamento', gloss_ca: 'aquest medicament', gloss_en: 'this medicine' },
      { text: '効果がある', furigana: 'こうかがある', role: 'verb', gloss_es: 'es eficaz', gloss_ca: 'és eficaç', gloss_en: 'is effective' },
      { text: '一方で、', role: 'key', gloss_es: 'por otro lado,', gloss_ca: "d'altra banda,", gloss_en: 'on the other hand,' },
      { text: '副作用も', furigana: 'ふくさようも', role: 'subject', gloss_es: 'también efectos secundarios', gloss_ca: 'també efectes secundaris', gloss_en: 'also side effects' },
      { text: 'ある。', role: 'verb', gloss_es: 'hay', gloss_ca: "n'hi ha", gloss_en: 'there are' },
    ],
    tip_es: 'Similar a が y けれども pero más formal. Con verbos puede indicar paralelismo ("mientras hace A, también hace B").',
    tip_ca: 'Similar a が i けれども però més formal. Amb verbs pot indicar paral·lelisme ("mentre fa A, també fa B").',
    tip_en: 'Similar to が and けれども but more formal. With verbs can indicate parallel actions.',
  },
]

const ch5: GrammarPoint[] = [
  {
    id: 'mnnc1-5-1',
    lesson: 5,
    number: 9,
    jlpt: 'N3',
    pattern: 'V/N に伴って',
    name_es: 'A medida que ~, junto con ~',
    name_ca: 'A mesura que ~, juntament amb ~',
    name_en: 'Along with ~, as ~ changes',
    explanation_es: 'Indica que un cambio ocurre en paralelo con otro. Ambos cambios suelen ir en la misma dirección. Registro formal/escrito.',
    explanation_ca: 'Indica que un canvi ocorre en paral·lel amb un altre. Tots dos canvis solen anar en la mateixa direcció. Registre formal/escrit.',
    explanation_en: 'Indicates that a change occurs in parallel with another. Both changes usually go in the same direction. Formal/written register.',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'cambio principal', label_ca: 'canvi principal', label_en: 'main change' },
      { text: 'に伴って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'cambio paralelo', label_ca: 'canvi paral·lel', label_en: 'parallel change' },
    ],
    example: [
      { text: '経済の', furigana: 'けいざいの', role: 'noun', gloss_es: 'de la economía', gloss_ca: "de l'economia", gloss_en: 'of the economy' },
      { text: '発展に', furigana: 'はってんに', role: 'noun', gloss_es: 'al desarrollo', gloss_ca: 'al desenvolupament', gloss_en: 'with the development' },
      { text: '伴って、', furigana: 'ともなって', role: 'particle', gloss_es: 'junto con,', gloss_ca: 'juntament amb,', gloss_en: 'along with,' },
      { text: '環境問題が', furigana: 'かんきょうもんだいが', role: 'subject', gloss_es: 'los problemas ambientales', gloss_ca: 'els problemes ambientals', gloss_en: 'environmental problems' },
      { text: '増えた。', furigana: 'ふえた', role: 'verb', gloss_es: 'aumentaron', gloss_ca: 'van augmentar', gloss_en: 'increased' },
    ],
    tip_es: 'Similar a ～につれて, pero に伴って es más formal y enfatiza que los cambios son concomitantes.',
    tip_ca: 'Similar a ～につれて, però に伴って és més formal i emfatitza que els canvis són concomitants.',
    tip_en: 'Similar to ～につれて but に伴って is more formal and emphasizes concomitant changes.',
  },
  {
    id: 'mnnc1-5-2',
    lesson: 5,
    number: 10,
    jlpt: 'N3',
    pattern: 'V辞書形/N に従って',
    name_es: 'Siguiendo ~, conforme a ~, a medida que ~',
    name_ca: "Seguint ~, d'acord amb ~, a mesura que ~",
    name_en: 'Following ~, in accordance with ~, as ~',
    explanation_es: 'Dos usos: (1) seguir instrucciones, reglas u órdenes; (2) indicar cambio gradual ("a medida que avanza el tiempo...").',
    explanation_ca: "Dos usos: (1) seguir instruccions, regles o ordres; (2) indicar canvi gradual (\"a mesura que avança el temps...\").",
    explanation_en: 'Two uses: (1) following instructions/rules/orders; (2) indicating gradual change ("as time passes...").',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'instrucción/cambio', label_ca: 'instrucció/canvi', label_en: 'instruction/change' },
      { text: 'に従って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción/resultado', label_ca: 'acció/resultat', label_en: 'action/result' },
    ],
    example: [
      { text: '先生の', furigana: 'せんせいの', role: 'noun', gloss_es: 'del profesor', gloss_ca: 'del professor', gloss_en: "of the teacher" },
      { text: '指示に', furigana: 'しじに', role: 'noun', gloss_es: 'las instrucciones', gloss_ca: 'les instruccions', gloss_en: 'the instructions' },
      { text: '従って、', furigana: 'したがって', role: 'particle', gloss_es: 'siguiendo,', gloss_ca: 'seguint,', gloss_en: 'following,' },
      { text: '問題を', furigana: 'もんだいを', role: 'object', gloss_es: 'el problema', gloss_ca: 'el problema', gloss_en: 'the problem' },
      { text: '解いた。', furigana: 'といた', role: 'verb', gloss_es: 'resolvió', gloss_ca: 'va resoldre', gloss_en: 'solved' },
    ],
    tip_es: 'Para el cambio gradual usa siempre la forma diccionario (年をとるに従って "a medida que envejeció").',
    tip_ca: 'Per al canvi gradual usa sempre la forma diccionari (年をとるに従って "a mesura que envellí").',
    tip_en: 'For gradual change always use dictionary form (年をとるに従って "as he aged").',
  },
]

const ch6: GrammarPoint[] = [
  {
    id: 'mnnc1-6-1',
    lesson: 6,
    number: 11,
    jlpt: 'N3',
    pattern: '〜はずがない',
    name_es: 'Es imposible que ~, no puede ser que ~',
    name_ca: 'És impossible que ~, no pot ser que ~',
    name_en: "There's no way that ~, it can't be that ~",
    explanation_es: 'Expresa que algo es imposible según el razonamiento o el conocimiento del hablante. Indica una negación lógica fuerte.',
    explanation_ca: "Expressa que alguna cosa és impossible segons el raonament o el coneixement del parlant. Indica una negació lògica forta.",
    explanation_en: "Expresses that something is impossible according to the speaker's reasoning or knowledge. A strong logical negation.",
    structure: [
      { text: 'V普通形/adj/N', role: 'verb', isSlot: true, label_es: 'hecho negado', label_ca: 'fet negat', label_en: 'negated fact' },
      { text: 'はずがない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '彼が', furigana: 'かれが', role: 'subject', gloss_es: 'él', gloss_ca: 'ell', gloss_en: 'he' },
      { text: 'そんなことを', role: 'object', gloss_es: 'algo así', gloss_ca: 'una cosa així', gloss_en: 'something like that' },
      { text: '言う', furigana: 'いう', role: 'verb', gloss_es: 'decir', gloss_ca: 'dir', gloss_en: 'say' },
      { text: 'はずがない。', role: 'key', gloss_es: 'es imposible que diga', gloss_ca: 'és impossible que digui', gloss_en: "there's no way he'd say" },
    ],
    tip_es: 'Compara: はずだ (debería ser), はずがない (es imposible). No confundir con わけがない (mismo significado pero más coloquial).',
    tip_ca: 'Compara: はずだ (hauria de ser), はずがない (és impossible). No confondre amb わけがない (mateix significat però més col·loquial).',
    tip_en: 'Compare: はずだ (should be), はずがない (impossible). わけがない has the same meaning but is more colloquial.',
  },
  {
    id: 'mnnc1-6-2',
    lesson: 6,
    number: 12,
    jlpt: 'N3',
    pattern: 'N 次第で/次第だ',
    name_es: 'Depende de ~, según ~',
    name_ca: 'Depèn de ~, segons ~',
    name_en: 'Depending on ~, it depends on ~',
    explanation_es: 'Indica que el resultado o la situación varía según algo. 次第だ es la forma predicativa ("todo depende de").',
    explanation_ca: "Indica que el resultat o la situació varia segons alguna cosa. 次第だ és la forma predicativa (\"tot depèn de\").",
    explanation_en: 'Indicates that the result or situation varies depending on something. 次第だ is the predicative form ("it all depends on").',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'factor determinante', label_ca: 'factor determinant', label_en: 'determining factor' },
      { text: '次第で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado variable', label_ca: 'resultat variable', label_en: 'variable result' },
    ],
    example: [
      { text: '結果は', furigana: 'けっかは', role: 'topic', gloss_es: 'el resultado', gloss_ca: 'el resultat', gloss_en: 'the result' },
      { text: 'あなたの', role: 'noun', gloss_es: 'de tu', gloss_ca: 'del teu', gloss_en: 'your' },
      { text: '努力次第だ。', furigana: 'どりょくしだいだ', role: 'key', gloss_es: 'depende del esfuerzo', gloss_ca: "depèn de l'esforç", gloss_en: 'depends on your effort' },
    ],
    tip_es: 'Diferente uso: V ます形+次第 significa "en cuanto haga ~" (nada más terminar). Aquí es N+次第で/次第だ (depender de).',
    tip_ca: 'Ús diferent: V ます形+次第 significa "en cuanto faci ~" (tot just acabar). Aquí és N+次第で/次第だ (dependre de).',
    tip_en: 'Different use: V ます stem + 次第 means "as soon as ~ is done". Here it is N + 次第で/次第だ (to depend on).',
  },
]

const ch7: GrammarPoint[] = [
  {
    id: 'mnnc1-7-1',
    lesson: 7,
    number: 13,
    jlpt: 'N3',
    pattern: 'N 向けに/向けの',
    name_es: 'Dirigido a ~, destinado a ~',
    name_ca: 'Adreçat a ~, destinat a ~',
    name_en: 'Aimed at ~, intended for ~',
    explanation_es: 'Indica que algo está diseñado o destinado para un público o propósito específico. 向けに modifica verbos; 向けの modifica sustantivos.',
    explanation_ca: "Indica que alguna cosa està dissenyada o destinada per a un públic o propòsit específic. 向けに modifica verbs; 向けの modifica substantius.",
    explanation_en: 'Indicates that something is designed or intended for a specific audience or purpose. 向けに modifies verbs; 向けの modifies nouns.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'destinatario', label_ca: 'destinatari', label_en: 'target audience' },
      { text: '向けに/向けの', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'producto/contenido', label_ca: 'producte/contingut', label_en: 'product/content' },
    ],
    example: [
      { text: 'これは', role: 'topic', gloss_es: 'esto', gloss_ca: 'això', gloss_en: 'this' },
      { text: '初心者', furigana: 'しょしんしゃ', role: 'noun', gloss_es: 'para principiantes', gloss_ca: 'per a principiants', gloss_en: 'for beginners' },
      { text: '向けの', role: 'particle', gloss_es: 'dirigido a', gloss_ca: 'adreçat a', gloss_en: 'aimed at' },
      { text: 'テキストです。', role: 'copula', gloss_es: 'es un libro de texto', gloss_ca: 'és un llibre de text', gloss_en: 'is a textbook' },
    ],
  },
  {
    id: 'mnnc1-7-2',
    lesson: 7,
    number: 14,
    jlpt: 'N3',
    pattern: '〜ものだ',
    name_es: 'Así son las cosas ~, se supone que ~',
    name_ca: 'Així són les coses ~, se suposa que ~',
    name_en: "That's just how things are ~, one is supposed to ~",
    explanation_es: 'Varios usos: (1) verdad general o expectativa social ("así debe ser"); (2) recuerdo nostálgico ("solía ~"); (3) admiración o sorpresa.',
    explanation_ca: "Diversos usos: (1) veritat general o expectativa social (\"així ha de ser\"); (2) record nostàlgic (\"solia ~\"); (3) admiració o sorpresa.",
    explanation_en: 'Several uses: (1) general truth or social expectation ("that\'s how it should be"); (2) nostalgic memory ("used to ~"); (3) admiration or surprise.',
    structure: [
      { text: 'V/adj (普通形)', role: 'verb', isSlot: true, label_es: 'norma/hábito/hecho', label_ca: 'norma/hàbit/fet', label_en: 'norm/habit/fact' },
      { text: 'ものだ', role: 'key', isSlot: false },
    ],
    example: [
      { text: '人に', furigana: 'ひとに', role: 'location', gloss_es: 'a las personas', gloss_ca: 'a les persones', gloss_en: 'to people' },
      { text: '会ったら', furigana: 'あったら', role: 'verb', gloss_es: 'cuando te encuentras', gloss_ca: 'quan et trobes', gloss_en: 'when you meet' },
      { text: 'あいさつする', role: 'verb', gloss_es: 'saludar', gloss_ca: 'saludar', gloss_en: 'greet' },
      { text: 'ものだ。', role: 'key', gloss_es: 'así debe hacerse', gloss_ca: "així s'ha de fer", gloss_en: "that's what you do" },
    ],
    tip_es: 'Para el uso nostálgico: 子どものころ、よく遊んだものだ "De niño, solía jugar mucho". Con ～たものだ.',
    tip_ca: 'Per a l\'ús nostàlgic: 子どものころ、よく遊んだものだ "De petit, solia jugar molt". Amb ～たものだ.',
    tip_en: 'For the nostalgic use: 子どものころ、よく遊んだものだ "As a child, I used to play a lot." Uses ～たものだ.',
  },
]

const ch8: GrammarPoint[] = [
  {
    id: 'mnnc1-8-1',
    lesson: 8,
    number: 15,
    jlpt: 'N3',
    pattern: '〜ものの',
    name_es: 'Aunque ~, si bien ~',
    name_ca: 'Tot i que ~, si bé ~',
    name_en: 'Although ~, even though ~',
    explanation_es: 'Conecta dos cláusulas donde la segunda contrasta o decepciona respecto a la primera. Similar a けれども pero más formal y con connotación de resultado inesperado o insatisfactorio.',
    explanation_ca: "Connecta dues clàusules on la segona contrasta o decepciona respecte a la primera. Similar a けれども però més formal i amb connotació de resultat inesperat o insatisfactori.",
    explanation_en: 'Connects two clauses where the second contrasts with or disappoints the first. More formal than けれども, with a nuance of unexpected or unsatisfactory result.',
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'premisa (aunque...)', label_ca: 'premissa (tot i que...)', label_en: 'premise (although...)' },
      { text: 'ものの', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado decepcionante', label_ca: 'resultat decebedor', label_en: 'disappointing result' },
    ],
    example: [
      { text: '日本語を', furigana: 'にほんごを', role: 'object', gloss_es: 'japonés', gloss_ca: 'japonès', gloss_en: 'Japanese' },
      { text: '勉強した', furigana: 'べんきょうした', role: 'verb', gloss_es: 'estudié', gloss_ca: 'vaig estudiar', gloss_en: 'studied' },
      { text: 'ものの、', role: 'key', gloss_es: 'aunque,', gloss_ca: 'tot i que,', gloss_en: 'although,' },
      { text: 'まだ', role: 'auxiliary', gloss_es: 'todavía', gloss_ca: 'encara', gloss_en: 'still' },
      { text: '話せない。', furigana: 'はなせない', role: 'verb', gloss_es: 'no puedo hablar', gloss_ca: 'no puc parlar', gloss_en: "can't speak it" },
    ],
    tip_es: 'El sujeto de ambas cláusulas suele ser el mismo. Se usa en textos formales; en coloquial se prefiere けれど.',
    tip_ca: 'El subjecte de les dues clàusules sol ser el mateix. S\'usa en textos formals; en col·loquial es prefereix けれど.',
    tip_en: 'The subject of both clauses is usually the same. Used in formal texts; colloquially けれど is preferred.',
  },
  {
    id: 'mnnc1-8-2',
    lesson: 8,
    number: 16,
    jlpt: 'N3',
    pattern: 'N に加えて',
    name_es: 'Además de ~, encima de ~',
    name_ca: 'A més de ~, a sobre de ~',
    name_en: 'In addition to ~, on top of ~',
    explanation_es: 'Indica que se suma algo a algo ya existente. La segunda cláusula añade información adicional, a menudo intensificando o agravando la situación.',
    explanation_ca: "Indica que s'afegeix alguna cosa a alguna cosa ja existent. La segona clàusula afegeix informació addicional, sovint intensificant o agreujant la situació.",
    explanation_en: 'Indicates that something is added to something already existing. The second clause adds further information, often intensifying or worsening the situation.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'elemento base', label_ca: 'element base', label_en: 'base element' },
      { text: 'に加えて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'elemento añadido', label_ca: 'element afegit', label_en: 'added element' },
    ],
    example: [
      { text: '雨に', furigana: 'あめに', role: 'noun', gloss_es: 'además de la lluvia', gloss_ca: 'a més de la pluja', gloss_en: 'in addition to the rain' },
      { text: '加えて、', furigana: 'くわえて', role: 'particle', gloss_es: 'encima,', gloss_ca: 'a sobre,', gloss_en: 'on top of that,' },
      { text: '風も', furigana: 'かぜも', role: 'subject', gloss_es: 'también el viento', gloss_ca: 'també el vent', gloss_en: 'also the wind' },
      { text: '強くなった。', furigana: 'つよくなった', role: 'verb', gloss_es: 'se hizo más fuerte', gloss_ca: 'es va fer més fort', gloss_en: 'became stronger' },
    ],
    tip_es: 'Similar a ～のみならず pero に加えて es más neutro y cotidiano. ～のみならず tiene un tono más enfático y formal.',
    tip_ca: 'Similar a ～のみならず però に加えて és més neutre i quotidià. ～のみならず té un to més emfàtic i formal.',
    tip_en: 'Similar to ～のみならず but に加えて is more neutral and everyday. ～のみならず is more emphatic and formal.',
  },
]

const ch9: GrammarPoint[] = [
  {
    id: 'mnnc1-9-1',
    lesson: 9,
    number: 17,
    jlpt: 'N3',
    pattern: '〜のみならず',
    name_es: 'No solo ~, sino también ~',
    name_ca: 'No només ~, sinó també ~',
    name_en: 'Not only ~, but also ~',
    explanation_es: 'Versión formal de だけでなく. Expresa que algo se extiende más allá de lo mencionado. Frecuente en escritura académica y noticias.',
    explanation_ca: 'Versió formal de だけでなく. Expressa que alguna cosa s\'estén més enllà del que s\'esmenta. Freqüent en escriptura acadèmica i notícies.',
    explanation_en: 'Formal version of だけでなく. Expresses that something extends beyond what is mentioned. Common in academic writing and news.',
    structure: [
      { text: 'N/V普通形/adj', role: 'noun', isSlot: true, label_es: 'elemento A', label_ca: 'element A', label_en: 'element A' },
      { text: 'のみならず', role: 'key', isSlot: false },
      { text: '〜も', role: 'key', isSlot: true, label_es: 'elemento B (también)', label_ca: 'element B (també)', label_en: 'element B (also)' },
    ],
    example: [
      { text: '日本のみならず、', furigana: 'にほんのみならず', role: 'noun', gloss_es: 'no solo en Japón sino también', gloss_ca: 'no només al Japó sinó també', gloss_en: 'not only in Japan but also' },
      { text: '世界中で', furigana: 'せかいじゅうで', role: 'location', gloss_es: 'en todo el mundo', gloss_ca: 'arreu del món', gloss_en: 'all over the world' },
      { text: '人気がある。', furigana: 'にんきがある', role: 'verb', gloss_es: 'es popular', gloss_ca: 'és popular', gloss_en: 'is popular' },
    ],
    tip_es: 'のみ = だけ (solo) en registro formal. Para el lenguaje cotidiano usa ～だけでなく o ～ばかりでなく.',
    tip_ca: 'のみ = だけ (només) en registre formal. Per al llenguatge quotidià usa ～だけでなく o ～ばかりでなく.',
    tip_en: 'のみ = だけ (only) in formal register. For everyday language use ～だけでなく or ～ばかりでなく.',
  },
  {
    id: 'mnnc1-9-2',
    lesson: 9,
    number: 18,
    jlpt: 'N3',
    pattern: '〜にもかかわらず',
    name_es: 'A pesar de ~, pese a ~',
    name_ca: 'Malgrat ~, tot i ~',
    name_en: 'Despite ~, in spite of ~',
    explanation_es: 'Indica que algo ocurre en contra de lo que cabría esperarse dada la situación. Más fuerte y formal que のに.',
    explanation_ca: "Indica que alguna cosa ocorre en contra del que s'esperaria donada la situació. Més fort i formal que のに.",
    explanation_en: "Indicates something happens contrary to what would be expected. Stronger and more formal than のに.",
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'obstáculo/circunstancia', label_ca: 'obstacle/circumstància', label_en: 'obstacle/circumstance' },
      { text: 'にもかかわらず', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado inesperado', label_ca: 'resultat inesperat', label_en: 'unexpected result' },
    ],
    example: [
      { text: '雨にも', furigana: 'あめにも', role: 'noun', gloss_es: 'a pesar de la lluvia', gloss_ca: 'malgrat la pluja', gloss_en: 'despite the rain' },
      { text: 'かかわらず、', role: 'key', gloss_es: 'pese a todo,', gloss_ca: 'malgrat tot,', gloss_en: 'in spite of,' },
      { text: '試合は', furigana: 'しあいは', role: 'topic', gloss_es: 'el partido', gloss_ca: 'el partit', gloss_en: 'the match' },
      { text: '行われた。', furigana: 'おこなわれた', role: 'verb', gloss_es: 'se celebró', gloss_ca: 'es va celebrar', gloss_en: 'was held' },
    ],
    tip_es: 'Compara con のに (frustración personal) y ながら (aunque). にもかかわらず es objetivo y formal.',
    tip_ca: "Compara amb のに (frustració personal) i ながら (tot i que). にもかかわらず és objectiu i formal.",
    tip_en: 'Compare with のに (personal frustration) and ながら (although). にもかかわらず is objective and formal.',
  },
]

const ch10: GrammarPoint[] = [
  {
    id: 'mnnc1-10-1',
    lesson: 10,
    number: 19,
    jlpt: 'N3',
    pattern: '〜ことなく',
    name_es: 'Sin ~, sin llegar a ~',
    name_ca: 'Sense ~, sense arribar a ~',
    name_en: 'Without doing ~, without ever ~',
    explanation_es: 'Indica que la acción principal ocurre sin realizar la acción mencionada. Equivale a ～ないで en registro formal/escrito.',
    explanation_ca: "Indica que l'acció principal ocorre sense realitzar l'acció esmentada. Equivalent a ～ないで en registre formal/escrit.",
    explanation_en: 'Indicates the main action occurs without performing the mentioned action. Equivalent to ～ないで in formal/written register.',
    structure: [
      { text: 'V辞書形', role: 'verb', isSlot: true, label_es: 'acción omitida', label_ca: 'acció omesa', label_en: 'omitted action' },
      { text: 'ことなく', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción principal', label_ca: 'acció principal', label_en: 'main action' },
    ],
    example: [
      { text: '休む', furigana: 'やすむ', role: 'verb', gloss_es: 'descansar', gloss_ca: 'descansar', gloss_en: 'resting' },
      { text: 'ことなく、', role: 'key', gloss_es: 'sin,', gloss_ca: 'sense,', gloss_en: 'without,' },
      { text: '三日間', furigana: 'みっかかん', role: 'time', gloss_es: 'durante tres días', gloss_ca: 'durant tres dies', gloss_en: 'for three days' },
      { text: '働き続けた。', furigana: 'はたらきつづけた', role: 'verb', gloss_es: 'siguió trabajando', gloss_ca: 'va seguir treballant', gloss_en: 'kept working' },
    ],
    tip_es: 'Solo se usa con verbos voluntarios. ～ことなく suena más literario que ～ないで; evita usarlo en conversación normal.',
    tip_ca: 'Només es fa servir amb verbs voluntaris. ～ことなく sona més literari que ～ないで; evita usar-lo en conversa normal.',
    tip_en: 'Only used with volitional verbs. ～ことなく sounds more literary than ～ないで; avoid in normal conversation.',
  },
  {
    id: 'mnnc1-10-2',
    lesson: 10,
    number: 20,
    jlpt: 'N3',
    pattern: '〜ほど〜ない / 〜ほど',
    name_es: 'No tan ~ como ~, tan ~ que ~',
    name_ca: 'No tan ~ com ~, tan ~ que ~',
    name_en: 'Not as ~ as ~, so ~ that ~',
    explanation_es: 'Dos usos: (1) comparación negativa (A は B ほど～ない = A no es tan ~ como B); (2) grado o cantidad extrema (〜ほど～ = tan/tanto que...).',
    explanation_ca: "Dos usos: (1) comparació negativa (A は B ほど～ない = A no és tan ~ com B); (2) grau o quantitat extrema (〜ほど～ = tan/tant que...).",
    explanation_en: 'Two uses: (1) negative comparison (A は B ほど～ない = A is not as ~ as B); (2) extreme degree (〜ほど～ = so ~ that...).',
    structure: [
      { text: 'N/V', role: 'noun', isSlot: true, label_es: 'estándar/grado', label_ca: 'estàndard/grau', label_en: 'standard/degree' },
      { text: 'ほど', role: 'particle', isSlot: false },
      { text: '〜ない / 〜', role: 'key', isSlot: true, label_es: 'comparación/resultado', label_ca: 'comparació/resultat', label_en: 'comparison/result' },
    ],
    example: [
      { text: '笑いが', furigana: 'わらいが', role: 'subject', gloss_es: 'la risa', gloss_ca: 'el riure', gloss_en: 'laughter' },
      { text: 'とまらない', furigana: 'とまらない', role: 'verb', gloss_es: 'no para', gloss_ca: 'no para', gloss_en: "doesn't stop" },
      { text: 'ほど', role: 'particle', gloss_es: 'tanto que', gloss_ca: 'tant que', gloss_en: 'so much that' },
      { text: '面白かった。', furigana: 'おもしろかった', role: 'adjective', gloss_es: 'fue divertido', gloss_ca: 'va ser divertit', gloss_en: 'it was funny' },
    ],
    tip_es: 'Uso 1 (comparación): この映画はあの映画ほど面白くない。Uso 2 (grado): 死ぬほど疲れた "Estoy muerto de cansancio".',
    tip_ca: "Ús 1 (comparació): この映画はあの映画ほど面白くない. Ús 2 (grau): 死ぬほど疲れた \"Estic mort de cansament\".",
    tip_en: 'Use 1 (comparison): この映画はあの映画ほど面白くない. Use 2 (degree): 死ぬほど疲れた "I\'m dead tired".',
  },
]

const ch11: GrammarPoint[] = [
  {
    id: 'mnnc1-11-1',
    lesson: 11,
    number: 21,
    jlpt: 'N3',
    pattern: 'N/V に対して',
    name_es: 'Hacia ~, respecto a ~, en contraste con ~',
    name_ca: 'Cap a ~, respecte a ~, en contrast amb ~',
    name_en: 'Towards ~, regarding ~, in contrast to ~',
    explanation_es: 'Tres usos: (1) dirección de una acción o emoción ("hacia, para"); (2) tema u objeto de atención ("respecto a"); (3) contraste ("mientras que A, B").',
    explanation_ca: "Tres usos: (1) direcció d'una acció o emoció (\"cap a, per a\"); (2) tema o objecte d'atenció (\"respecte a\"); (3) contrast (\"mentre que A, B\").",
    explanation_en: 'Three uses: (1) direction of an action or emotion ("towards, for"); (2) topic or object of attention ("regarding"); (3) contrast ("whereas A, B").',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'objetivo/tema', label_ca: 'objectiu/tema', label_en: 'target/topic' },
      { text: 'に対して', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción/actitud/contraste', label_ca: 'acció/actitud/contrast', label_en: 'action/attitude/contrast' },
    ],
    example: [
      { text: '子どもに', furigana: 'こどもに', role: 'location', gloss_es: 'hacia los niños', gloss_ca: 'cap als nens', gloss_en: 'towards children' },
      { text: '対して、', role: 'particle', gloss_es: 'respecto a,', gloss_ca: 'respecte a,', gloss_en: 'regarding,' },
      { text: '優しく', furigana: 'やさしく', role: 'adjective', gloss_es: 'con amabilidad', gloss_ca: 'amb amabilitat', gloss_en: 'kindly' },
      { text: 'すること。', role: 'verb', gloss_es: 'hay que comportarse', gloss_ca: "cal comportar-se", gloss_en: 'one should act' },
    ],
    tip_es: 'La forma に対する modifica sustantivos: 子どもに対する愛情 "el amor hacia los niños".',
    tip_ca: 'La forma に対する modifica substantius: 子どもに対する愛情 "l\'amor cap als nens".',
    tip_en: 'The form に対する modifies nouns: 子どもに対する愛情 "love towards children".',
  },
  {
    id: 'mnnc1-11-2',
    lesson: 11,
    number: 22,
    jlpt: 'N3',
    pattern: '〜というより',
    name_es: 'Más que ~, en lugar de decir ~',
    name_ca: 'Més que ~, en lloc de dir ~',
    name_en: 'Rather than ~, more like ~',
    explanation_es: 'Indica que la descripción o calificación que sigue es más precisa que la mencionada antes. Corrige o matiza una expresión.',
    explanation_ca: 'Indica que la descripció o qualificació que segueix és més precisa que la esmentada abans. Corregeix o matisa una expressió.',
    explanation_en: 'Indicates that the following description is more accurate than the one just mentioned. Corrects or nuances an expression.',
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'descripción imprecisa', label_ca: 'descripció imprecisa', label_en: 'imprecise description' },
      { text: 'というより', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'descripción más precisa', label_ca: 'descripció més precisa', label_en: 'more precise description' },
    ],
    example: [
      { text: '怒っている', furigana: 'おこっている', role: 'verb', gloss_es: 'estar enfadado', gloss_ca: 'estar enfadat', gloss_en: 'angry' },
      { text: 'というより、', role: 'key', gloss_es: 'más que,', gloss_ca: 'més que,', gloss_en: 'rather than,' },
      { text: '悲しんでいる', furigana: 'かなしんでいる', role: 'verb', gloss_es: 'está triste', gloss_ca: 'està trist', gloss_en: 'sad' },
      { text: 'んだ。', role: 'key', gloss_es: 'en realidad', gloss_ca: 'en realitat', gloss_en: 'actually' },
    ],
    tip_es: 'A menudo se sigue de むしろ para mayor énfasis: 怒っているというよりむしろ悲しんでいる.',
    tip_ca: 'Sovint es segueix de むしろ per a major èmfasi: 怒っているというよりむしろ悲しんでいる.',
    tip_en: 'Often followed by むしろ for extra emphasis: 怒っているというよりむしろ悲しんでいる.',
  },
]

const ch12: GrammarPoint[] = [
  {
    id: 'mnnc1-12-1',
    lesson: 12,
    number: 23,
    jlpt: 'N3',
    pattern: '〜あまり',
    name_es: 'De tanto ~, a causa del exceso de ~',
    name_ca: 'De tant ~, a causa de l\'excés de ~',
    name_en: 'So much ~, out of excessive ~',
    explanation_es: 'Indica que algo ocurre como resultado de un estado o emoción excesivos. El resultado es a menudo negativo o involuntario.',
    explanation_ca: "Indica que alguna cosa ocorre com a resultat d'un estat o emoció excessius. El resultat és sovint negatiu o involuntari.",
    explanation_en: 'Indicates that something occurs as a result of an excessive state or emotion. The result is often negative or involuntary.',
    structure: [
      { text: 'N の/V た形/adj', role: 'noun', isSlot: true, label_es: 'causa excesiva', label_ca: 'causa excessiva', label_en: 'excessive cause' },
      { text: 'あまり', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado (involuntario)', label_ca: 'resultat (involuntari)', label_en: 'result (involuntary)' },
    ],
    example: [
      { text: '嬉しさの', furigana: 'うれしさの', role: 'noun', gloss_es: 'de la alegría', gloss_ca: "de l'alegria", gloss_en: 'of joy' },
      { text: 'あまり、', role: 'key', gloss_es: 'de tanta,', gloss_ca: 'de tanta,', gloss_en: 'out of so much,' },
      { text: '泣いて', furigana: 'ないて', role: 'verb', gloss_es: 'lloró', gloss_ca: 'va plorar', gloss_en: 'cried' },
      { text: 'しまった。', role: 'auxiliary', gloss_es: 'sin querer', gloss_ca: 'sense voler', gloss_en: 'unintentionally' },
    ],
    tip_es: 'Con sustantivos: Nのあまり. Con verbos siempre forma ～た: 心配したあまり "de tanto preocuparse". No se usa con situaciones positivas intencionadas.',
    tip_ca: 'Amb substantius: Nのあまり. Amb verbs sempre forma ～た: 心配したあまり "de tant preocupar-se". No s\'usa amb situacions positives intencionades.',
    tip_en: 'With nouns: N の あまり. With verbs always use ～た form: 心配したあまり "from worrying so much". Not used for intentional positive situations.',
  },
  {
    id: 'mnnc1-12-2',
    lesson: 12,
    number: 24,
    jlpt: 'N3',
    pattern: 'V ます形 かねない',
    name_es: 'Podría ~, existe el riesgo de ~',
    name_ca: 'Podria ~, hi ha el risc de ~',
    name_en: 'Might ~, could possibly ~ (negative nuance)',
    explanation_es: 'Expresa que algo negativo o indeseable es posible o incluso probable si no se toma precaución. Siempre tiene connotación negativa.',
    explanation_ca: 'Expressa que alguna cosa negativa o indesitjable és possible o fins i tot probable si no es pren precaució. Sempre té connotació negativa.',
    explanation_en: 'Expresses that something negative or undesirable is possible or even likely if no precaution is taken. Always has a negative connotation.',
    structure: [
      { text: 'V ます形', role: 'verb', isSlot: true, label_es: 'acción negativa posible', label_ca: 'acció negativa possible', label_en: 'possible negative action' },
      { text: 'かねない', role: 'key', isSlot: false },
    ],
    example: [
      { text: 'このまま', role: 'auxiliary', gloss_es: 'si continúa así', gloss_ca: 'si continua així', gloss_en: 'at this rate' },
      { text: 'では、', role: 'particle', gloss_es: ',', gloss_ca: ',', gloss_en: ',' },
      { text: '大事故に', furigana: 'だいじこに', role: 'location', gloss_es: 'en un accidente grave', gloss_ca: 'en un accident greu', gloss_en: 'into a serious accident' },
      { text: 'なり', role: 'verb', gloss_es: 'podría convertirse', gloss_ca: 'podria convertir-se', gloss_en: 'could turn' },
      { text: 'かねない。', role: 'key', gloss_es: '(riesgo real)', gloss_ca: '(risc real)', gloss_en: '(real risk)' },
    ],
    tip_es: 'Diferente de かねる (no poder hacer, reticencia). かねない = puede llegar a (algo malo); かねる = no me es posible hacer.',
    tip_ca: 'Diferent de かねる (no poder fer, reticència). かねない = pot arribar a (alguna cosa dolenta); かねる = no em és possible fer.',
    tip_en: 'Different from かねる (unable to do, reluctance). かねない = could possibly (something bad happen); かねる = I cannot bring myself to do.',
  },
]

const ch13: GrammarPoint[] = [
  {
    id: 'mnnc1-13-1',
    lesson: 13,
    number: 25,
    jlpt: 'N3',
    pattern: 'V て / い adj くて たまらない',
    name_es: 'No puedo aguantar ~, es insoportablemente ~',
    name_ca: 'No puc aguantar ~, és insupportablement ~',
    name_en: "Can't stand ~, unbearably ~",
    explanation_es: 'Expresa que un sentimiento o estado es tan intenso que es difícil de soportar. Se usa con emociones, sensaciones físicas y deseos fuertes.',
    explanation_ca: 'Expressa que un sentiment o estat és tan intens que és difícil de suportar. S\'usa amb emocions, sensacions físiques i desitjos forts.',
    explanation_en: 'Expresses that a feeling or state is so intense it is hard to bear. Used with emotions, physical sensations, and strong desires.',
    structure: [
      { text: 'V て / い adj く', role: 'verb', isSlot: true, label_es: 'sentimiento/estado intenso', label_ca: 'sentiment/estat intens', label_en: 'intense feeling/state' },
      { text: 'たまらない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '眠くて', furigana: 'ねむくて', role: 'adjective', gloss_es: 'tanto sueño tengo que', gloss_ca: 'tant de son tinc que', gloss_en: "I'm so sleepy" },
      { text: 'たまらない。', role: 'key', gloss_es: 'no lo aguanto', gloss_ca: 'no ho aguanto', gloss_en: "I can't stand it" },
    ],
    tip_es: 'Similar a ～てしょうがない y ～てならない. たまらない es más coloquial; てならない es más formal/emocional.',
    tip_ca: 'Similar a ～てしょうがない i ～てならない. たまらない és més col·loquial; てならない és més formal/emocional.',
    tip_en: 'Similar to ～てしょうがない and ～てならない. たまらない is more colloquial; てならない is more formal/emotional.',
  },
  {
    id: 'mnnc1-13-2',
    lesson: 13,
    number: 26,
    jlpt: 'N3',
    pattern: '〜ばかりか〜も',
    name_es: 'No solo ~, sino incluso ~',
    name_ca: 'No només ~, sinó fins i tot ~',
    name_en: 'Not only ~, but even ~',
    explanation_es: 'Expresa que la situación va más allá de lo esperado, añadiendo un elemento adicional sorprendente o más extremo que el primero.',
    explanation_ca: "Expressa que la situació va més enllà del que s'esperava, afegint un element addicional sorprenent o més extrem que el primer.",
    explanation_en: 'Expresses that the situation goes beyond what was expected, adding a surprising or more extreme additional element.',
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'elemento A', label_ca: 'element A', label_en: 'element A' },
      { text: 'ばかりか', role: 'key', isSlot: false },
      { text: '〜も', role: 'key', isSlot: true, label_es: 'elemento B (más extremo)', label_ca: 'element B (més extrem)', label_en: 'element B (more extreme)' },
    ],
    example: [
      { text: '彼女は', furigana: 'かのじょは', role: 'topic', gloss_es: 'ella', gloss_ca: 'ella', gloss_en: 'she' },
      { text: '英語ばかりか', furigana: 'えいごばかりか', role: 'noun', gloss_es: 'no solo inglés sino', gloss_ca: 'no només anglès sinó', gloss_en: 'not only English but' },
      { text: 'フランス語も', role: 'noun', gloss_es: 'también francés', gloss_ca: 'també francès', gloss_en: 'also French' },
      { text: '話せる。', furigana: 'はなせる', role: 'verb', gloss_es: 'puede hablar', gloss_ca: 'pot parlar', gloss_en: 'can speak' },
    ],
    tip_es: 'Más enfático que だけでなく. El segundo elemento suele ser más sorprendente o extremo. También se dice ～ばかりでなく.',
    tip_ca: 'Més emfàtic que だけでなく. El segon element sol ser més sorprenent o extrem. També es diu ～ばかりでなく.',
    tip_en: 'More emphatic than だけでなく. The second element is usually more surprising or extreme. Also said as ～ばかりでなく.',
  },
]

const ch14: GrammarPoint[] = [
  {
    id: 'mnnc1-14-1',
    lesson: 14,
    number: 27,
    jlpt: 'N3',
    pattern: 'V ます形 ようがない',
    name_es: 'No hay manera de ~, es imposible ~',
    name_ca: 'No hi ha manera de ~, és impossible ~',
    name_en: "There's no way to ~, it's impossible to ~",
    explanation_es: 'Indica que no existe ningún método o posibilidad de realizar la acción. Más fuerte que できない; implica que la situación es irresoluble.',
    explanation_ca: "Indica que no hi ha cap mètode o possibilitat de realitzar l'acció. Més fort que できない; implica que la situació és irresoluble.",
    explanation_en: 'Indicates there is no method or possibility of performing the action. Stronger than できない; implies the situation is unsolvable.',
    structure: [
      { text: 'V ます形', role: 'verb', isSlot: true, label_es: 'acción imposible', label_ca: 'acció impossible', label_en: 'impossible action' },
      { text: 'ようがない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '連絡先が', furigana: 'れんらくさきが', role: 'subject', gloss_es: 'los datos de contacto', gloss_ca: 'les dades de contacte', gloss_en: 'contact details' },
      { text: 'わからないから、', role: 'verb', gloss_es: 'como no sé,', gloss_ca: 'com que no sé,', gloss_en: "since I don't know," },
      { text: '連絡し', furigana: 'れんらくし', role: 'verb', gloss_es: 'contactar', gloss_ca: 'contactar', gloss_en: 'contact' },
      { text: 'ようがない。', role: 'key', gloss_es: 'es imposible', gloss_ca: 'és impossible', gloss_en: "there's no way to" },
    ],
    tip_es: 'También se dice ～ようもない. Se construye siempre con el ます形 del verbo, no con el diccionario.',
    tip_ca: 'També es diu ～ようもない. Es construeix sempre amb el ます形 del verb, no amb el diccionari.',
    tip_en: 'Can also say ～ようもない. Always constructed with the ます stem, not the dictionary form.',
  },
  {
    id: 'mnnc1-14-2',
    lesson: 14,
    number: 28,
    jlpt: 'N3',
    pattern: 'N を通じて / を通して',
    name_es: 'A través de ~, mediante ~, durante todo ~',
    name_ca: 'A través de ~, mitjançant ~, durant tot ~',
    name_en: 'Through ~, via ~, throughout ~',
    explanation_es: 'Dos usos: (1) medio o intermediario ("a través de, por medio de"); (2) duración completa ("durante todo el año, a lo largo de"). を通じて es más formal.',
    explanation_ca: "Dos usos: (1) mitjà o intermediari (\"a través de, per mitjà de\"); (2) durada completa (\"durant tot l'any, al llarg de\"). を通じて és més formal.",
    explanation_en: 'Two uses: (1) means or intermediary ("through, by means of"); (2) entire duration ("throughout the year, throughout"). を通じて is more formal.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'medio/período', label_ca: 'mitjà/període', label_en: 'means/period' },
      { text: 'を通じて/を通して', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado/duración', label_ca: 'resultat/durada', label_en: 'result/duration' },
    ],
    example: [
      { text: 'インターネットを', role: 'object', gloss_es: 'mediante internet', gloss_ca: 'mitjançant internet', gloss_en: 'through the internet' },
      { text: '通して、', role: 'particle', gloss_es: 'a través de,', gloss_ca: 'a través de,', gloss_en: 'via,' },
      { text: '世界中と', furigana: 'せかいじゅうと', role: 'noun', gloss_es: 'con todo el mundo', gloss_ca: 'amb tot el món', gloss_en: 'with the whole world' },
      { text: 'つながれる。', role: 'verb', gloss_es: 'se puede conectar', gloss_ca: 'es pot connectar', gloss_en: 'can connect' },
    ],
    tip_es: 'Para la duración, el sujeto suele ser una palabra de tiempo: 一年を通じて (durante todo el año).',
    tip_ca: "Per a la durada, el subjecte sol ser una paraula de temps: 一年を通じて (durant tot l'any).",
    tip_en: 'For duration, the subject is usually a time word: 一年を通じて (throughout the year).',
  },
]

const ch15: GrammarPoint[] = [
  {
    id: 'mnnc1-15-1',
    lesson: 15,
    number: 29,
    jlpt: 'N3',
    pattern: 'N ごとに',
    name_es: 'Cada ~, por cada ~, cada vez que ~',
    name_ca: 'Cada ~, per cada ~, cada cop que ~',
    name_en: 'Every ~, each ~, every time ~',
    explanation_es: 'Indica repetición regular a intervalos de tiempo o cantidad, o que algo ocurre sin excepción en cada unidad.',
    explanation_ca: "Indica repetició regular a intervals de temps o quantitat, o que alguna cosa ocorre sense excepció en cada unitat.",
    explanation_en: 'Indicates regular repetition at time or quantity intervals, or that something occurs without exception for each unit.',
    structure: [
      { text: 'N/V辞書形', role: 'noun', isSlot: true, label_es: 'intervalo/evento', label_ca: 'interval/esdeveniment', label_en: 'interval/event' },
      { text: 'ごとに', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción repetida', label_ca: 'acció repetida', label_en: 'repeated action' },
    ],
    example: [
      { text: '三十分ごとに', furigana: 'さんじゅっぷんごとに', role: 'time', gloss_es: 'cada treinta minutos', gloss_ca: 'cada trenta minuts', gloss_en: 'every thirty minutes' },
      { text: 'バスが', role: 'subject', gloss_es: 'el autobús', gloss_ca: "l'autobús", gloss_en: 'a bus' },
      { text: '来る。', furigana: 'くる', role: 'verb', gloss_es: 'viene', gloss_ca: 've', gloss_en: 'comes' },
    ],
    tip_es: 'Compara con ～おきに (intervalos en el sentido de "dejando un espacio entre"): 一日おきに "cada dos días"; ごとに sería "cada día".',
    tip_ca: 'Compara amb ～おきに (intervals en el sentit de "deixant un espai entre"): 一日おきに "cada dos dies"; ごとに seria "cada dia".',
    tip_en: 'Compare with ～おきに (intervals meaning "leaving a gap"): 一日おきに "every other day"; ごとに would be "every day".',
  },
  {
    id: 'mnnc1-15-2',
    lesson: 15,
    number: 30,
    jlpt: 'N3',
    pattern: '〜につれて',
    name_es: 'A medida que ~, conforme ~',
    name_ca: 'A mesura que ~, a mesura que ~',
    name_en: 'As ~, in proportion to ~',
    explanation_es: 'Indica que dos cambios progresan juntos de forma gradual. La segunda cláusula cambia en correlación con la primera. Solo con verbos o adjetivos que expresan cambio.',
    explanation_ca: "Indica que dos canvis progressen junts de forma gradual. La segona clàusula canvia en correlació amb la primera. Només amb verbs o adjectius que expressen canvi.",
    explanation_en: 'Indicates that two changes progress together gradually. The second clause changes in correlation with the first. Only with verbs or adjectives expressing change.',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'cambio 1', label_ca: 'canvi 1', label_en: 'change 1' },
      { text: 'につれて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'cambio 2 (correlacionado)', label_ca: 'canvi 2 (correlacionat)', label_en: 'change 2 (correlated)' },
    ],
    example: [
      { text: '年をとる', furigana: 'としをとる', role: 'verb', gloss_es: 'envejecer', gloss_ca: 'envellir', gloss_en: 'aging' },
      { text: 'につれて、', role: 'particle', gloss_es: 'a medida que,', gloss_ca: 'a mesura que,', gloss_en: 'as,' },
      { text: '体力が', furigana: 'たいりょくが', role: 'subject', gloss_es: 'la fuerza física', gloss_ca: 'la força física', gloss_en: 'physical strength' },
      { text: '落ちる。', furigana: 'おちる', role: 'verb', gloss_es: 'decrece', gloss_ca: 'disminueix', gloss_en: 'declines' },
    ],
    tip_es: 'Similar a ～に伴って pero につれて hace más énfasis en el cambio gradual proporcional. No usar con acciones puntuales.',
    tip_ca: 'Similar a ～に伴って però につれて fa més èmfasi en el canvi gradual proporcional. No usar amb accions puntuals.',
    tip_en: 'Similar to ～に伴って but につれて emphasizes gradual proportional change more. Do not use with one-time actions.',
  },
]

const ch16: GrammarPoint[] = [
  {
    id: 'mnnc1-16-1',
    lesson: 16,
    number: 31,
    jlpt: 'N3',
    pattern: 'V て / い adj くて たまらない → てならない',
    name_es: 'No puedo evitar sentir ~, profundamente ~',
    name_ca: 'No puc evitar sentir ~, profundament ~',
    name_en: "Can't help feeling ~, deeply ~",
    explanation_es: 'Expresa un sentimiento interior muy fuerte, a menudo emocional o mental, que surge de forma natural. Más formal y emocional que たまらない. No se usa para deseos activos.',
    explanation_ca: "Expressa un sentiment interior molt fort, sovint emocional o mental, que sorgeix de forma natural. Més formal i emocional que たまらない. No s'usa per a desitjos actius.",
    explanation_en: 'Expresses a strong inner feeling, often emotional or mental, that arises naturally. More formal and emotional than たまらない. Not used for active desires.',
    structure: [
      { text: 'V て / い adj く', role: 'verb', isSlot: true, label_es: 'sentimiento intenso', label_ca: 'sentiment intens', label_en: 'intense feeling' },
      { text: 'てならない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '故郷が', furigana: 'こきょうが', role: 'subject', gloss_es: 'mi tierra natal', gloss_ca: 'la meva terra natal', gloss_en: 'my hometown' },
      { text: '懐かしくて', furigana: 'なつかしくて', role: 'adjective', gloss_es: 'es tan nostálgica que', gloss_ca: 'és tan nostàlgica que', gloss_en: 'is so nostalgic that' },
      { text: 'ならない。', role: 'key', gloss_es: 'no puedo evitarlo', gloss_ca: 'no puc evitar-ho', gloss_en: "I can't help it" },
    ],
    tip_es: 'Solo con sentimientos que surgen espontáneamente (nostalgia, soledad, alegría). NO con deseos: ×食べたくてならない (usa たまらない).',
    tip_ca: "Només amb sentiments que sorgeixen espontàniament (nostàlgia, solitud, alegria). NO amb desitjos: ×食べたくてならない (usa たまらない).",
    tip_en: 'Only with feelings that arise spontaneously (nostalgia, loneliness, joy). NOT with desires: ×食べたくてならない (use たまらない).',
  },
  {
    id: 'mnnc1-16-2',
    lesson: 16,
    number: 32,
    jlpt: 'N3',
    pattern: 'V 意向形/辞書形 まい',
    name_es: 'No voy a ~, probablemente no ~',
    name_ca: 'No vaig a ~, probablement no ~',
    name_en: "Won't ~, probably won't ~",
    explanation_es: 'Expresa la intención negativa del hablante ("no voy a hacer") o una negación de probabilidad ("probablemente no"). Registro formal/escrito. Equivale a ～ないだろう o ～ないつもりだ.',
    explanation_ca: "Expressa la intenció negativa del parlant (\"no vaig a fer\") o una negació de probabilitat (\"probablement no\"). Registre formal/escrit. Equivalent a ～ないだろう o ～ないつもりだ.",
    explanation_en: 'Expresses the speaker\'s negative intention ("won\'t do") or negation of probability ("probably won\'t"). Formal/written register. Equivalent to ～ないだろう or ～ないつもりだ.',
    structure: [
      { text: 'V 辞書形/意向形', role: 'verb', isSlot: true, label_es: 'acción negada', label_ca: 'acció negada', label_en: 'negated action' },
      { text: 'まい', role: 'key', isSlot: false },
    ],
    example: [
      { text: 'もう二度と', furigana: 'もうにどと', role: 'time', gloss_es: 'nunca más', gloss_ca: 'mai més', gloss_en: 'never again' },
      { text: '遅刻する', furigana: 'ちこくする', role: 'verb', gloss_es: 'llegar tarde', gloss_ca: 'arribar tard', gloss_en: 'be late' },
      { text: 'まいと', role: 'key', gloss_es: 'con la intención de no', gloss_ca: "amb la intenció de no", gloss_en: 'with the intention of not' },
      { text: '決めた。', furigana: 'きめた', role: 'verb', gloss_es: 'decidió', gloss_ca: 'va decidir', gloss_en: 'decided' },
    ],
    tip_es: 'Con する: するまい o しまい. Con くる: くるまい o こまい. En conversación normal usa ～ないつもりだ o ～ないだろう.',
    tip_ca: 'Amb する: するまい o しまい. Amb くる: くるまい o こまい. En conversa normal usa ～ないつもりだ o ～ないだろう.',
    tip_en: 'With する: するまい or しまい. With くる: くるまい or こまい. In normal conversation use ～ないつもりだ or ～ないだろう.',
  },
]

const ch17: GrammarPoint[] = [
  {
    id: 'mnnc1-17-1',
    lesson: 17,
    number: 33,
    jlpt: 'N3',
    pattern: '〜に違いない',
    name_es: 'Sin duda ~, seguramente ~, debe de ~',
    name_ca: 'Sens dubte ~, segurament ~, ha de ~',
    name_en: 'Must be ~, no doubt ~, surely ~',
    explanation_es: 'Expresa una certeza o convicción fuerte del hablante basada en la evidencia. Más fuerte que だろう y はずだ.',
    explanation_ca: "Expressa una certesa o convicció forta del parlant basada en l'evidència. Més fort que だろう i はずだ.",
    explanation_en: "Expresses the speaker's strong certainty or conviction based on evidence. Stronger than だろう and はずだ.",
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'hecho inferido', label_ca: 'fet inferit', label_en: 'inferred fact' },
      { text: 'に違いない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '電気が', furigana: 'でんきが', role: 'subject', gloss_es: 'la luz', gloss_ca: 'el llum', gloss_en: 'the light' },
      { text: 'ついているから、', role: 'verb', gloss_es: 'como está encendida,', gloss_ca: "com que és encesa,", gloss_en: "since it's on," },
      { text: '誰かが', furigana: 'だれかが', role: 'subject', gloss_es: 'alguien', gloss_ca: 'algú', gloss_en: 'someone' },
      { text: 'いるに', role: 'verb', gloss_es: 'debe de estar', gloss_ca: "ha d'estar", gloss_en: 'must be' },
      { text: '違いない。', furigana: 'ちがいない', role: 'key', gloss_es: 'sin duda', gloss_ca: 'sens dubte', gloss_en: 'no doubt' },
    ],
    tip_es: 'Escala de certeza: かもしれない < だろう < はずだ < に違いない. Con に違いない el hablante está casi seguro.',
    tip_ca: "Escala de certesa: かもしれない < だろう < はずだ < に違いない. Amb に違いない el parlant n'està gairebé segur.",
    tip_en: 'Certainty scale: かもしれない < だろう < はずだ < に違いない. With に違いない the speaker is almost certain.',
  },
  {
    id: 'mnnc1-17-2',
    lesson: 17,
    number: 34,
    jlpt: 'N3',
    pattern: 'V た / N の 上で',
    name_es: 'Después de ~, habiendo hecho ~',
    name_ca: 'Després de ~, havent fet ~',
    name_en: 'After doing ~, having done ~',
    explanation_es: 'Indica que la acción principal se realiza después de completar la primera y teniendo en cuenta los resultados. Implica deliberación o preparación previa.',
    explanation_ca: "Indica que l'acció principal es realitza després de completar la primera i tenint en compte els resultats. Implica deliberació o preparació prèvia.",
    explanation_en: 'Indicates the main action is performed after completing the first and taking the results into account. Implies deliberation or prior preparation.',
    structure: [
      { text: 'V た形', role: 'verb', isSlot: true, label_es: 'acción preparatoria', label_ca: 'acció preparatòria', label_en: 'preparatory action' },
      { text: '上で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción principal', label_ca: 'acció principal', label_en: 'main action' },
    ],
    example: [
      { text: 'よく考えた', furigana: 'よくかんがえた', role: 'verb', gloss_es: 'reflexionar bien', gloss_ca: 'reflexionar bé', gloss_en: 'thinking carefully' },
      { text: '上で、', role: 'key', gloss_es: 'después de,', gloss_ca: 'després de,', gloss_en: 'after,' },
      { text: '返事を', furigana: 'へんじを', role: 'object', gloss_es: 'la respuesta', gloss_ca: 'la resposta', gloss_en: 'the answer' },
      { text: 'ください。', role: 'key', gloss_es: 'deme por favor', gloss_ca: "doni'm si us plau", gloss_en: 'please give me' },
    ],
    tip_es: 'No confundir con 上に (además de). 上で siempre implica secuencia temporal y consideración. Con N の上で: 相談の上で "después de consultar".',
    tip_ca: 'No confondre amb 上に (a més de). 上で sempre implica seqüència temporal i consideració. Amb N の上で: 相談の上で "després de consultar".',
    tip_en: 'Don\'t confuse with 上に (in addition to). 上で always implies temporal sequence and consideration. With N の上で: 相談の上で "after consulting".',
  },
]

const ch18: GrammarPoint[] = [
  {
    id: 'mnnc1-18-1',
    lesson: 18,
    number: 35,
    jlpt: 'N3',
    pattern: 'N をはじめ(として)',
    name_es: 'Empezando por ~, entre ellos ~',
    name_ca: 'Començant per ~, entre ells ~',
    name_en: 'Starting with ~, including ~',
    explanation_es: 'Introduce el ejemplo más representativo de un grupo, indicando que hay más elementos incluidos. El sustantivo es el miembro más destacado.',
    explanation_ca: "Introdueix l'exemple més representatiu d'un grup, indicant que hi ha més elements inclosos. El substantiu és el membre més destacat.",
    explanation_en: 'Introduces the most representative example of a group, indicating there are more elements included. The noun is the most notable member.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'ejemplo más destacado', label_ca: 'exemple més destacat', label_en: 'most notable example' },
      { text: 'をはじめ', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'grupo/otros elementos', label_ca: 'grup/altres elements', label_en: 'group/other elements' },
    ],
    example: [
      { text: '東京をはじめ、', furigana: 'とうきょうをはじめ', role: 'noun', gloss_es: 'empezando por Tokio,', gloss_ca: 'començant per Tòquio,', gloss_en: 'starting with Tokyo,' },
      { text: '大阪・名古屋など', furigana: 'おおさかなごや', role: 'noun', gloss_es: 'Osaka, Nagoya, etc.', gloss_ca: 'Osaka, Nagoya, etc.', gloss_en: 'Osaka, Nagoya, etc.' },
      { text: '大都市では', furigana: 'だいとしでは', role: 'location', gloss_es: 'en las grandes ciudades', gloss_ca: 'a les grans ciutats', gloss_en: 'in major cities' },
      { text: '人口が増えている。', furigana: 'じんこうがふえている', role: 'verb', gloss_es: 'la población está aumentando', gloss_ca: 'la població augmenta', gloss_en: 'the population is growing' },
    ],
    tip_es: 'Similar a ～など, pero をはじめ indica que el primer sustantivo es el ejemplo principal y más importante del grupo.',
    tip_ca: "Similar a ～など, però をはじめ indica que el primer substantiu és l'exemple principal i més important del grup.",
    tip_en: 'Similar to ～など, but をはじめ indicates the first noun is the main and most important example of the group.',
  },
  {
    id: 'mnnc1-18-2',
    lesson: 18,
    number: 36,
    jlpt: 'N3',
    pattern: 'N はもちろん',
    name_es: 'Por supuesto ~, no solo ~, ni que decir tiene ~',
    name_ca: 'Per descomptat ~, no només ~, ni cal dir ~',
    name_en: 'Of course ~, not only ~, needless to say ~',
    explanation_es: 'Indica que algo es obvio o evidente, y que además hay algo más. El primer elemento es esperado; el segundo añade información sorprendente o adicional.',
    explanation_ca: "Indica que alguna cosa és òbvia o evident, i que a més hi ha alguna cosa més. El primer element és esperat; el segon afegeix informació sorprenent o addicional.",
    explanation_en: 'Indicates that something is obvious or expected, and additionally there is something more. The first element is expected; the second adds surprising or additional information.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'elemento obvio', label_ca: 'element obvi', label_en: 'obvious element' },
      { text: 'はもちろん', role: 'key', isSlot: false },
      { text: '〜も', role: 'key', isSlot: true, label_es: 'elemento adicional', label_ca: 'element addicional', label_en: 'additional element' },
    ],
    example: [
      { text: '日本語はもちろん、', furigana: 'にほんごはもちろん', role: 'noun', gloss_es: 'no solo japonés,', gloss_ca: 'no només japonès,', gloss_en: 'not only Japanese,' },
      { text: '英語も', furigana: 'えいごも', role: 'noun', gloss_es: 'también inglés', gloss_ca: 'també anglès', gloss_en: 'also English' },
      { text: '話せます。', furigana: 'はなせます', role: 'verb', gloss_es: 'puede hablar', gloss_ca: 'pot parlar', gloss_en: 'can speak' },
    ],
    tip_es: 'Similar a ～だけでなく, pero はもちろん enfatiza que el primer elemento es completamente esperado o dado por sentado.',
    tip_ca: 'Similar a ～だけでなく, però はもちろん emfatitza que el primer element és completament esperat o donat per descomptat.',
    tip_en: 'Similar to ～だけでなく, but はもちろん emphasizes the first element is completely expected or taken for granted.',
  },
]

const ch19: GrammarPoint[] = [
  {
    id: 'mnnc1-19-1',
    lesson: 19,
    number: 37,
    jlpt: 'N3',
    pattern: '〜からこそ',
    name_es: 'Precisamente porque ~, justamente por ~',
    name_ca: 'Precisament perquè ~, justament per ~',
    name_en: 'Precisely because ~, the very reason why ~',
    explanation_es: 'Enfatiza que la razón indicada es la causa fundamental o única de algo. こそ añade énfasis a から. Implica que sin esa causa, el resultado no sería el mismo.',
    explanation_ca: "Emfatitza que la raó indicada és la causa fonamental o única d'alguna cosa. こそ afegeix èmfasi a から. Implica que sense aquella causa, el resultat no seria el mateix.",
    explanation_en: 'Emphasizes that the stated reason is the fundamental or only cause of something. こそ adds emphasis to から. Implies that without that cause, the result would be different.',
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'causa fundamental', label_ca: 'causa fonamental', label_en: 'fundamental cause' },
      { text: 'からこそ', role: 'key', isSlot: false },
      { text: '〜のだ', role: 'key', isSlot: true, label_es: 'resultado', label_ca: 'resultat', label_en: 'result' },
    ],
    example: [
      { text: '信頼して', furigana: 'しんらいして', role: 'verb', gloss_es: 'precisamente porque confío', gloss_ca: 'precisament perquè confio', gloss_en: 'precisely because I trust you' },
      { text: 'いるからこそ、', role: 'key', gloss_es: 'es justamente por eso que', gloss_ca: "és justament per això que", gloss_en: 'that is why' },
      { text: '厳しく', furigana: 'きびしく', role: 'adjective', gloss_es: 'con dureza', gloss_ca: 'amb duresa', gloss_en: 'strictly' },
      { text: '言うんだ。', role: 'verb', gloss_es: 'te lo digo', gloss_ca: "t'ho dic", gloss_en: 'I say it' },
    ],
    tip_es: 'El resultado suele ser algo positivo o justificado. からこそ a menudo aparece con de, んだ o のだ al final para mayor énfasis.',
    tip_ca: 'El resultat sol ser alguna cosa positiva o justificada. からこそ sovint apareix amb de, んだ o のだ al final per a major èmfasi.',
    tip_en: 'The result is usually something positive or justified. からこそ often appears with で, んだ, or のだ at the end for further emphasis.',
  },
  {
    id: 'mnnc1-19-2',
    lesson: 19,
    number: 38,
    jlpt: 'N3',
    pattern: '〜ということは',
    name_es: 'Si ~ es así, entonces ~; lo que significa ~',
    name_ca: 'Si ~ és així, aleshores ~; el que significa ~',
    name_en: 'If that means ~, then ~; that is to say ~',
    explanation_es: 'Introduce una conclusión o implicación lógica a partir de lo que se acaba de decir o de un hecho dado. El hablante deriva o reconfirma una interpretación.',
    explanation_ca: "Introdueix una conclusió o implicació lògica a partir del que s'acaba de dir o d'un fet donat. El parlant deriva o reconfirma una interpretació.",
    explanation_en: 'Introduces a logical conclusion or implication from what was just said or a given fact. The speaker derives or reconfirms an interpretation.',
    structure: [
      { text: '〜', role: 'verb', isSlot: true, label_es: 'hecho/premisa', label_ca: 'fet/premissa', label_en: 'fact/premise' },
      { text: 'ということは', role: 'key', isSlot: false },
      { text: '〜ということだ', role: 'key', isSlot: true, label_es: 'conclusión derivada', label_ca: 'conclusió derivada', label_en: 'derived conclusion' },
    ],
    example: [
      { text: '彼が来ない', furigana: 'かれがこない', role: 'verb', gloss_es: 'que él no viene', gloss_ca: 'que ell no ve', gloss_en: "that he won't come" },
      { text: 'ということは、', role: 'key', gloss_es: 'lo que significa es que', gloss_ca: 'el que significa és que', gloss_en: 'which means that' },
      { text: '会議は', furigana: 'かいぎは', role: 'topic', gloss_es: 'la reunión', gloss_ca: 'la reunió', gloss_en: 'the meeting' },
      { text: '中止だ。', furigana: 'ちゅうしだ', role: 'key', gloss_es: 'está cancelada', gloss_ca: 'està cancel·lada', gloss_en: 'is cancelled' },
    ],
    tip_es: 'Se usa al inicio de oración para razonar en voz alta. A menudo termina con ～ということだ o ～ということになる.',
    tip_ca: "S'usa a l'inici d'oració per a raonar en veu alta. Sovint acaba amb ～ということだ o ～ということになる.",
    tip_en: 'Used at the start of a sentence to reason out loud. Often ends with ～ということだ or ～ということになる.',
  },
]

const ch20: GrammarPoint[] = [
  {
    id: 'mnnc1-20-1',
    lesson: 20,
    number: 39,
    jlpt: 'N3',
    pattern: 'V ずにはいられない',
    name_es: 'No puedo evitar ~, inevitablemente ~',
    name_ca: 'No puc evitar ~, inevitablement ~',
    name_en: "Can't help but ~, can't stop oneself from ~",
    explanation_es: 'Expresa que el hablante no puede evitar hacer algo aunque quisiera, porque el impulso es demasiado fuerte. Es más formal que ～てしまう.',
    explanation_ca: "Expressa que el parlant no pot evitar fer alguna cosa encara que volgués, perquè l'impuls és massa fort. És més formal que ～てしまう.",
    explanation_en: "Expresses that the speaker can't avoid doing something even if they wanted to, because the impulse is too strong. More formal than ～てしまう.",
    structure: [
      { text: 'V ない形 (ず形)', role: 'verb', isSlot: true, label_es: 'acción inevitable', label_ca: 'acció inevitable', label_en: 'inevitable action' },
      { text: 'にはいられない', role: 'key', isSlot: false },
    ],
    example: [
      { text: 'あの映画を', furigana: 'あのえいがを', role: 'object', gloss_es: 'esa película', gloss_ca: 'aquella pel·lícula', gloss_en: 'that movie' },
      { text: '見ずには', furigana: 'みずには', role: 'verb', gloss_es: 'sin verla', gloss_ca: 'sense veure-la', gloss_en: 'without watching it' },
      { text: 'いられない。', role: 'key', gloss_es: 'no puedo estar', gloss_ca: 'no puc estar', gloss_en: "can't help but watch" },
    ],
    tip_es: 'Construcción: V ない形 → ず (excepto: しない→せず/しず, こない→こず). Equivalente coloquial: ～ないではいられない.',
    tip_ca: "Construcció: V ない形 → ず (excepte: しない→せず/しず, こない→こず). Equivalent col·loquial: ～ないではいられない.",
    tip_en: 'Construction: V ない form → ず (except: しない→せず, こない→こず). Colloquial equivalent: ～ないではいられない.',
  },
  {
    id: 'mnnc1-20-2',
    lesson: 20,
    number: 40,
    jlpt: 'N3',
    pattern: 'V 辞書形 わけにはいかない',
    name_es: 'No puedo permitirme ~, no me es posible ~',
    name_ca: 'No em puc permetre ~, no em és possible ~',
    name_en: "Can't afford to ~, it wouldn't do to ~",
    explanation_es: 'Indica que algo no se puede hacer por razones sociales, morales o de las circunstancias, aunque el hablante pudiera o quisiera hacerlo.',
    explanation_ca: "Indica que alguna cosa no es pot fer per raons socials, morals o de les circumstàncies, encara que el parlant pogués o volgués fer-ho.",
    explanation_en: "Indicates something cannot be done due to social, moral, or circumstantial reasons, even if the speaker could or wanted to do it.",
    structure: [
      { text: 'V 辞書形', role: 'verb', isSlot: true, label_es: 'acción no permisible', label_ca: 'acció no permissible', label_en: 'impermissible action' },
      { text: 'わけにはいかない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '試験が', furigana: 'しけんが', role: 'subject', gloss_es: 'el examen', gloss_ca: "l'examen", gloss_en: 'the exam' },
      { text: 'あるから、', role: 'verb', gloss_es: 'como tengo,', gloss_ca: 'com que tinc,', gloss_en: 'since there is,' },
      { text: '休む', furigana: 'やすむ', role: 'verb', gloss_es: 'faltar', gloss_ca: 'faltar', gloss_en: 'miss it' },
      { text: 'わけには', role: 'key', gloss_es: 'no puedo permitirme', gloss_ca: 'no em puc permetre', gloss_en: "I can't afford to" },
      { text: 'いかない。', role: 'key', gloss_es: '(no está bien)', gloss_ca: "(no és correcte)", gloss_en: '(it just won\'t do)' },
    ],
    tip_es: 'Compara: できない (incapacidad física/técnica) vs わけにはいかない (restricción social/moral). La forma negativa ～ないわけにはいかない = "debo hacerlo sin falta".',
    tip_ca: "Compara: できない (incapacitat física/tècnica) vs わけにはいかない (restricció social/moral). La forma negativa ～ないわけにはいかない = \"he de fer-ho sense falta\".",
    tip_en: "Compare: できない (physical/technical inability) vs わけにはいかない (social/moral restriction). The negative ～ないわけにはいかない = \"I must do it without fail\".",
  },
]

export const MNN_C1_GRAMMAR_POINTS: GrammarPoint[] = [
  ...ch1, ...ch2, ...ch3, ...ch4, ...ch5,
  ...ch6, ...ch7, ...ch8, ...ch9, ...ch10,
  ...ch11, ...ch12, ...ch13, ...ch14, ...ch15,
  ...ch16, ...ch17, ...ch18, ...ch19, ...ch20,
]
