import type { GrammarPoint } from './grammar-mnn1'

// ─── Minna no Nihongo Chūkyū I ──────────────────────────────────────────────
// みんなの日本語 中級I · Lecciones 1-20 · JLPT N3

const ch1: GrammarPoint[] = [
  {
    id: 'mnnc1-1-1',
    lesson: 1,
    number: 1,
    jlpt: 'N3',
    pattern: 'N にとって',
    name_es: 'Para ~, desde el punto de vista de ~',
    name_ca: 'Per a ~, des del punt de vista de ~',
    name_en: 'For ~, from the perspective of ~',
    explanation_es: 'Indica el punto de vista de una persona o grupo respecto a algo. Expresa cómo algo parece, afecta o tiene valor para alguien específico.',
    explanation_ca: "Indica el punt de vista d'una persona o grup respecte a alguna cosa. Expressa com alguna cosa sembla, afecta o té valor per a algú específic.",
    explanation_en: 'Indicates the standpoint of a person or group regarding something. Expresses how something seems, affects, or has value for someone.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'persona/grupo', label_ca: 'persona/grup', label_en: 'person/group' },
      { text: 'にとって', role: 'particle', isSlot: false },
      { text: '述語', role: 'key', isSlot: true, label_es: 'predicado', label_ca: 'predicat', label_en: 'predicate' },
    ],
    example: [
      { text: '日本語は', furigana: 'にほんごは', role: 'topic', gloss_es: 'el japonés', gloss_ca: 'el japonès', gloss_en: 'Japanese' },
      { text: '私に', furigana: 'わたしに', role: 'noun', gloss_es: 'para mí', gloss_ca: 'per a mi', gloss_en: 'for me' },
      { text: 'とって', role: 'particle', gloss_es: '(perspectiva)', gloss_ca: '(perspectiva)', gloss_en: '(perspective)' },
      { text: '難しい', furigana: 'むずかしい', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'です。', role: 'copula', gloss_es: 'es', gloss_ca: 'és', gloss_en: 'is' },
    ],
    tip_es: 'No confundir con ～のために (propósito). にとって solo expresa perspectiva o evaluación subjetiva.',
    tip_ca: 'No confondre amb ～のために (propòsit). にとって només expressa perspectiva o avaluació subjectiva.',
    tip_en: "Don't confuse with ～のために (purpose). にとって only expresses perspective or subjective evaluation.",
  },
  {
    id: 'mnnc1-1-2',
    lesson: 1,
    number: 2,
    jlpt: 'N3',
    pattern: '〜ということだ',
    name_es: 'Lo que significa es ~, dicen que ~',
    name_ca: 'El que significa és ~, diuen que ~',
    name_en: 'That means ~, I heard that ~',
    explanation_es: 'Dos usos: (1) reformular o aclarar el significado de algo ("eso significa que"); (2) transmitir información de segunda mano ("dicen que", "he oído que").',
    explanation_ca: "Dos usos: (1) reformular o aclarir el significat d'alguna cosa (\"això significa\"); (2) transmetre informació de segona mà (\"diuen que\", \"he sentit que\").",
    explanation_en: 'Two uses: (1) to rephrase or clarify something ("that means"); (2) to convey second-hand information ("they say", "I heard that").',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'forma ordinaria', label_ca: 'forma ordinària', label_en: 'plain form' },
      { text: 'ということだ', role: 'key', isSlot: false },
    ],
    example: [
      { text: '試験に', furigana: 'しけんに', role: 'location', gloss_es: 'en el examen', gloss_ca: "a l'examen", gloss_en: 'in the exam' },
      { text: '合格した', furigana: 'ごうかくした', role: 'verb', gloss_es: 'aprobó', gloss_ca: 'va aprovar', gloss_en: 'passed' },
      { text: 'ということは、', role: 'key', gloss_es: 'lo que significa es que', gloss_ca: 'el que significa és que', gloss_en: 'which means' },
      { text: '努力した', furigana: 'どりょくした', role: 'verb', gloss_es: 'se esforzó', gloss_ca: 'es va esforçar', gloss_en: 'worked hard' },
      { text: 'ということだ。', role: 'key', gloss_es: 'eso significa', gloss_ca: 'això significa', gloss_en: 'that means' },
    ],
    tip_es: 'En lenguaje coloquial, ということ se contrae a って. Compara con らしい y そうだ para información indirecta.',
    tip_ca: "En llengua col·loquial, ということ es contrau a って. Compara amb らしい i そうだ per a informació indirecta.",
    tip_en: 'In casual speech ということ contracts to って. Compare with らしい and そうだ for indirect information.',
  },
]

const ch2: GrammarPoint[] = [
  {
    id: 'mnnc1-2-1',
    lesson: 2,
    number: 3,
    jlpt: 'N3',
    pattern: '〜うちに',
    name_es: 'Mientras ~, antes de que cambie',
    name_ca: 'Mentre ~, abans que canviï',
    name_en: 'While ~, before it changes',
    explanation_es: 'Indica que hay que aprovechar una situación mientras dura, antes de que cambie. La primera cláusula describe una condición temporal.',
    explanation_ca: "Indica que cal aprofitar una situació mentre dura, abans que canviï. La primera clàusula descriu una condició temporal.",
    explanation_en: 'Indicates that something should be done while a situation lasts, before it changes. The first clause describes a temporary condition.',
    structure: [
      { text: 'V/い adj (普通形)', role: 'verb', isSlot: true, label_es: 'condición temporal', label_ca: 'condició temporal', label_en: 'temporary condition' },
      { text: 'うちに', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción recomendada', label_ca: 'acció recomanada', label_en: 'recommended action' },
    ],
    example: [
      { text: '熱い', furigana: 'あつい', role: 'adjective', gloss_es: 'caliente', gloss_ca: 'calent', gloss_en: 'hot' },
      { text: 'うちに', role: 'particle', gloss_es: 'mientras está', gloss_ca: 'mentre estigui', gloss_en: "while it's still" },
      { text: '食べて', furigana: 'たべて', role: 'verb', gloss_es: 'come', gloss_ca: 'menja', gloss_en: 'eat' },
      { text: 'ください。', role: 'key', gloss_es: 'por favor', gloss_ca: 'si us plau', gloss_en: 'please' },
    ],
    tip_es: 'Distinto de ～間に (durante un período fijo). うちに implica que la condición puede cambiar pronto.',
    tip_ca: 'Diferent de ～間に (durant un període fix). うちに implica que la condició pot canviar aviat.',
    tip_en: 'Different from ～間に (during a fixed period). うちに implies the condition may change soon.',
  },
  {
    id: 'mnnc1-2-2',
    lesson: 2,
    number: 4,
    jlpt: 'N3',
    pattern: '〜ことから',
    name_es: 'A partir del hecho de que ~, por ~',
    name_ca: "A partir del fet que ~, per ~",
    name_en: 'From the fact that ~, because ~',
    explanation_es: 'Expresa la base o razón para una conclusión o denominación. A menudo explica el origen de nombres o costumbres a partir de un hecho observable.',
    explanation_ca: "Expressa la base o raó per a una conclusió o denominació. Sovint explica l'origen de noms o costums a partir d'un fet observable.",
    explanation_en: 'Expresses the basis for a conclusion or naming. Often explains the origin of names or customs from an observable fact.',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'hecho observable', label_ca: 'fet observable', label_en: 'observable fact' },
      { text: 'ことから', role: 'key', isSlot: false },
      { text: '〜と呼ばれる', role: 'verb', isSlot: true, label_es: 'conclusión/denominación', label_ca: 'conclusió/denominació', label_en: 'conclusion/naming' },
    ],
    example: [
      { text: '花が', furigana: 'はなが', role: 'subject', gloss_es: 'flores', gloss_ca: 'flors', gloss_en: 'flowers' },
      { text: '多い', furigana: 'おおい', role: 'adjective', gloss_es: 'hay muchas', gloss_ca: "n'hi ha moltes", gloss_en: 'there are many' },
      { text: 'ことから、', role: 'key', gloss_es: 'a partir de este hecho,', gloss_ca: "a partir d'aquest fet,", gloss_en: 'from this fact,' },
      { text: '「花の都」と', furigana: 'はなのみやこ', role: 'noun', gloss_es: '«ciudad de las flores»', gloss_ca: '«ciutat de les flors»', gloss_en: '"City of Flowers"' },
      { text: '呼ばれています。', furigana: 'よばれています', role: 'verb', gloss_es: 'se llama', gloss_ca: 'es diu', gloss_en: 'is called' },
    ],
  },
]

const ch3: GrammarPoint[] = [
  {
    id: 'mnnc1-3-1',
    lesson: 3,
    number: 5,
    jlpt: 'N3',
    pattern: 'N に反して',
    name_es: 'Contrariamente a ~, en contra de ~',
    name_ca: 'Contràriament a ~, en contra de ~',
    name_en: 'Contrary to ~, against ~',
    explanation_es: 'Indica que algo ocurre de manera opuesta a lo esperado, deseado o establecido. Se usa con expectativas, reglas u órdenes.',
    explanation_ca: "Indica que alguna cosa ocorre de manera oposada al que s'esperava, desitjava o establia. S'usa amb expectatives, regles o ordres.",
    explanation_en: 'Indicates that something happens contrary to expectations, desires, or rules.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'expectativa/regla', label_ca: 'expectativa/regla', label_en: 'expectation/rule' },
      { text: 'に反して', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado contrario', label_ca: 'resultat contrari', label_en: 'contrary result' },
    ],
    example: [
      { text: '予想に', furigana: 'よそうに', role: 'noun', gloss_es: 'a las expectativas', gloss_ca: 'a les expectatives', gloss_en: 'contrary to expectations' },
      { text: '反して、', role: 'particle', gloss_es: 'en contra de,', gloss_ca: 'en contra de,', gloss_en: 'against,' },
      { text: '試験は', furigana: 'しけんは', role: 'topic', gloss_es: 'el examen', gloss_ca: "l'examen", gloss_en: 'the exam' },
      { text: '難しく', furigana: 'むずかしく', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'なかった。', role: 'verb', gloss_es: 'no fue', gloss_ca: 'no va ser', gloss_en: 'was not' },
    ],
    tip_es: 'Nouns típicos: 予想・期待・意思・規則・命令. La forma adjetival es に反した N.',
    tip_ca: 'Noms típics: 予想・期待・意思・規則・命令. La forma adjectival és に反した N.',
    tip_en: 'Typical nouns: 予想・期待・意思・規則・命令 (expectation, will, rule, order). Adjectival form: に反した N.',
  },
  {
    id: 'mnnc1-3-2',
    lesson: 3,
    number: 6,
    jlpt: 'N3',
    pattern: '〜わけではない',
    name_es: 'No es que ~, no necesariamente ~',
    name_ca: 'No és que ~, no necessàriament ~',
    name_en: "It's not that ~, not necessarily ~",
    explanation_es: 'Corrige o matiza una posible interpretación del oyente. Niega parcialmente una implicación sin negar el hecho completo.',
    explanation_ca: "Corregeix o matisa una possible interpretació de l'oient. Nega parcialment una implicació sense negar el fet complet.",
    explanation_en: "Corrects or nuances a possible interpretation. Partially denies an implication without negating the whole fact.",
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'implicación a negar', label_ca: 'implicació a negar', label_en: 'implication to deny' },
      { text: 'わけではない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '嫌いな', furigana: 'きらいな', role: 'adjective', gloss_es: 'que me disguste', gloss_ca: 'que em disgusti', gloss_en: 'that I dislike it' },
      { text: 'わけでは', role: 'key', gloss_es: 'no es que', gloss_ca: 'no és que', gloss_en: "it's not that" },
      { text: 'ない', role: 'key', gloss_es: '(negación)', gloss_ca: '(negació)', gloss_en: '(negation)' },
      { text: 'が、', role: 'conjunction', gloss_es: 'pero', gloss_ca: 'però', gloss_en: 'but' },
      { text: '今は食べたくない。', furigana: 'いまはたべたくない', role: 'verb', gloss_es: 'ahora no quiero comerlo', gloss_ca: 'ara no el vull menjar', gloss_en: "I just don't want to eat it now" },
    ],
    tip_es: 'Compara: わけがない (imposibilidad total), わけにはいかない (no puede hacerse). わけではない solo niega parcialmente.',
    tip_ca: "Compara: わけがない (impossibilitat total), わけにはいかない (no pot fer-se). わけではない només nega parcialment.",
    tip_en: 'Compare: わけがない (total impossibility), わけにはいかない (cannot be done). わけではない only partially denies.',
  },
]

const ch4: GrammarPoint[] = [
  {
    id: 'mnnc1-4-1',
    lesson: 4,
    number: 7,
    jlpt: 'N3',
    pattern: 'N に比べて',
    name_es: 'Comparado con ~, en comparación con ~',
    name_ca: 'Comparat amb ~, en comparació amb ~',
    name_en: 'Compared to ~, in comparison with ~',
    explanation_es: 'Establece una comparación entre dos elementos. La forma に比べ (sin て) es más formal y se usa en escritura.',
    explanation_ca: 'Estableix una comparació entre dos elements. La forma に比べ (sense て) és més formal i es usa en escriptura.',
    explanation_en: 'Establishes a comparison between two elements. The form に比べ (without て) is more formal and used in writing.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'base de comparación', label_ca: 'base de comparació', label_en: 'comparison base' },
      { text: 'に比べて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado', label_ca: 'resultat', label_en: 'result' },
    ],
    example: [
      { text: '去年に', furigana: 'きょねんに', role: 'time', gloss_es: 'al año pasado', gloss_ca: "a l'any passat", gloss_en: 'to last year' },
      { text: '比べて、', furigana: 'くらべて', role: 'particle', gloss_es: 'comparado con,', gloss_ca: 'comparat amb,', gloss_en: 'compared to,' },
      { text: '今年は', furigana: 'ことしは', role: 'topic', gloss_es: 'este año', gloss_ca: 'aquest any', gloss_en: 'this year' },
      { text: '暖かい。', furigana: 'あたたかい', role: 'adjective', gloss_es: 'es más cálido', gloss_ca: 'és més càlid', gloss_en: 'is warmer' },
    ],
    tip_es: 'También se puede decir ～と比べて. Con adjetivos suele acompañarse de ～より o ～のほうが.',
    tip_ca: 'També es pot dir ～と比べて. Amb adjectius sol acompanyar-se de ～より o ～のほうが.',
    tip_en: 'Can also use ～と比べて. With adjectives often paired with ～より or ～のほうが.',
  },
  {
    id: 'mnnc1-4-2',
    lesson: 4,
    number: 8,
    jlpt: 'N3',
    pattern: '〜一方で',
    name_es: 'Por otro lado ~, mientras que ~',
    name_ca: "D'altra banda ~, mentre que ~",
    name_en: 'On the other hand ~, while ~',
    explanation_es: 'Contrasta dos aspectos de un mismo tema. Puede indicar contraste ("por un lado... por otro") o acciones que ocurren en paralelo.',
    explanation_ca: "Contrasta dos aspectes d'un mateix tema. Pot indicar contrast o accions que ocorren en paral·lel.",
    explanation_en: 'Contrasts two aspects of the same topic. Can indicate contrast or parallel actions.',
    structure: [
      { text: 'V/N/adj (普通形)', role: 'verb', isSlot: true, label_es: 'aspecto 1', label_ca: 'aspecte 1', label_en: 'aspect 1' },
      { text: '一方で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'aspecto 2 (contraste)', label_ca: 'aspecte 2 (contrast)', label_en: 'aspect 2 (contrast)' },
    ],
    example: [
      { text: 'この薬は', furigana: 'このくすりは', role: 'topic', gloss_es: 'este medicamento', gloss_ca: 'aquest medicament', gloss_en: 'this medicine' },
      { text: '効果がある', furigana: 'こうかがある', role: 'verb', gloss_es: 'es eficaz', gloss_ca: 'és eficaç', gloss_en: 'is effective' },
      { text: '一方で、', role: 'key', gloss_es: 'por otro lado,', gloss_ca: "d'altra banda,", gloss_en: 'on the other hand,' },
      { text: '副作用も', furigana: 'ふくさようも', role: 'subject', gloss_es: 'también efectos secundarios', gloss_ca: 'també efectes secundaris', gloss_en: 'also side effects' },
      { text: 'ある。', role: 'verb', gloss_es: 'hay', gloss_ca: "n'hi ha", gloss_en: 'there are' },
    ],
    tip_es: 'Similar a が y けれども pero más formal. Con verbos puede indicar paralelismo ("mientras hace A, también hace B").',
    tip_ca: 'Similar a が i けれども però més formal. Amb verbs pot indicar paral·lelisme ("mentre fa A, també fa B").',
    tip_en: 'Similar to が and けれども but more formal. With verbs can indicate parallel actions.',
  },
]

const ch5: GrammarPoint[] = [
  {
    id: 'mnnc1-5-1',
    lesson: 5,
    number: 9,
    jlpt: 'N3',
    pattern: 'V/N に伴って',
    name_es: 'A medida que ~, junto con ~',
    name_ca: 'A mesura que ~, juntament amb ~',
    name_en: 'Along with ~, as ~ changes',
    explanation_es: 'Indica que un cambio ocurre en paralelo con otro. Ambos cambios suelen ir en la misma dirección. Registro formal/escrito.',
    explanation_ca: 'Indica que un canvi ocorre en paral·lel amb un altre. Tots dos canvis solen anar en la mateixa direcció. Registre formal/escrit.',
    explanation_en: 'Indicates that a change occurs in parallel with another. Both changes usually go in the same direction. Formal/written register.',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'cambio principal', label_ca: 'canvi principal', label_en: 'main change' },
      { text: 'に伴って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'cambio paralelo', label_ca: 'canvi paral·lel', label_en: 'parallel change' },
    ],
    example: [
      { text: '経済の', furigana: 'けいざいの', role: 'noun', gloss_es: 'de la economía', gloss_ca: "de l'economia", gloss_en: 'of the economy' },
      { text: '発展に', furigana: 'はってんに', role: 'noun', gloss_es: 'al desarrollo', gloss_ca: 'al desenvolupament', gloss_en: 'with the development' },
      { text: '伴って、', furigana: 'ともなって', role: 'particle', gloss_es: 'junto con,', gloss_ca: 'juntament amb,', gloss_en: 'along with,' },
      { text: '環境問題が', furigana: 'かんきょうもんだいが', role: 'subject', gloss_es: 'los problemas ambientales', gloss_ca: 'els problemes ambientals', gloss_en: 'environmental problems' },
      { text: '増えた。', furigana: 'ふえた', role: 'verb', gloss_es: 'aumentaron', gloss_ca: 'van augmentar', gloss_en: 'increased' },
    ],
    tip_es: 'Similar a ～につれて, pero に伴って es más formal y enfatiza que los cambios son concomitantes.',
    tip_ca: 'Similar a ～につれて, però に伴って és més formal i emfatitza que els canvis són concomitants.',
    tip_en: 'Similar to ～につれて but に伴って is more formal and emphasizes concomitant changes.',
  },
  {
    id: 'mnnc1-5-2',
    lesson: 5,
    number: 10,
    jlpt: 'N3',
    pattern: 'V辞書形/N に従って',
    name_es: 'Siguiendo ~, conforme a ~, a medida que ~',
    name_ca: "Seguint ~, d'acord amb ~, a mesura que ~",
    name_en: 'Following ~, in accordance with ~, as ~',
    explanation_es: 'Dos usos: (1) seguir instrucciones, reglas u órdenes; (2) indicar cambio gradual ("a medida que avanza el tiempo...").',
    explanation_ca: "Dos usos: (1) seguir instruccions, regles o ordres; (2) indicar canvi gradual (\"a mesura que avança el temps...\").",
    explanation_en: 'Two uses: (1) following instructions/rules/orders; (2) indicating gradual change ("as time passes...").',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'instrucción/cambio', label_ca: 'instrucció/canvi', label_en: 'instruction/change' },
      { text: 'に従って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción/resultado', label_ca: 'acció/resultat', label_en: 'action/result' },
    ],
    example: [
      { text: '先生の', furigana: 'せんせいの', role: 'noun', gloss_es: 'del profesor', gloss_ca: 'del professor', gloss_en: "of the teacher" },
      { text: '指示に', furigana: 'しじに', role: 'noun', gloss_es: 'las instrucciones', gloss_ca: 'les instruccions', gloss_en: 'the instructions' },
      { text: '従って、', furigana: 'したがって', role: 'particle', gloss_es: 'siguiendo,', gloss_ca: 'seguint,', gloss_en: 'following,' },
      { text: '問題を', furigana: 'もんだいを', role: 'object', gloss_es: 'el problema', gloss_ca: 'el problema', gloss_en: 'the problem' },
      { text: '解いた。', furigana: 'といた', role: 'verb', gloss_es: 'resolvió', gloss_ca: 'va resoldre', gloss_en: 'solved' },
    ],
    tip_es: 'Para el cambio gradual usa siempre la forma diccionario (年をとるに従って "a medida que envejeció").',
    tip_ca: 'Per al canvi gradual usa sempre la forma diccionari (年をとるに従って "a mesura que envellí").',
    tip_en: 'For gradual change always use dictionary form (年をとるに従って "as he aged").',
  },
]

const ch6: GrammarPoint[] = [
  {
    id: 'mnnc1-6-1',
    lesson: 6,
    number: 11,
    jlpt: 'N3',
    pattern: '〜はずがない',
    name_es: 'Es imposible que ~, no puede ser que ~',
    name_ca: 'És impossible que ~, no pot ser que ~',
    name_en: "There's no way that ~, it can't be that ~",
    explanation_es: 'Expresa que algo es imposible según el razonamiento o el conocimiento del hablante. Indica una negación lógica fuerte.',
    explanation_ca: "Expressa que alguna cosa és impossible segons el raonament o el coneixement del parlant. Indica una negació lògica forta.",
    explanation_en: "Expresses that something is impossible according to the speaker's reasoning or knowledge. A strong logical negation.",
    structure: [
      { text: 'V普通形/adj/N', role: 'verb', isSlot: true, label_es: 'hecho negado', label_ca: 'fet negat', label_en: 'negated fact' },
      { text: 'はずがない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '彼が', furigana: 'かれが', role: 'subject', gloss_es: 'él', gloss_ca: 'ell', gloss_en: 'he' },
      { text: 'そんなことを', role: 'object', gloss_es: 'algo así', gloss_ca: 'una cosa així', gloss_en: 'something like that' },
      { text: '言う', furigana: 'いう', role: 'verb', gloss_es: 'decir', gloss_ca: 'dir', gloss_en: 'say' },
      { text: 'はずがない。', role: 'key', gloss_es: 'es imposible que diga', gloss_ca: 'és impossible que digui', gloss_en: "there's no way he'd say" },
    ],
    tip_es: 'Compara: はずだ (debería ser), はずがない (es imposible). No confundir con わけがない (mismo significado pero más coloquial).',
    tip_ca: 'Compara: はずだ (hauria de ser), はずがない (és impossible). No confondre amb わけがない (mateix significat però més col·loquial).',
    tip_en: 'Compare: はずだ (should be), はずがない (impossible). わけがない has the same meaning but is more colloquial.',
  },
  {
    id: 'mnnc1-6-2',
    lesson: 6,
    number: 12,
    jlpt: 'N3',
    pattern: 'N 次第で/次第だ',
    name_es: 'Depende de ~, según ~',
    name_ca: 'Depèn de ~, segons ~',
    name_en: 'Depending on ~, it depends on ~',
    explanation_es: 'Indica que el resultado o la situación varía según algo. 次第だ es la forma predicativa ("todo depende de").',
    explanation_ca: "Indica que el resultat o la situació varia segons alguna cosa. 次第だ és la forma predicativa (\"tot depèn de\").",
    explanation_en: 'Indicates that the result or situation varies depending on something. 次第だ is the predicative form ("it all depends on").',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'factor determinante', label_ca: 'factor determinant', label_en: 'determining factor' },
      { text: '次第で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado variable', label_ca: 'resultat variable', label_en: 'variable result' },
    ],
    example: [
      { text: '結果は', furigana: 'けっかは', role: 'topic', gloss_es: 'el resultado', gloss_ca: 'el resultat', gloss_en: 'the result' },
      { text: 'あなたの', role: 'noun', gloss_es: 'de tu', gloss_ca: 'del teu', gloss_en: 'your' },
      { text: '努力次第だ。', furigana: 'どりょくしだいだ', role: 'key', gloss_es: 'depende del esfuerzo', gloss_ca: "depèn de l'esforç", gloss_en: 'depends on your effort' },
    ],
    tip_es: 'Diferente uso: V ます形+次第 significa "en cuanto haga ~" (nada más terminar). Aquí es N+次第で/次第だ (depender de).',
    tip_ca: 'Ús diferent: V ます形+次第 significa "en cuanto faci ~" (tot just acabar). Aquí és N+次第で/次第だ (dependre de).',
    tip_en: 'Different use: V ます stem + 次第 means "as soon as ~ is done". Here it is N + 次第で/次第だ (to depend on).',
  },
]

const ch7: GrammarPoint[] = [
  {
    id: 'mnnc1-7-1',
    lesson: 7,
    number: 13,
    jlpt: 'N3',
    pattern: 'N 向けに/向けの',
    name_es: 'Dirigido a ~, destinado a ~',
    name_ca: 'Adreçat a ~, destinat a ~',
    name_en: 'Aimed at ~, intended for ~',
    explanation_es: 'Indica que algo está diseñado o destinado para un público o propósito específico. 向けに modifica verbos; 向けの modifica sustantivos.',
    explanation_ca: "Indica que alguna cosa està dissenyada o destinada per a un públic o propòsit específic. 向けに modifica verbs; 向けの modifica substantius.",
    explanation_en: 'Indicates that something is designed or intended for a specific audience or purpose. 向けに modifies verbs; 向けの modifies nouns.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'destinatario', label_ca: 'destinatari', label_en: 'target audience' },
      { text: '向けに/向けの', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'producto/contenido', label_ca: 'producte/contingut', label_en: 'product/content' },
    ],
    example: [
      { text: 'これは', role: 'topic', gloss_es: 'esto', gloss_ca: 'això', gloss_en: 'this' },
      { text: '初心者', furigana: 'しょしんしゃ', role: 'noun', gloss_es: 'para principiantes', gloss_ca: 'per a principiants', gloss_en: 'for beginners' },
      { text: '向けの', role: 'particle', gloss_es: 'dirigido a', gloss_ca: 'adreçat a', gloss_en: 'aimed at' },
      { text: 'テキストです。', role: 'copula', gloss_es: 'es un libro de texto', gloss_ca: 'és un llibre de text', gloss_en: 'is a textbook' },
    ],
  },
  {
    id: 'mnnc1-7-2',
    lesson: 7,
    number: 14,
    jlpt: 'N3',
    pattern: '〜ものだ',
    name_es: 'Así son las cosas ~, se supone que ~',
    name_ca: 'Així són les coses ~, se suposa que ~',
    name_en: "That's just how things are ~, one is supposed to ~",
    explanation_es: 'Varios usos: (1) verdad general o expectativa social ("así debe ser"); (2) recuerdo nostálgico ("solía ~"); (3) admiración o sorpresa.',
    explanation_ca: "Diversos usos: (1) veritat general o expectativa social (\"així ha de ser\"); (2) record nostàlgic (\"solia ~\"); (3) admiració o sorpresa.",
    explanation_en: 'Several uses: (1) general truth or social expectation ("that\'s how it should be"); (2) nostalgic memory ("used to ~"); (3) admiration or surprise.',
    structure: [
      { text: 'V/adj (普通形)', role: 'verb', isSlot: true, label_es: 'norma/hábito/hecho', label_ca: 'norma/hàbit/fet', label_en: 'norm/habit/fact' },
      { text: 'ものだ', role: 'key', isSlot: false },
    ],
    example: [
      { text: '人に', furigana: 'ひとに', role: 'location', gloss_es: 'a las personas', gloss_ca: 'a les persones', gloss_en: 'to people' },
      { text: '会ったら', furigana: 'あったら', role: 'verb', gloss_es: 'cuando te encuentras', gloss_ca: 'quan et trobes', gloss_en: 'when you meet' },
      { text: 'あいさつする', role: 'verb', gloss_es: 'saludar', gloss_ca: 'saludar', gloss_en: 'greet' },
      { text: 'ものだ。', role: 'key', gloss_es: 'así debe hacerse', gloss_ca: "així s'ha de fer", gloss_en: "that's what you do" },
    ],
    tip_es: 'Para el uso nostálgico: 子どものころ、よく遊んだものだ "De niño, solía jugar mucho". Con ～たものだ.',
    tip_ca: 'Per a l\'ús nostàlgic: 子どものころ、よく遊んだものだ "De petit, solia jugar molt". Amb ～たものだ.',
    tip_en: 'For the nostalgic use: 子どものころ、よく遊んだものだ "As a child, I used to play a lot." Uses ～たものだ.',
  },
]

const ch8: GrammarPoint[] = [
  {
    id: 'mnnc1-8-1',
    lesson: 8,
    number: 15,
    jlpt: 'N3',
    pattern: '〜ものの',
    name_es: 'Aunque ~, si bien ~',
    name_ca: 'Tot i que ~, si bé ~',
    name_en: 'Although ~, even though ~',
    explanation_es: 'Conecta dos cláusulas donde la segunda contrasta o decepciona respecto a la primera. Similar a けれども pero más formal y con connotación de resultado inesperado o insatisfactorio.',
    explanation_ca: "Connecta dues clàusules on la segona contrasta o decepciona respecte a la primera. Similar a けれども però més formal i amb connotació de resultat inesperat o insatisfactori.",
    explanation_en: 'Connects two clauses where the second contrasts with or disappoints the first. More formal than けれども, with a nuance of unexpected or unsatisfactory result.',
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'premisa (aunque...)', label_ca: 'premissa (tot i que...)', label_en: 'premise (although...)' },
      { text: 'ものの', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado decepcionante', label_ca: 'resultat decebedor', label_en: 'disappointing result' },
    ],
    example: [
      { text: '日本語を', furigana: 'にほんごを', role: 'object', gloss_es: 'japonés', gloss_ca: 'japonès', gloss_en: 'Japanese' },
      { text: '勉強した', furigana: 'べんきょうした', role: 'verb', gloss_es: 'estudié', gloss_ca: 'vaig estudiar', gloss_en: 'studied' },
      { text: 'ものの、', role: 'key', gloss_es: 'aunque,', gloss_ca: 'tot i que,', gloss_en: 'although,' },
      { text: 'まだ', role: 'auxiliary', gloss_es: 'todavía', gloss_ca: 'encara', gloss_en: 'still' },
      { text: '話せない。', furigana: 'はなせない', role: 'verb', gloss_es: 'no puedo hablar', gloss_ca: 'no puc parlar', gloss_en: "can't speak it" },
    ],
    tip_es: 'El sujeto de ambas cláusulas suele ser el mismo. Se usa en textos formales; en coloquial se prefiere けれど.',
    tip_ca: 'El subjecte de les dues clàusules sol ser el mateix. S\'usa en textos formals; en col·loquial es prefereix けれど.',
    tip_en: 'The subject of both clauses is usually the same. Used in formal texts; colloquially けれど is preferred.',
  },
  {
    id: 'mnnc1-8-2',
    lesson: 8,
    number: 16,
    jlpt: 'N3',
    pattern: 'N に加えて',
    name_es: 'Además de ~, encima de ~',
    name_ca: 'A més de ~, a sobre de ~',
    name_en: 'In addition to ~, on top of ~',
    explanation_es: 'Indica que se suma algo a algo ya existente. La segunda cláusula añade información adicional, a menudo intensificando o agravando la situación.',
    explanation_ca: "Indica que s'afegeix alguna cosa a alguna cosa ja existent. La segona clàusula afegeix informació addicional, sovint intensificant o agreujant la situació.",
    explanation_en: 'Indicates that something is added to something already existing. The second clause adds further information, often intensifying or worsening the situation.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'elemento base', label_ca: 'element base', label_en: 'base element' },
      { text: 'に加えて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'elemento añadido', label_ca: 'element afegit', label_en: 'added element' },
    ],
    example: [
      { text: '雨に', furigana: 'あめに', role: 'noun', gloss_es: 'además de la lluvia', gloss_ca: 'a més de la pluja', gloss_en: 'in addition to the rain' },
      { text: '加えて、', furigana: 'くわえて', role: 'particle', gloss_es: 'encima,', gloss_ca: 'a sobre,', gloss_en: 'on top of that,' },
      { text: '風も', furigana: 'かぜも', role: 'subject', gloss_es: 'también el viento', gloss_ca: 'també el vent', gloss_en: 'also the wind' },
      { text: '強くなった。', furigana: 'つよくなった', role: 'verb', gloss_es: 'se hizo más fuerte', gloss_ca: 'es va fer més fort', gloss_en: 'became stronger' },
    ],
    tip_es: 'Similar a ～のみならず pero に加えて es más neutro y cotidiano. ～のみならず tiene un tono más enfático y formal.',
    tip_ca: 'Similar a ～のみならず però に加えて és més neutre i quotidià. ～のみならず té un to més emfàtic i formal.',
    tip_en: 'Similar to ～のみならず but に加えて is more neutral and everyday. ～のみならず is more emphatic and formal.',
  },
]

const ch9: GrammarPoint[] = [
  {
    id: 'mnnc1-9-1',
    lesson: 9,
    number: 17,
    jlpt: 'N3',
    pattern: '〜のみならず',
    name_es: 'No solo ~, sino también ~',
    name_ca: 'No només ~, sinó també ~',
    name_en: 'Not only ~, but also ~',
    explanation_es: 'Versión formal de だけでなく. Expresa que algo se extiende más allá de lo mencionado. Frecuente en escritura académica y noticias.',
    explanation_ca: 'Versió formal de だけでなく. Expressa que alguna cosa s\'estén més enllà del que s\'esmenta. Freqüent en escriptura acadèmica i notícies.',
    explanation_en: 'Formal version of だけでなく. Expresses that something extends beyond what is mentioned. Common in academic writing and news.',
    structure: [
      { text: 'N/V普通形/adj', role: 'noun', isSlot: true, label_es: 'elemento A', label_ca: 'element A', label_en: 'element A' },
      { text: 'のみならず', role: 'key', isSlot: false },
      { text: '〜も', role: 'key', isSlot: true, label_es: 'elemento B (también)', label_ca: 'element B (també)', label_en: 'element B (also)' },
    ],
    example: [
      { text: '日本のみならず、', furigana: 'にほんのみならず', role: 'noun', gloss_es: 'no solo en Japón sino también', gloss_ca: 'no només al Japó sinó també', gloss_en: 'not only in Japan but also' },
      { text: '世界中で', furigana: 'せかいじゅうで', role: 'location', gloss_es: 'en todo el mundo', gloss_ca: 'arreu del món', gloss_en: 'all over the world' },
      { text: '人気がある。', furigana: 'にんきがある', role: 'verb', gloss_es: 'es popular', gloss_ca: 'és popular', gloss_en: 'is popular' },
    ],
    tip_es: 'のみ = だけ (solo) en registro formal. Para el lenguaje cotidiano usa ～だけでなく o ～ばかりでなく.',
    tip_ca: 'のみ = だけ (només) en registre formal. Per al llenguatge quotidià usa ～だけでなく o ～ばかりでなく.',
    tip_en: 'のみ = だけ (only) in formal register. For everyday language use ～だけでなく or ～ばかりでなく.',
  },
  {
    id: 'mnnc1-9-2',
    lesson: 9,
    number: 18,
    jlpt: 'N3',
    pattern: '〜にもかかわらず',
    name_es: 'A pesar de ~, pese a ~',
    name_ca: 'Malgrat ~, tot i ~',
    name_en: 'Despite ~, in spite of ~',
    explanation_es: 'Indica que algo ocurre en contra de lo que cabría esperarse dada la situación. Más fuerte y formal que のに.',
    explanation_ca: "Indica que alguna cosa ocorre en contra del que s'esperaria donada la situació. Més fort i formal que のに.",
    explanation_en: "Indicates something happens contrary to what would be expected. Stronger and more formal than のに.",
    structure: [
      { text: 'V/adj/N (普通形)', role: 'verb', isSlot: true, label_es: 'obstáculo/circunstancia', label_ca: 'obstacle/circumstància', label_en: 'obstacle/circumstance' },
      { text: 'にもかかわらず', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado inesperado', label_ca: 'resultat inesperat', label_en: 'unexpected result' },
    ],
    example: [
      { text: '雨にも', furigana: 'あめにも', role: 'noun', gloss_es: 'a pesar de la lluvia', gloss_ca: 'malgrat la pluja', gloss_en: 'despite the rain' },
      { text: 'かかわらず、', role: 'key', gloss_es: 'pese a todo,', gloss_ca: 'malgrat tot,', gloss_en: 'in spite of,' },
      { text: '試合は', furigana: 'しあいは', role: 'topic', gloss_es: 'el partido', gloss_ca: 'el partit', gloss_en: 'the match' },
      { text: '行われた。', furigana: 'おこなわれた', role: 'verb', gloss_es: 'se celebró', gloss_ca: 'es va celebrar', gloss_en: 'was held' },
    ],
    tip_es: 'Compara con のに (frustración personal) y ながら (aunque). にもかかわらず es objetivo y formal.',
    tip_ca: "Compara amb のに (frustració personal) i ながら (tot i que). にもかかわらず és objectiu i formal.",
    tip_en: 'Compare with のに (personal frustration) and ながら (although). にもかかわらず is objective and formal.',
  },
]

const ch10: GrammarPoint[] = [
  {
    id: 'mnnc1-10-1',
    lesson: 10,
    number: 19,
    jlpt: 'N3',
    pattern: '〜ことなく',
    name_es: 'Sin ~, sin llegar a ~',
    name_ca: 'Sense ~, sense arribar a ~',
    name_en: 'Without doing ~, without ever ~',
    explanation_es: 'Indica que la acción principal ocurre sin realizar la acción mencionada. Equivale a ～ないで en registro formal/escrito.',
    explanation_ca: "Indica que l'acció principal ocorre sense realitzar l'acció esmentada. Equivalent a ～ないで en registre formal/escrit.",
    explanation_en: 'Indicates the main action occurs without performing the mentioned action. Equivalent to ～ないで in formal/written register.',
    structure: [
      { text: 'V辞書形', role: 'verb', isSlot: true, label_es: 'acción omitida', label_ca: 'acció omesa', label_en: 'omitted action' },
      { text: 'ことなく', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción principal', label_ca: 'acció principal', label_en: 'main action' },
    ],
    example: [
      { text: '休む', furigana: 'やすむ', role: 'verb', gloss_es: 'descansar', gloss_ca: 'descansar', gloss_en: 'resting' },
      { text: 'ことなく、', role: 'key', gloss_es: 'sin,', gloss_ca: 'sense,', gloss_en: 'without,' },
      { text: '三日間', furigana: 'みっかかん', role: 'time', gloss_es: 'durante tres días', gloss_ca: 'durant tres dies', gloss_en: 'for three days' },
      { text: '働き続けた。', furigana: 'はたらきつづけた', role: 'verb', gloss_es: 'siguió trabajando', gloss_ca: 'va seguir treballant', gloss_en: 'kept working' },
    ],
    tip_es: 'Solo se usa con verbos voluntarios. ～ことなく suena más literario que ～ないで; evita usarlo en conversación normal.',
    tip_ca: 'Només es fa servir amb verbs voluntaris. ～ことなく sona més literari que ～ないで; evita usar-lo en conversa normal.',
    tip_en: 'Only used with volitional verbs. ～ことなく sounds more literary than ～ないで; avoid in normal conversation.',
  },
  {
    id: 'mnnc1-10-2',
    lesson: 10,
    number: 20,
    jlpt: 'N3',
    pattern: '〜ほど〜ない / 〜ほど',
    name_es: 'No tan ~ como ~, tan ~ que ~',
    name_ca: 'No tan ~ com ~, tan ~ que ~',
    name_en: 'Not as ~ as ~, so ~ that ~',
    explanation_es: 'Dos usos: (1) comparación negativa (A は B ほど～ない = A no es tan ~ como B); (2) grado o cantidad extrema (〜ほど～ = tan/tanto que...).',
    explanation_ca: "Dos usos: (1) comparació negativa (A は B ほど～ない = A no és tan ~ com B); (2) grau o quantitat extrema (〜ほど～ = tan/tant que...).",
    explanation_en: 'Two uses: (1) negative comparison (A は B ほど～ない = A is not as ~ as B); (2) extreme degree (〜ほど～ = so ~ that...).',
    structure: [
      { text: 'N/V', role: 'noun', isSlot: true, label_es: 'estándar/grado', label_ca: 'estàndard/grau', label_en: 'standard/degree' },
      { text: 'ほど', role: 'particle', isSlot: false },
      { text: '〜ない / 〜', role: 'key', isSlot: true, label_es: 'comparación/resultado', label_ca: 'comparació/resultat', label_en: 'comparison/result' },
    ],
    example: [
      { text: '笑いが', furigana: 'わらいが', role: 'subject', gloss_es: 'la risa', gloss_ca: 'el riure', gloss_en: 'laughter' },
      { text: 'とまらない', furigana: 'とまらない', role: 'verb', gloss_es: 'no para', gloss_ca: 'no para', gloss_en: "doesn't stop" },
      { text: 'ほど', role: 'particle', gloss_es: 'tanto que', gloss_ca: 'tant que', gloss_en: 'so much that' },
      { text: '面白かった。', furigana: 'おもしろかった', role: 'adjective', gloss_es: 'fue divertido', gloss_ca: 'va ser divertit', gloss_en: 'it was funny' },
    ],
    tip_es: 'Uso 1 (comparación): この映画はあの映画ほど面白くない。Uso 2 (grado): 死ぬほど疲れた "Estoy muerto de cansancio".',
    tip_ca: "Ús 1 (comparació): この映画はあの映画ほど面白くない. Ús 2 (grau): 死ぬほど疲れた \"Estic mort de cansament\".",
    tip_en: 'Use 1 (comparison): この映画はあの映画ほど面白くない. Use 2 (degree): 死ぬほど疲れた "I\'m dead tired".',
  },
]

export const MNN_C1_GRAMMAR_POINTS: GrammarPoint[] = [
  ...ch1, ...ch2, ...ch3, ...ch4, ...ch5,
  ...ch6, ...ch7, ...ch8, ...ch9, ...ch10,
]
