import type { GrammarPoint } from './grammar-mnn1'

// ─── Minna no Nihongo Chūkyū I ──────────────────────────────────────────────
// みんなの日本語 中級I · Lecciones 1-20 · JLPT N3

const ch1: GrammarPoint[] = [
  {
    id: 'mnnc1-1-1',
    lesson: 1,
    number: 1,
    jlpt: 'N3',
    pattern: 'N にとって',
    name_es: 'Para ~, desde el punto de vista de ~',
    name_ca: 'Per a ~, des del punt de vista de ~',
    name_en: 'For ~, from the perspective of ~',
    explanation_es: 'Indica el punto de vista de una persona o grupo respecto a algo. Expresa cómo algo parece, afecta o tiene valor para alguien específico.',
    explanation_ca: "Indica el punt de vista d'una persona o grup respecte a alguna cosa. Expressa com alguna cosa sembla, afecta o té valor per a algú específic.",
    explanation_en: 'Indicates the standpoint of a person or group regarding something. Expresses how something seems, affects, or has value for someone.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'persona/grupo', label_ca: 'persona/grup', label_en: 'person/group' },
      { text: 'にとって', role: 'particle', isSlot: false },
      { text: '述語', role: 'key', isSlot: true, label_es: 'predicado', label_ca: 'predicat', label_en: 'predicate' },
    ],
    example: [
      { text: '日本語は', furigana: 'にほんごは', role: 'topic', gloss_es: 'el japonés', gloss_ca: 'el japonès', gloss_en: 'Japanese' },
      { text: '私に', furigana: 'わたしに', role: 'noun', gloss_es: 'para mí', gloss_ca: 'per a mi', gloss_en: 'for me' },
      { text: 'とって', role: 'particle', gloss_es: '(perspectiva)', gloss_ca: '(perspectiva)', gloss_en: '(perspective)' },
      { text: '難しい', furigana: 'むずかしい', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'です。', role: 'copula', gloss_es: 'es', gloss_ca: 'és', gloss_en: 'is' },
    ],
    tip_es: 'No confundir con ～のために (propósito). にとって solo expresa perspectiva o evaluación subjetiva.',
    tip_ca: 'No confondre amb ～のために (propòsit). にとって només expressa perspectiva o avaluació subjectiva.',
    tip_en: "Don't confuse with ～のために (purpose). にとって only expresses perspective or subjective evaluation.",
  },
  {
    id: 'mnnc1-1-2',
    lesson: 1,
    number: 2,
    jlpt: 'N3',
    pattern: '〜ということだ',
    name_es: 'Lo que significa es ~, dicen que ~',
    name_ca: 'El que significa és ~, diuen que ~',
    name_en: 'That means ~, I heard that ~',
    explanation_es: 'Dos usos: (1) reformular o aclarar el significado de algo ("eso significa que"); (2) transmitir información de segunda mano ("dicen que", "he oído que").',
    explanation_ca: "Dos usos: (1) reformular o aclarir el significat d'alguna cosa (\"això significa\"); (2) transmetre informació de segona mà (\"diuen que\", \"he sentit que\").",
    explanation_en: 'Two uses: (1) to rephrase or clarify something ("that means"); (2) to convey second-hand information ("they say", "I heard that").',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'forma ordinaria', label_ca: 'forma ordinària', label_en: 'plain form' },
      { text: 'ということだ', role: 'key', isSlot: false },
    ],
    example: [
      { text: '試験に', furigana: 'しけんに', role: 'location', gloss_es: 'en el examen', gloss_ca: "a l'examen", gloss_en: 'in the exam' },
      { text: '合格した', furigana: 'ごうかくした', role: 'verb', gloss_es: 'aprobó', gloss_ca: 'va aprovar', gloss_en: 'passed' },
      { text: 'ということは、', role: 'key', gloss_es: 'lo que significa es que', gloss_ca: 'el que significa és que', gloss_en: 'which means' },
      { text: '努力した', furigana: 'どりょくした', role: 'verb', gloss_es: 'se esforzó', gloss_ca: 'es va esforçar', gloss_en: 'worked hard' },
      { text: 'ということだ。', role: 'key', gloss_es: 'eso significa', gloss_ca: 'això significa', gloss_en: 'that means' },
    ],
    tip_es: 'En lenguaje coloquial, ということ se contrae a って. Compara con らしい y そうだ para información indirecta.',
    tip_ca: "En llengua col·loquial, ということ es contrau a って. Compara amb らしい i そうだ per a informació indirecta.",
    tip_en: 'In casual speech ということ contracts to って. Compare with らしい and そうだ for indirect information.',
  },
]

const ch2: GrammarPoint[] = [
  {
    id: 'mnnc1-2-1',
    lesson: 2,
    number: 3,
    jlpt: 'N3',
    pattern: '〜うちに',
    name_es: 'Mientras ~, antes de que cambie',
    name_ca: 'Mentre ~, abans que canviï',
    name_en: 'While ~, before it changes',
    explanation_es: 'Indica que hay que aprovechar una situación mientras dura, antes de que cambie. La primera cláusula describe una condición temporal.',
    explanation_ca: "Indica que cal aprofitar una situació mentre dura, abans que canviï. La primera clàusula descriu una condició temporal.",
    explanation_en: 'Indicates that something should be done while a situation lasts, before it changes. The first clause describes a temporary condition.',
    structure: [
      { text: 'V/い adj (普通形)', role: 'verb', isSlot: true, label_es: 'condición temporal', label_ca: 'condició temporal', label_en: 'temporary condition' },
      { text: 'うちに', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción recomendada', label_ca: 'acció recomanada', label_en: 'recommended action' },
    ],
    example: [
      { text: '熱い', furigana: 'あつい', role: 'adjective', gloss_es: 'caliente', gloss_ca: 'calent', gloss_en: 'hot' },
      { text: 'うちに', role: 'particle', gloss_es: 'mientras está', gloss_ca: 'mentre estigui', gloss_en: "while it's still" },
      { text: '食べて', furigana: 'たべて', role: 'verb', gloss_es: 'come', gloss_ca: 'menja', gloss_en: 'eat' },
      { text: 'ください。', role: 'key', gloss_es: 'por favor', gloss_ca: 'si us plau', gloss_en: 'please' },
    ],
    tip_es: 'Distinto de ～間に (durante un período fijo). うちに implica que la condición puede cambiar pronto.',
    tip_ca: 'Diferent de ～間に (durant un període fix). うちに implica que la condició pot canviar aviat.',
    tip_en: 'Different from ～間に (during a fixed period). うちに implies the condition may change soon.',
  },
  {
    id: 'mnnc1-2-2',
    lesson: 2,
    number: 4,
    jlpt: 'N3',
    pattern: '〜ことから',
    name_es: 'A partir del hecho de que ~, por ~',
    name_ca: "A partir del fet que ~, per ~",
    name_en: 'From the fact that ~, because ~',
    explanation_es: 'Expresa la base o razón para una conclusión o denominación. A menudo explica el origen de nombres o costumbres a partir de un hecho observable.',
    explanation_ca: "Expressa la base o raó per a una conclusió o denominació. Sovint explica l'origen de noms o costums a partir d'un fet observable.",
    explanation_en: 'Expresses the basis for a conclusion or naming. Often explains the origin of names or customs from an observable fact.',
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'hecho observable', label_ca: 'fet observable', label_en: 'observable fact' },
      { text: 'ことから', role: 'key', isSlot: false },
      { text: '〜と呼ばれる', role: 'verb', isSlot: true, label_es: 'conclusión/denominación', label_ca: 'conclusió/denominació', label_en: 'conclusion/naming' },
    ],
    example: [
      { text: '花が', furigana: 'はなが', role: 'subject', gloss_es: 'flores', gloss_ca: 'flors', gloss_en: 'flowers' },
      { text: '多い', furigana: 'おおい', role: 'adjective', gloss_es: 'hay muchas', gloss_ca: "n'hi ha moltes", gloss_en: 'there are many' },
      { text: 'ことから、', role: 'key', gloss_es: 'a partir de este hecho,', gloss_ca: "a partir d'aquest fet,", gloss_en: 'from this fact,' },
      { text: '「花の都」と', furigana: 'はなのみやこ', role: 'noun', gloss_es: '«ciudad de las flores»', gloss_ca: '«ciutat de les flors»', gloss_en: '"City of Flowers"' },
      { text: '呼ばれています。', furigana: 'よばれています', role: 'verb', gloss_es: 'se llama', gloss_ca: 'es diu', gloss_en: 'is called' },
    ],
  },
]

const ch3: GrammarPoint[] = [
  {
    id: 'mnnc1-3-1',
    lesson: 3,
    number: 5,
    jlpt: 'N3',
    pattern: 'N に反して',
    name_es: 'Contrariamente a ~, en contra de ~',
    name_ca: 'Contràriament a ~, en contra de ~',
    name_en: 'Contrary to ~, against ~',
    explanation_es: 'Indica que algo ocurre de manera opuesta a lo esperado, deseado o establecido. Se usa con expectativas, reglas u órdenes.',
    explanation_ca: "Indica que alguna cosa ocorre de manera oposada al que s'esperava, desitjava o establia. S'usa amb expectatives, regles o ordres.",
    explanation_en: 'Indicates that something happens contrary to expectations, desires, or rules.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'expectativa/regla', label_ca: 'expectativa/regla', label_en: 'expectation/rule' },
      { text: 'に反して', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado contrario', label_ca: 'resultat contrari', label_en: 'contrary result' },
    ],
    example: [
      { text: '予想に', furigana: 'よそうに', role: 'noun', gloss_es: 'a las expectativas', gloss_ca: 'a les expectatives', gloss_en: 'contrary to expectations' },
      { text: '反して、', role: 'particle', gloss_es: 'en contra de,', gloss_ca: 'en contra de,', gloss_en: 'against,' },
      { text: '試験は', furigana: 'しけんは', role: 'topic', gloss_es: 'el examen', gloss_ca: "l'examen", gloss_en: 'the exam' },
      { text: '難しく', furigana: 'むずかしく', role: 'adjective', gloss_es: 'difícil', gloss_ca: 'difícil', gloss_en: 'difficult' },
      { text: 'なかった。', role: 'verb', gloss_es: 'no fue', gloss_ca: 'no va ser', gloss_en: 'was not' },
    ],
    tip_es: 'Nouns típicos: 予想・期待・意思・規則・命令. La forma adjetival es に反した N.',
    tip_ca: 'Noms típics: 予想・期待・意思・規則・命令. La forma adjectival és に反した N.',
    tip_en: 'Typical nouns: 予想・期待・意思・規則・命令 (expectation, will, rule, order). Adjectival form: に反した N.',
  },
  {
    id: 'mnnc1-3-2',
    lesson: 3,
    number: 6,
    jlpt: 'N3',
    pattern: '〜わけではない',
    name_es: 'No es que ~, no necesariamente ~',
    name_ca: 'No és que ~, no necessàriament ~',
    name_en: "It's not that ~, not necessarily ~",
    explanation_es: 'Corrige o matiza una posible interpretación del oyente. Niega parcialmente una implicación sin negar el hecho completo.',
    explanation_ca: "Corregeix o matisa una possible interpretació de l'oient. Nega parcialment una implicació sense negar el fet complet.",
    explanation_en: "Corrects or nuances a possible interpretation. Partially denies an implication without negating the whole fact.",
    structure: [
      { text: '普通形', role: 'verb', isSlot: true, label_es: 'implicación a negar', label_ca: 'implicació a negar', label_en: 'implication to deny' },
      { text: 'わけではない', role: 'key', isSlot: false },
    ],
    example: [
      { text: '嫌いな', furigana: 'きらいな', role: 'adjective', gloss_es: 'que me disguste', gloss_ca: 'que em disgusti', gloss_en: 'that I dislike it' },
      { text: 'わけでは', role: 'key', gloss_es: 'no es que', gloss_ca: 'no és que', gloss_en: "it's not that" },
      { text: 'ない', role: 'key', gloss_es: '(negación)', gloss_ca: '(negació)', gloss_en: '(negation)' },
      { text: 'が、', role: 'conjunction', gloss_es: 'pero', gloss_ca: 'però', gloss_en: 'but' },
      { text: '今は食べたくない。', furigana: 'いまはたべたくない', role: 'verb', gloss_es: 'ahora no quiero comerlo', gloss_ca: 'ara no el vull menjar', gloss_en: "I just don't want to eat it now" },
    ],
    tip_es: 'Compara: わけがない (imposibilidad total), わけにはいかない (no puede hacerse). わけではない solo niega parcialmente.',
    tip_ca: "Compara: わけがない (impossibilitat total), わけにはいかない (no pot fer-se). わけではない només nega parcialment.",
    tip_en: 'Compare: わけがない (total impossibility), わけにはいかない (cannot be done). わけではない only partially denies.',
  },
]

const ch4: GrammarPoint[] = [
  {
    id: 'mnnc1-4-1',
    lesson: 4,
    number: 7,
    jlpt: 'N3',
    pattern: 'N に比べて',
    name_es: 'Comparado con ~, en comparación con ~',
    name_ca: 'Comparat amb ~, en comparació amb ~',
    name_en: 'Compared to ~, in comparison with ~',
    explanation_es: 'Establece una comparación entre dos elementos. La forma に比べ (sin て) es más formal y se usa en escritura.',
    explanation_ca: 'Estableix una comparació entre dos elements. La forma に比べ (sense て) és més formal i es usa en escriptura.',
    explanation_en: 'Establishes a comparison between two elements. The form に比べ (without て) is more formal and used in writing.',
    structure: [
      { text: 'N', role: 'noun', isSlot: true, label_es: 'base de comparación', label_ca: 'base de comparació', label_en: 'comparison base' },
      { text: 'に比べて', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'resultado', label_ca: 'resultat', label_en: 'result' },
    ],
    example: [
      { text: '去年に', furigana: 'きょねんに', role: 'time', gloss_es: 'al año pasado', gloss_ca: "a l'any passat", gloss_en: 'to last year' },
      { text: '比べて、', furigana: 'くらべて', role: 'particle', gloss_es: 'comparado con,', gloss_ca: 'comparat amb,', gloss_en: 'compared to,' },
      { text: '今年は', furigana: 'ことしは', role: 'topic', gloss_es: 'este año', gloss_ca: 'aquest any', gloss_en: 'this year' },
      { text: '暖かい。', furigana: 'あたたかい', role: 'adjective', gloss_es: 'es más cálido', gloss_ca: 'és més càlid', gloss_en: 'is warmer' },
    ],
    tip_es: 'También se puede decir ～と比べて. Con adjetivos suele acompañarse de ～より o ～のほうが.',
    tip_ca: 'També es pot dir ～と比べて. Amb adjectius sol acompanyar-se de ～より o ～のほうが.',
    tip_en: 'Can also use ～と比べて. With adjectives often paired with ～より or ～のほうが.',
  },
  {
    id: 'mnnc1-4-2',
    lesson: 4,
    number: 8,
    jlpt: 'N3',
    pattern: '〜一方で',
    name_es: 'Por otro lado ~, mientras que ~',
    name_ca: "D'altra banda ~, mentre que ~",
    name_en: 'On the other hand ~, while ~',
    explanation_es: 'Contrasta dos aspectos de un mismo tema. Puede indicar contraste ("por un lado... por otro") o acciones que ocurren en paralelo.',
    explanation_ca: "Contrasta dos aspectes d'un mateix tema. Pot indicar contrast o accions que ocorren en paral·lel.",
    explanation_en: 'Contrasts two aspects of the same topic. Can indicate contrast or parallel actions.',
    structure: [
      { text: 'V/N/adj (普通形)', role: 'verb', isSlot: true, label_es: 'aspecto 1', label_ca: 'aspecte 1', label_en: 'aspect 1' },
      { text: '一方で', role: 'key', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'aspecto 2 (contraste)', label_ca: 'aspecte 2 (contrast)', label_en: 'aspect 2 (contrast)' },
    ],
    example: [
      { text: 'この薬は', furigana: 'このくすりは', role: 'topic', gloss_es: 'este medicamento', gloss_ca: 'aquest medicament', gloss_en: 'this medicine' },
      { text: '効果がある', furigana: 'こうかがある', role: 'verb', gloss_es: 'es eficaz', gloss_ca: 'és eficaç', gloss_en: 'is effective' },
      { text: '一方で、', role: 'key', gloss_es: 'por otro lado,', gloss_ca: "d'altra banda,", gloss_en: 'on the other hand,' },
      { text: '副作用も', furigana: 'ふくさようも', role: 'subject', gloss_es: 'también efectos secundarios', gloss_ca: 'també efectes secundaris', gloss_en: 'also side effects' },
      { text: 'ある。', role: 'verb', gloss_es: 'hay', gloss_ca: "n'hi ha", gloss_en: 'there are' },
    ],
    tip_es: 'Similar a が y けれども pero más formal. Con verbos puede indicar paralelismo ("mientras hace A, también hace B").',
    tip_ca: 'Similar a が i けれども però més formal. Amb verbs pot indicar paral·lelisme ("mentre fa A, també fa B").',
    tip_en: 'Similar to が and けれども but more formal. With verbs can indicate parallel actions.',
  },
]

const ch5: GrammarPoint[] = [
  {
    id: 'mnnc1-5-1',
    lesson: 5,
    number: 9,
    jlpt: 'N3',
    pattern: 'V/N に伴って',
    name_es: 'A medida que ~, junto con ~',
    name_ca: 'A mesura que ~, juntament amb ~',
    name_en: 'Along with ~, as ~ changes',
    explanation_es: 'Indica que un cambio ocurre en paralelo con otro. Ambos cambios suelen ir en la misma dirección. Registro formal/escrito.',
    explanation_ca: 'Indica que un canvi ocorre en paral·lel amb un altre. Tots dos canvis solen anar en la mateixa direcció. Registre formal/escrit.',
    explanation_en: 'Indicates that a change occurs in parallel with another. Both changes usually go in the same direction. Formal/written register.',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'cambio principal', label_ca: 'canvi principal', label_en: 'main change' },
      { text: 'に伴って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'cambio paralelo', label_ca: 'canvi paral·lel', label_en: 'parallel change' },
    ],
    example: [
      { text: '経済の', furigana: 'けいざいの', role: 'noun', gloss_es: 'de la economía', gloss_ca: "de l'economia", gloss_en: 'of the economy' },
      { text: '発展に', furigana: 'はってんに', role: 'noun', gloss_es: 'al desarrollo', gloss_ca: 'al desenvolupament', gloss_en: 'with the development' },
      { text: '伴って、', furigana: 'ともなって', role: 'particle', gloss_es: 'junto con,', gloss_ca: 'juntament amb,', gloss_en: 'along with,' },
      { text: '環境問題が', furigana: 'かんきょうもんだいが', role: 'subject', gloss_es: 'los problemas ambientales', gloss_ca: 'els problemes ambientals', gloss_en: 'environmental problems' },
      { text: '増えた。', furigana: 'ふえた', role: 'verb', gloss_es: 'aumentaron', gloss_ca: 'van augmentar', gloss_en: 'increased' },
    ],
    tip_es: 'Similar a ～につれて, pero に伴って es más formal y enfatiza que los cambios son concomitantes.',
    tip_ca: 'Similar a ～につれて, però に伴って és més formal i emfatitza que els canvis són concomitants.',
    tip_en: 'Similar to ～につれて but に伴って is more formal and emphasizes concomitant changes.',
  },
  {
    id: 'mnnc1-5-2',
    lesson: 5,
    number: 10,
    jlpt: 'N3',
    pattern: 'V辞書形/N に従って',
    name_es: 'Siguiendo ~, conforme a ~, a medida que ~',
    name_ca: "Seguint ~, d'acord amb ~, a mesura que ~",
    name_en: 'Following ~, in accordance with ~, as ~',
    explanation_es: 'Dos usos: (1) seguir instrucciones, reglas u órdenes; (2) indicar cambio gradual ("a medida que avanza el tiempo...").',
    explanation_ca: "Dos usos: (1) seguir instruccions, regles o ordres; (2) indicar canvi gradual (\"a mesura que avança el temps...\").",
    explanation_en: 'Two uses: (1) following instructions/rules/orders; (2) indicating gradual change ("as time passes...").',
    structure: [
      { text: 'V辞書形/N', role: 'verb', isSlot: true, label_es: 'instrucción/cambio', label_ca: 'instrucció/canvi', label_en: 'instruction/change' },
      { text: 'に従って', role: 'particle', isSlot: false },
      { text: '〜', role: 'key', isSlot: true, label_es: 'acción/resultado', label_ca: 'acció/resultat', label_en: 'action/result' },
    ],
    example: [
      { text: '先生の', furigana: 'せんせいの', role: 'noun', gloss_es: 'del profesor', gloss_ca: 'del professor', gloss_en: "of the teacher" },
      { text: '指示に', furigana: 'しじに', role: 'noun', gloss_es: 'las instrucciones', gloss_ca: 'les instruccions', gloss_en: 'the instructions' },
      { text: '従って、', furigana: 'したがって', role: 'particle', gloss_es: 'siguiendo,', gloss_ca: 'seguint,', gloss_en: 'following,' },
      { text: '問題を', furigana: 'もんだいを', role: 'object', gloss_es: 'el problema', gloss_ca: 'el problema', gloss_en: 'the problem' },
      { text: '解いた。', furigana: 'といた', role: 'verb', gloss_es: 'resolvió', gloss_ca: 'va resoldre', gloss_en: 'solved' },
    ],
    tip_es: 'Para el cambio gradual usa siempre la forma diccionario (年をとるに従って "a medida que envejeció").',
    tip_ca: 'Per al canvi gradual usa sempre la forma diccionari (年をとるに従って "a mesura que envellí").',
    tip_en: 'For gradual change always use dictionary form (年をとるに従って "as he aged").',
  },
]

export const MNN_C1_GRAMMAR_POINTS: GrammarPoint[] = [
  ...ch1, ...ch2, ...ch3, ...ch4, ...ch5,
]
