export interface BunproGrammarPoint {
  id: string
  jlpt: 'N5' | 'N4' | 'N3' | 'N2' | 'N1'
  pattern: string
  name_es: string
  name_en: string
  meaning_es: string
  meaning_en: string
  structure: string
  example_jp: string
  example_es: string
  notes?: string
}

export const BUNPRO_GRAMMAR: BunproGrammarPoint[] = [
  // ─────────────────────────────────────────────
  // N5
  // ─────────────────────────────────────────────
  {
    id: 'n5-01', jlpt: 'N5', pattern: 'は', name_es: 'Partícula de tema は', name_en: 'Topic marker は',
    meaning_es: 'Marca el tema de la oración. Indica de qué se está hablando.',
    meaning_en: 'Marks the topic of the sentence. Indicates what the sentence is about.',
    structure: 'N は ～',
    example_jp: '私は学生です。', example_es: 'Yo soy estudiante.',
  },
  {
    id: 'n5-02', jlpt: 'N5', pattern: 'も', name_es: 'Partícula も (también)', name_en: 'Also, Too も',
    meaning_es: 'Sustituye a は o が/を para indicar "también". Añade una información similar.',
    meaning_en: 'Replaces は or が/を to mean "also/too". Adds similar information.',
    structure: 'N も ～',
    example_jp: '田中さんも学生です。', example_es: 'Tanaka también es estudiante.',
  },
  {
    id: 'n5-03', jlpt: 'N5', pattern: 'が', name_es: 'Partícula de sujeto が', name_en: 'Subject marker が',
    meaning_es: 'Marca el sujeto gramatical de la oración. También se usa con verbos de existencia y gusto.',
    meaning_en: 'Marks the grammatical subject. Also used with existence and preference verbs.',
    structure: 'N が ～',
    example_jp: '猫が好きです。', example_es: 'Me gustan los gatos.',
  },
  {
    id: 'n5-04', jlpt: 'N5', pattern: 'を', name_es: 'Partícula de objeto を', name_en: 'Object marker を',
    meaning_es: 'Marca el objeto directo de un verbo transitivo.',
    meaning_en: 'Marks the direct object of a transitive verb.',
    structure: 'N を Vtr',
    example_jp: '水を飲みます。', example_es: 'Bebo agua.',
  },
  {
    id: 'n5-05', jlpt: 'N5', pattern: 'に', name_es: 'Partícula de destino/tiempo に', name_en: 'Direction/time marker に',
    meaning_es: 'Indica destino de movimiento, lugar de existencia, o tiempo específico.',
    meaning_en: 'Indicates destination of movement, location of existence, or specific time.',
    structure: 'N に V',
    example_jp: '学校に行きます。', example_es: 'Voy a la escuela.',
  },
  {
    id: 'n5-06', jlpt: 'N5', pattern: 'で', name_es: 'Partícula de lugar/medio で', name_en: 'Location/means marker で',
    meaning_es: 'Indica el lugar donde ocurre una acción, o el medio/herramienta utilizado.',
    meaning_en: 'Indicates the place where an action occurs, or the means/tool used.',
    structure: 'N で V',
    example_jp: '図書館で勉強します。', example_es: 'Estudio en la biblioteca.',
  },
  {
    id: 'n5-07', jlpt: 'N5', pattern: 'の', name_es: 'Partícula posesiva の', name_en: 'Possessive particle の',
    meaning_es: 'Indica posesión, relación o modificación nominal. Equivale a "de" en español.',
    meaning_en: 'Indicates possession, relation, or nominal modification. Like "of" or possessive in English.',
    structure: 'N₁ の N₂',
    example_jp: '私の本です。', example_es: 'Es mi libro.',
  },
  {
    id: 'n5-08', jlpt: 'N5', pattern: 'と', name_es: 'Partícula と (y / con)', name_en: 'And/With particle と',
    meaning_es: 'Une sustantivos de manera exhaustiva ("y") o indica compañía ("con").',
    meaning_en: 'Lists nouns exhaustively ("and") or indicates accompaniment ("with").',
    structure: 'N₁ と N₂ / N と V',
    example_jp: '友達と映画を見ます。', example_es: 'Veo una película con un amigo.',
  },
  {
    id: 'n5-09', jlpt: 'N5', pattern: 'や', name_es: 'Partícula や (y…, entre otros)', name_en: 'Non-exhaustive list や',
    meaning_es: 'Lista sustantivos de manera no exhaustiva, implicando que hay más elementos.',
    meaning_en: 'Lists nouns non-exhaustively, implying there are more items.',
    structure: 'N₁ や N₂ (など)',
    example_jp: 'りんごやバナナを買います。', example_es: 'Compro manzanas y plátanos (entre otras cosas).',
  },
  {
    id: 'n5-10', jlpt: 'N5', pattern: 'か', name_es: 'Partícula de pregunta か', name_en: 'Question marker か',
    meaning_es: 'Convierte una oración declarativa en una pregunta.',
    meaning_en: 'Turns a statement into a yes/no question.',
    structure: '～ か',
    example_jp: '学生ですか。', example_es: '¿Eres estudiante?',
  },
  {
    id: 'n5-11', jlpt: 'N5', pattern: 'ね', name_es: 'Partícula final ね', name_en: 'Sentence-ending particle ね',
    meaning_es: 'Busca confirmación o acuerdo del oyente. Equivale a "¿verdad?" o "¿no?',
    meaning_en: 'Seeks confirmation or agreement from the listener. Like "right?" or "isn\'t it?".',
    structure: '～ ね',
    example_jp: 'いい天気ですね。', example_es: 'Hace buen tiempo, ¿verdad?',
  },
  {
    id: 'n5-12', jlpt: 'N5', pattern: 'よ', name_es: 'Partícula final よ', name_en: 'Sentence-ending particle よ',
    meaning_es: 'Da énfasis o informa al oyente de algo que no sabe. Expresa certeza del hablante.',
    meaning_en: 'Adds emphasis or informs the listener of something they don\'t know. Expresses speaker\'s certainty.',
    structure: '～ よ',
    example_jp: 'これは本当ですよ。', example_es: 'Esto es verdad (te lo digo yo).',
  },
  {
    id: 'n5-13', jlpt: 'N5', pattern: 'です', name_es: 'Cópula です', name_en: 'Copula です',
    meaning_es: 'Forma educada de "ser/estar". Equivale a "soy/eres/es…" en registro formal.',
    meaning_en: 'Polite copula equivalent to "am/is/are". Used in formal/polite speech.',
    structure: 'N/Adj-な です',
    example_jp: '私は学生です。', example_es: 'Soy estudiante.',
  },
  {
    id: 'n5-14', jlpt: 'N5', pattern: 'じゃない / ではない', name_es: 'Negación de です', name_en: 'Negation of です',
    meaning_es: 'Forma negativa de です. じゃない es coloquial; ではない/ではありません es formal.',
    meaning_en: 'Negative form of です. じゃない is casual; ではない/ではありません is formal.',
    structure: 'N じゃない / ではない',
    example_jp: '学生じゃない。', example_es: 'No soy estudiante.',
  },
  {
    id: 'n5-15', jlpt: 'N5', pattern: 'でした', name_es: 'Pasado de です', name_en: 'Past form of です',
    meaning_es: 'Forma pasada de です. Indica que algo era o existía en el pasado.',
    meaning_en: 'Past tense of です. Indicates something was or existed in the past.',
    structure: 'N/Adj-な でした',
    example_jp: '子供の頃、学生でした。', example_es: 'De niño, era estudiante.',
  },
  {
    id: 'n5-16', jlpt: 'N5', pattern: 'じゃなかった / ではなかった', name_es: 'Pasado negativo de です', name_en: 'Past negative of です',
    meaning_es: 'Forma pasado negativa de です.',
    meaning_en: 'Past negative form of です.',
    structure: 'N じゃなかった / ではなかった',
    example_jp: '先生じゃなかった。', example_es: 'No era profesor.',
  },
  {
    id: 'n5-17', jlpt: 'N5', pattern: 'います / あります', name_es: 'Verbos de existencia います/あります', name_en: 'Existence verbs います/あります',
    meaning_es: 'います: existencia de seres animados. あります: existencia de cosas inanimadas.',
    meaning_en: 'います: existence of animate beings. あります: existence of inanimate objects.',
    structure: 'N が います/あります',
    example_jp: '猫がいます。本があります。', example_es: 'Hay un gato. Hay un libro.',
  },
  {
    id: 'n5-18', jlpt: 'N5', pattern: 'に います / に あります', name_es: 'Ubicación con に います/あります', name_en: 'Location に います/あります',
    meaning_es: 'Indica dónde se encuentra algo o alguien.',
    meaning_en: 'Indicates where something/someone is located.',
    structure: 'N は [lugar] に います/あります',
    example_jp: '猫はソファーの上にいます。', example_es: 'El gato está encima del sofá.',
  },
  {
    id: 'n5-19', jlpt: 'N5', pattern: 'ます形 (presente/futuro)', name_es: 'Forma ます (presente/futuro)', name_en: 'Polite present/future ます',
    meaning_es: 'Forma verbal educada para acciones habituales o que se realizarán en el futuro.',
    meaning_en: 'Polite verb form for habitual actions or future actions.',
    structure: 'V-ます',
    example_jp: '毎日日本語を勉強します。', example_es: 'Estudio japonés todos los días.',
  },
  {
    id: 'n5-20', jlpt: 'N5', pattern: 'ません', name_es: 'Negación ません', name_en: 'Polite negative ません',
    meaning_es: 'Forma negativa educada del presente/futuro.',
    meaning_en: 'Polite negative of present/future.',
    structure: 'V-ません',
    example_jp: '肉を食べません。', example_es: 'No como carne.',
  },
  {
    id: 'n5-21', jlpt: 'N5', pattern: 'ました', name_es: 'Pasado ました', name_en: 'Polite past ました',
    meaning_es: 'Forma pasada afirmativa educada.',
    meaning_en: 'Polite affirmative past tense.',
    structure: 'V-ました',
    example_jp: '昨日映画を見ました。', example_es: 'Ayer vi una película.',
  },
  {
    id: 'n5-22', jlpt: 'N5', pattern: 'ませんでした', name_es: 'Pasado negativo ませんでした', name_en: 'Polite negative past',
    meaning_es: 'Forma pasada negativa educada.',
    meaning_en: 'Polite negative past tense.',
    structure: 'V-ませんでした',
    example_jp: '昨日勉強しませんでした。', example_es: 'Ayer no estudié.',
  },
  {
    id: 'n5-23', jlpt: 'N5', pattern: 'て形', name_es: 'Forma て', name_en: 'Te-form',
    meaning_es: 'Forma conectora del verbo. Sirve para encadenar acciones, pedir permiso, etc.',
    meaning_en: 'Connective verb form. Used to chain actions, ask permission, etc.',
    structure: 'V-て',
    example_jp: '起きて、歯を磨いて、朝ごはんを食べます。', example_es: 'Me levanto, me lavo los dientes y desayuno.',
  },
  {
    id: 'n5-24', jlpt: 'N5', pattern: 'てください', name_es: 'Petición てください', name_en: 'Please do… てください',
    meaning_es: 'Pide educadamente a alguien que haga algo.',
    meaning_en: 'Politely requests someone to do something.',
    structure: 'V-てください',
    example_jp: 'ここに書いてください。', example_es: 'Por favor, escribe aquí.',
  },
  {
    id: 'n5-25', jlpt: 'N5', pattern: 'てもいい', name_es: 'Permiso てもいい', name_en: 'May I… / It\'s okay to… てもいい',
    meaning_es: 'Pide o concede permiso para hacer algo.',
    meaning_en: 'Asks for or grants permission to do something.',
    structure: 'V-てもいい(ですか)',
    example_jp: 'ここに座ってもいいですか。', example_es: '¿Puedo sentarme aquí?',
  },
  {
    id: 'n5-26', jlpt: 'N5', pattern: 'てはいけない', name_es: 'Prohibición てはいけない', name_en: 'Must not… てはいけない',
    meaning_es: 'Expresa que algo está prohibido o no se debe hacer.',
    meaning_en: 'Expresses that something is prohibited or must not be done.',
    structure: 'V-てはいけない',
    example_jp: 'ここで写真を撮ってはいけません。', example_es: 'No se puede fotografiar aquí.',
  },
  {
    id: 'n5-27', jlpt: 'N5', pattern: 'ている', name_es: 'Acción en progreso ている', name_en: 'Ongoing action ている',
    meaning_es: 'Indica una acción en progreso (presente continuo) o un estado resultante.',
    meaning_en: 'Indicates an ongoing action (progressive) or a resultant state.',
    structure: 'V-ている',
    example_jp: '今、ご飯を食べています。', example_es: 'Ahora mismo estoy comiendo.',
  },
  {
    id: 'n5-28', jlpt: 'N5', pattern: 'ない形 (forma negativa plana)', name_es: 'Forma ない (negativo informal)', name_en: 'Plain negative form ない',
    meaning_es: 'Forma negativa del verbo en registro informal/plano.',
    meaning_en: 'Informal negative verb form.',
    structure: 'V-ない',
    example_jp: '行かない。', example_es: 'No voy.',
  },
  {
    id: 'n5-29', jlpt: 'N5', pattern: 'た形 (pasado plano)', name_es: 'Forma た (pasado informal)', name_en: 'Plain past form た',
    meaning_es: 'Forma pasada del verbo en registro informal.',
    meaning_en: 'Informal past tense verb form.',
    structure: 'V-た',
    example_jp: '昨日行った。', example_es: 'Fui ayer.',
  },
  {
    id: 'n5-30', jlpt: 'N5', pattern: 'い形容詞', name_es: 'Adjetivos en い', name_en: 'I-adjectives',
    meaning_es: 'Adjetivos que terminan en い. Se conjugan directamente (sin です para informal).',
    meaning_en: 'Adjectives ending in い. Conjugate directly without a copula in informal speech.',
    structure: 'い-Adj (い)',
    example_jp: 'この本は面白い。', example_es: 'Este libro es interesante.',
  },
  {
    id: 'n5-31', jlpt: 'N5', pattern: 'い形容詞 + くない', name_es: 'Negación de adj-い', name_en: 'Negative i-adjective',
    meaning_es: 'Forma negativa de los adjetivos en い. Se reemplaza い por くない.',
    meaning_en: 'Negative form of i-adjectives. Replace い with くない.',
    structure: 'い-Adj → くない',
    example_jp: 'この映画は面白くない。', example_es: 'Esta película no es interesante.',
  },
  {
    id: 'n5-32', jlpt: 'N5', pattern: 'い形容詞 + かった', name_es: 'Pasado de adj-い', name_en: 'Past i-adjective',
    meaning_es: 'Forma pasada de los adjetivos en い. Se reemplaza い por かった.',
    meaning_en: 'Past form of i-adjectives. Replace い with かった.',
    structure: 'い-Adj → かった',
    example_jp: '昨日は寒かった。', example_es: 'Ayer hacía frío.',
  },
  {
    id: 'n5-33', jlpt: 'N5', pattern: 'な形容詞', name_es: 'Adjetivos en な', name_en: 'Na-adjectives',
    meaning_es: 'Adjetivos que requieren な antes del sustantivo. Funcionan con です como cópula.',
    meaning_en: 'Adjectives that require な before a noun. Use です as copula.',
    structure: 'な-Adj な N / な-Adj です',
    example_jp: '彼女は親切な人です。', example_es: 'Ella es una persona amable.',
  },
  {
    id: 'n5-34', jlpt: 'N5', pattern: 'と思います', name_es: 'Opinión と思います', name_en: 'I think that… と思います',
    meaning_es: 'Expresa la opinión del hablante.',
    meaning_en: 'Expresses the speaker\'s opinion or thought.',
    structure: '～と思います',
    example_jp: '彼は来ると思います。', example_es: 'Creo que él vendrá.',
  },
  {
    id: 'n5-35', jlpt: 'N5', pattern: 'から (razón)', name_es: 'Razón から', name_en: 'Because から',
    meaning_es: 'Indica la razón o causa de algo.',
    meaning_en: 'Indicates the reason or cause.',
    structure: '～から、～',
    example_jp: '疲れたから、早く寝ます。', example_es: 'Como estoy cansado, me acuesto pronto.',
  },
  {
    id: 'n5-36', jlpt: 'N5', pattern: 'が (pero/sin embargo)', name_es: 'Contraste が', name_en: 'But/However が',
    meaning_es: 'Conecta dos oraciones con información contrastante. Equivale a "pero".',
    meaning_en: 'Connects two clauses with contrasting information. Means "but/however".',
    structure: '～が、～',
    example_jp: '高いですが、おいしいです。', example_es: 'Es caro, pero está rico.',
  },
  {
    id: 'n5-37', jlpt: 'N5', pattern: 'けど / けれど', name_es: 'Contraste けど/けれど', name_en: 'But (casual) けど',
    meaning_es: 'Versión coloquial de が. Conecta oraciones con contraste. A veces suaviza el enunciado.',
    meaning_en: 'Casual version of が. Connects clauses with contrast or softens a statement.',
    structure: '～けど、～',
    example_jp: '行きたいけど、お金がない。', example_es: 'Quiero ir, pero no tengo dinero.',
  },
  {
    id: 'n5-38', jlpt: 'N5', pattern: 'し～し', name_es: 'Enumeración し～し', name_en: 'And moreover し',
    meaning_es: 'Enumera varias razones o características. Sugiere que hay más razones implícitas.',
    meaning_en: 'Lists multiple reasons or characteristics. Implies there are additional reasons.',
    structure: '～し、～し、～',
    example_jp: '安いし、おいしいし、このレストランが好きです。', example_es: 'Es barato, además está rico; me gusta este restaurante.',
  },
  {
    id: 'n5-39', jlpt: 'N5', pattern: 'どんな', name_es: '¿Qué tipo de? どんな', name_en: 'What kind of? どんな',
    meaning_es: 'Pregunta por las características o tipo de algo.',
    meaning_en: 'Asks about the characteristics or type of something.',
    structure: 'どんな N',
    example_jp: 'どんな音楽が好きですか。', example_es: '¿Qué tipo de música te gusta?',
  },
  {
    id: 'n5-40', jlpt: 'N5', pattern: 'どのくらい / どれくらい', name_es: '¿Cuánto tiempo/distancia?', name_en: 'How long/far? どのくらい',
    meaning_es: 'Pregunta por la cantidad, duración o distancia.',
    meaning_en: 'Asks about quantity, duration, or distance.',
    structure: 'どのくらい ～',
    example_jp: 'ここから駅までどのくらいですか。', example_es: '¿A qué distancia queda la estación de aquí?',
  },
  {
    id: 'n5-41', jlpt: 'N5', pattern: 'たい', name_es: 'Deseo たい', name_en: 'Want to do たい',
    meaning_es: 'Expresa el deseo del hablante de hacer algo.',
    meaning_en: 'Expresses the speaker\'s desire to do something.',
    structure: 'V-たい',
    example_jp: '日本に行きたい。', example_es: 'Quiero ir a Japón.',
  },
  {
    id: 'n5-42', jlpt: 'N5', pattern: 'ましょう / ましょうか', name_es: 'Propuesta ましょう', name_en: 'Let\'s…/Shall we? ましょう',
    meaning_es: 'ましょう: propone hacer algo juntos. ましょうか: ofrece ayuda o propone con pregunta.',
    meaning_en: 'ましょう: proposes doing something together. ましょうか: offers help or asks with a question.',
    structure: 'V-ましょう(か)',
    example_jp: '一緒に行きましょう。', example_es: 'Vamos juntos.',
  },
  {
    id: 'n5-43', jlpt: 'N5', pattern: 'に行く / に来る', name_es: 'Ir/Venir a hacer に行く・に来る', name_en: 'Go/Come to do に行く・に来る',
    meaning_es: 'Indica el propósito de un movimiento: ir o venir a hacer algo.',
    meaning_en: 'Indicates the purpose of movement: going or coming to do something.',
    structure: 'V-に + 行く/来る',
    example_jp: '映画を見に行きます。', example_es: 'Voy a ver una película.',
  },
  {
    id: 'n5-44', jlpt: 'N5', pattern: 'ないでください', name_es: 'Petición negativa ないでください', name_en: 'Please don\'t… ないでください',
    meaning_es: 'Pide educadamente a alguien que no haga algo.',
    meaning_en: 'Politely asks someone not to do something.',
    structure: 'V-ないでください',
    example_jp: 'ここで食べないでください。', example_es: 'Por favor, no coma aquí.',
  },
  {
    id: 'n5-45', jlpt: 'N5', pattern: 'なければならない / なければいけない', name_es: 'Obligación なければならない', name_en: 'Must do… なければならない',
    meaning_es: 'Expresa obligación: "tengo que / debo hacer".',
    meaning_en: 'Expresses obligation: "must do / have to do".',
    structure: 'V-なければならない',
    example_jp: '宿題をしなければならない。', example_es: 'Tengo que hacer los deberes.',
  },
  {
    id: 'n5-46', jlpt: 'N5', pattern: 'なくてもいい', name_es: 'No es necesario なくてもいい', name_en: 'Don\'t have to… なくてもいい',
    meaning_es: 'Indica que no es necesario hacer algo.',
    meaning_en: 'Indicates that it is not necessary to do something.',
    structure: 'V-なくてもいい',
    example_jp: '今日は来なくてもいいです。', example_es: 'Hoy no tienes que venir.',
  },
  {
    id: 'n5-47', jlpt: 'N5', pattern: 'で (por/por medío de)', name_es: 'Medio de transporte で', name_en: 'By means of で',
    meaning_es: 'Indica el medio de transporte o la herramienta utilizada.',
    meaning_en: 'Indicates the means of transportation or tool used.',
    structure: 'N で V',
    example_jp: '電車で行きます。', example_es: 'Voy en tren.',
  },
  {
    id: 'n5-48', jlpt: 'N5', pattern: 'から～まで', name_es: 'Desde～hasta から～まで', name_en: 'From～to から～まで',
    meaning_es: 'Indica el punto de inicio y fin de tiempo, lugar o cantidad.',
    meaning_en: 'Indicates the starting and ending point of time, place, or quantity.',
    structure: '[lugar/tiempo] から [lugar/tiempo] まで',
    example_jp: '9時から5時まで働きます。', example_es: 'Trabajo desde las 9 hasta las 5.',
  },
  {
    id: 'n5-49', jlpt: 'N5', pattern: 'より', name_es: 'Comparación より', name_en: 'More than より',
    meaning_es: 'Indica el punto de comparación. "A は B より ～" = "A es más ～ que B".',
    meaning_en: 'Indicates the standard of comparison. "A は B より ～" = "A is more ～ than B".',
    structure: 'N₁ は N₂ より Adj',
    example_jp: '東京は大阪より大きいです。', example_es: 'Tokio es más grande que Osaka.',
  },
  {
    id: 'n5-50', jlpt: 'N5', pattern: 'の中で一番', name_es: 'El más… の中で一番', name_en: 'The most… の中で一番',
    meaning_es: 'Expresa el superlativo: "el más ～ de todos".',
    meaning_en: 'Expresses the superlative: "the most ～ of all".',
    structure: 'N の中で N が一番 Adj',
    example_jp: 'クラスの中で誰が一番背が高いですか。', example_es: '¿Quién es el más alto de la clase?',
  },
  {
    id: 'n5-51', jlpt: 'N5', pattern: 'どちら / どれ (elección)', name_es: '¿Cuál? どちら・どれ', name_en: 'Which one? どちら・どれ',
    meaning_es: 'どちら: de dos opciones. どれ: de tres o más opciones.',
    meaning_en: 'どちら: between two options. どれ: among three or more options.',
    structure: 'どちら/どれ が ～',
    example_jp: 'AとBとどちらが好きですか。', example_es: '¿Cuál te gusta más, A o B?',
  },
  {
    id: 'n5-52', jlpt: 'N5', pattern: 'たことがある', name_es: 'Experiencia たことがある', name_en: 'Have done before たことがある',
    meaning_es: 'Indica que el hablante ha tenido una experiencia en el pasado.',
    meaning_en: 'Indicates the speaker has had a past experience.',
    structure: 'V-たことがある',
    example_jp: '富士山に登ったことがあります。', example_es: 'He subido al monte Fuji (alguna vez).',
  },
  {
    id: 'n5-53', jlpt: 'N5', pattern: 'たり～たりする', name_es: 'Lista de acciones たり～たりする', name_en: 'Do things like… たり～たりする',
    meaning_es: 'Enumera acciones representativas de manera no exhaustiva.',
    meaning_en: 'Lists representative actions non-exhaustively.',
    structure: 'V-たり、V-たりする',
    example_jp: '週末は映画を見たり、本を読んだりします。', example_es: 'Los fines de semana veo películas, leo libros, etc.',
  },
  {
    id: 'n5-54', jlpt: 'N5', pattern: 'ながら', name_es: 'Acciones simultáneas ながら', name_en: 'While doing… ながら',
    meaning_es: 'Indica que dos acciones ocurren al mismo tiempo. El sujeto realiza ambas.',
    meaning_en: 'Indicates two actions happening simultaneously by the same subject.',
    structure: 'V-ながら V',
    example_jp: '音楽を聴きながら勉強します。', example_es: 'Estudio mientras escucho música.',
  },
  {
    id: 'n5-55', jlpt: 'N5', pattern: 'てから', name_es: 'Después de hacer てから', name_en: 'After doing てから',
    meaning_es: 'Indica que una acción ocurre después de completar otra.',
    meaning_en: 'Indicates one action occurs after completing another.',
    structure: 'V-てから V',
    example_jp: '宿題をしてから遊びます。', example_es: 'Después de hacer los deberes, jugaré.',
  },
  {
    id: 'n5-56', jlpt: 'N5', pattern: 'とき', name_es: 'Cuando とき', name_en: 'When とき',
    meaning_es: 'Indica el momento en que ocurre algo.',
    meaning_en: 'Indicates the time when something occurs.',
    structure: 'V/Adj/N の とき',
    example_jp: '子供の時、よく公園で遊びました。', example_es: 'Cuando era niño, jugaba mucho en el parque.',
  },
  {
    id: 'n5-57', jlpt: 'N5', pattern: 'でも', name_es: 'Partícula でも (incluso/cualquier)', name_en: 'Even / Any… でも',
    meaning_es: 'Añadido a pronombres interrogativos da un significado universal ("cualquiera, siempre, etc.").',
    meaning_en: 'Added to interrogative pronouns gives a universal meaning ("anyone, always, etc.").',
    structure: 'WH + でも',
    example_jp: '誰でも参加できます。', example_es: 'Cualquiera puede participar.',
  },
  {
    id: 'n5-58', jlpt: 'N5', pattern: 'だから', name_es: 'Por eso だから', name_en: 'Therefore だから',
    meaning_es: 'Conector causal informal. "Por eso / Por esa razón".',
    meaning_en: 'Informal causal connector. "Therefore / That\'s why".',
    structure: 'だから、～',
    example_jp: '雨だから、傘を持って行きます。', example_es: 'Llueve, así que llevaré paraguas.',
  },
  {
    id: 'n5-59', jlpt: 'N5', pattern: 'つもり', name_es: 'Intención つもり', name_en: 'Intention / Plan to… つもり',
    meaning_es: 'Expresa la intención o plan del hablante.',
    meaning_en: 'Expresses the speaker\'s intention or plan.',
    structure: 'V-る つもり',
    example_jp: '来年日本に行くつもりです。', example_es: 'Tengo pensado ir a Japón el año que viene.',
  },
  {
    id: 'n5-60', jlpt: 'N5', pattern: 'かもしれない', name_es: 'Posibilidad かもしれない', name_en: 'Might / Maybe かもしれない',
    meaning_es: 'Expresa posibilidad o incertidumbre del hablante.',
    meaning_en: 'Expresses possibility or the speaker\'s uncertainty.',
    structure: '～かもしれない',
    example_jp: '明日雨かもしれない。', example_es: 'Puede que mañana llueva.',
  },

  // ─────────────────────────────────────────────
  // N4
  // ─────────────────────────────────────────────
  {
    id: 'n4-01', jlpt: 'N4', pattern: 'てあげる / てくれる / てもらう', name_es: 'Verbos de dar/recibir favores', name_en: 'Giving/Receiving favors',
    meaning_es: 'てあげる: dar un favor a alguien. てくれる: recibir favor del otro. てもらう: conseguir que alguien lo haga.',
    meaning_en: 'てあげる: do a favor for someone. てくれる: receive a favor. てもらう: get someone to do something.',
    structure: 'V-て + あげる/くれる/もらう',
    example_jp: '荷物を持ってあげました。', example_es: 'Le llevé el equipaje (como favor).',
  },
  {
    id: 'n4-02', jlpt: 'N4', pattern: 'てしまう', name_es: 'Completar/lamentar てしまう', name_en: 'Completely done / Regret てしまう',
    meaning_es: 'Indica que una acción se completó (a menudo involuntariamente o con pesar).',
    meaning_en: 'Indicates an action was completed, often with regret or accidentally.',
    structure: 'V-てしまう',
    example_jp: 'ケーキを全部食べてしまった。', example_es: 'Me comí todo el pastel (me pasé).',
  },
  {
    id: 'n4-03', jlpt: 'N4', pattern: 'ておく', name_es: 'Preparación ておく', name_en: 'Do in advance / Preparation ておく',
    meaning_es: 'Indica que se hace algo de antemano o que se deja en un estado para el futuro.',
    meaning_en: 'Indicates doing something in advance or leaving something in a state for later.',
    structure: 'V-ておく',
    example_jp: '旅行の前にホテルを予約しておく。', example_es: 'Antes del viaje, reservaré el hotel de antemano.',
  },
  {
    id: 'n4-04', jlpt: 'N4', pattern: 'てみる', name_es: 'Intentar/probar てみる', name_en: 'Try doing てみる',
    meaning_es: 'Indica intentar hacer algo para ver qué pasa.',
    meaning_en: 'Indicates trying to do something to see what happens.',
    structure: 'V-てみる',
    example_jp: 'この料理を作ってみたい。', example_es: 'Quiero intentar hacer este plato.',
  },
  {
    id: 'n4-05', jlpt: 'N4', pattern: 'てほしい', name_es: 'Querer que alguien haga てほしい', name_en: 'Want someone to do てほしい',
    meaning_es: 'Expresa el deseo de que otra persona haga algo.',
    meaning_en: 'Expresses the desire for someone else to do something.',
    structure: 'N に V-てほしい',
    example_jp: '彼に来てほしい。', example_es: 'Quiero que él venga.',
  },
  {
    id: 'n4-06', jlpt: 'N4', pattern: 'ようにする', name_es: 'Esforzarse por ようにする', name_en: 'Make sure to / Try to ようにする',
    meaning_es: 'Indica el esfuerzo por establecer un hábito o alcanzar un objetivo.',
    meaning_en: 'Indicates making an effort to establish a habit or achieve a goal.',
    structure: 'V-ようにする',
    example_jp: '毎日運動するようにしています。', example_es: 'Me esfuerzo por hacer ejercicio todos los días.',
  },
  {
    id: 'n4-07', jlpt: 'N4', pattern: 'ようになる', name_es: 'Llegar a poder ようになる', name_en: 'Come to be able to ようになる',
    meaning_es: 'Indica un cambio gradual de estado o habilidad.',
    meaning_en: 'Indicates a gradual change of state or ability.',
    structure: 'V-ようになる',
    example_jp: '日本語が話せるようになった。', example_es: 'He llegado a poder hablar japonés.',
  },
  {
    id: 'n4-08', jlpt: 'N4', pattern: 'ことができる', name_es: 'Poder hacer ことができる', name_en: 'Be able to do ことができる',
    meaning_es: 'Expresa la capacidad o posibilidad de hacer algo.',
    meaning_en: 'Expresses the ability or possibility to do something.',
    structure: 'V-ることができる',
    example_jp: '泳ぐことができます。', example_es: 'Puedo nadar.',
  },
  {
    id: 'n4-09', jlpt: 'N4', pattern: 'ことにする', name_es: 'Decidir hacer ことにする', name_en: 'Decide to do ことにする',
    meaning_es: 'Expresa una decisión tomada por el hablante.',
    meaning_en: 'Expresses a decision made by the speaker.',
    structure: 'V-ることにする',
    example_jp: '毎朝走ることにした。', example_es: 'He decidido correr todas las mañanas.',
  },
  {
    id: 'n4-10', jlpt: 'N4', pattern: 'ことになる', name_es: 'Resultar que / Decidirse ことになる', name_en: 'It has been decided / It turns out ことになる',
    meaning_es: 'Indica que algo se ha decidido o resulta de factores externos al hablante.',
    meaning_en: 'Indicates something has been decided or results from external factors.',
    structure: 'V-ることになる',
    example_jp: '来月転勤することになりました。', example_es: 'Ha resultado que me trasladan el mes que viene.',
  },
  {
    id: 'n4-11', jlpt: 'N4', pattern: 'ことがある', name_es: 'Ocurre a veces ことがある', name_en: 'Sometimes happens ことがある',
    meaning_es: 'Indica que algo ocurre de vez en cuando.',
    meaning_en: 'Indicates something happens occasionally.',
    structure: 'V-ることがある',
    example_jp: '遅刻することがある。', example_es: 'A veces llego tarde.',
  },
  {
    id: 'n4-12', jlpt: 'N4', pattern: 'だろう / でしょう', name_es: 'Suposición だろう・でしょう', name_en: 'Probably / I suppose だろう・でしょう',
    meaning_es: 'Expresa suposición o probabilidad moderada.',
    meaning_en: 'Expresses supposition or moderate probability.',
    structure: '～だろう/でしょう',
    example_jp: '明日は晴れるでしょう。', example_es: 'Probablemente mañana hará sol.',
  },
  {
    id: 'n4-13', jlpt: 'N4', pattern: 'はずだ', name_es: 'Se supone que はずだ', name_en: 'Should be / Expected to はずだ',
    meaning_es: 'Expresa expectativa lógica basada en hechos o razonamiento.',
    meaning_en: 'Expresses logical expectation based on facts or reasoning.',
    structure: '～はずだ',
    example_jp: '彼はもう着いているはずだ。', example_es: 'Ya debería de haber llegado.',
  },
  {
    id: 'n4-14', jlpt: 'N4', pattern: 'らしい', name_es: 'Al parecer / Parece que らしい', name_en: 'Seems like / I heard that らしい',
    meaning_es: 'Indica información obtenida de fuentes externas o apariencia típica.',
    meaning_en: 'Indicates information obtained from outside sources or typical appearance.',
    structure: '～らしい',
    example_jp: '彼女は結婚したらしい。', example_es: 'Parece que ella se casó.',
  },
  {
    id: 'n4-15', jlpt: 'N4', pattern: 'ようだ / みたいだ', name_es: 'Parece que ようだ・みたいだ', name_en: 'It seems / It looks like ようだ・みたいだ',
    meaning_es: 'Expresa apariencia o semejanza basada en la observación directa del hablante.',
    meaning_en: 'Expresses appearance or similarity based on direct observation.',
    structure: '～ようだ/みたいだ',
    example_jp: '彼は疲れているようだ。', example_es: 'Parece que está cansado.',
  },
  {
    id: 'n4-16', jlpt: 'N4', pattern: 'そうだ (aspecto)', name_es: 'Parece que va a ~ そうだ', name_en: 'Looks like it will… そうだ',
    meaning_es: 'Basado en apariencia visual directa, predice lo que está a punto de ocurrir.',
    meaning_en: 'Based on direct visual appearance, predicts what is about to happen.',
    structure: 'V-そうだ / Adj-そうだ',
    example_jp: '雨が降りそうだ。', example_es: 'Parece que va a llover.',
  },
  {
    id: 'n4-17', jlpt: 'N4', pattern: 'そうだ (rumor)', name_es: 'Dicen que そうだ', name_en: 'I heard that そうだ',
    meaning_es: 'Reporta información escuchada de otros, sin verificación propia.',
    meaning_en: 'Reports hearsay information heard from others, without personal verification.',
    structure: '～そうだ (después de forma plana)',
    example_jp: '明日は試験があるそうだ。', example_es: 'Dicen que mañana hay examen.',
  },
  {
    id: 'n4-18', jlpt: 'N4', pattern: 'のに (a pesar de)', name_es: 'A pesar de のに', name_en: 'Even though / Despite のに',
    meaning_es: 'Expresa contraste o decepción entre lo esperado y la realidad.',
    meaning_en: 'Expresses contrast or disappointment between expectation and reality.',
    structure: '～のに、～',
    example_jp: '一生懸命勉強したのに、試験に落ちた。', example_es: 'Aunque estudié mucho, suspendí el examen.',
  },
  {
    id: 'n4-19', jlpt: 'N4', pattern: 'たら', name_es: 'Condicional たら', name_en: 'If/When (conditional) たら',
    meaning_es: 'Condicional que indica "si/cuando se cumple A, entonces B". A menudo implica que A ya ocurrió.',
    meaning_en: 'Conditional meaning "if/when A occurs, then B". Often implies A is already completed.',
    structure: 'V-たら',
    example_jp: '家に帰ったら電話して。', example_es: 'Cuando llegues a casa, llámame.',
  },
  {
    id: 'n4-20', jlpt: 'N4', pattern: 'ば', name_es: 'Condicional ば', name_en: 'If… ば conditional',
    meaning_es: 'Condicional hipotético: "si haces X, entonces Y". Indica condición necesaria.',
    meaning_en: 'Hypothetical conditional: "if you do X, then Y". Indicates a necessary condition.',
    structure: 'V-ば',
    example_jp: '頑張れば合格できる。', example_es: 'Si te esfuerzas, podrás aprobar.',
  },
  {
    id: 'n4-21', jlpt: 'N4', pattern: 'なら', name_es: 'Condicional なら', name_en: 'If that\'s the case なら',
    meaning_es: 'Condicional basado en una premisa o contexto mencionado. "Si es que / en caso de que".',
    meaning_en: 'Conditional based on a mentioned premise or context. "If that\'s the case / assuming".',
    structure: 'N/V-plain なら',
    example_jp: '行くなら、早めに出発して。', example_es: 'Si vas a ir, sal pronto.',
  },
  {
    id: 'n4-22', jlpt: 'N4', pattern: 'と (condicional)', name_es: 'Condicional と', name_en: 'Natural consequence と',
    meaning_es: 'Condicional natural o inevitables. "Cuando/si haces A, B ocurre siempre".',
    meaning_en: 'Natural or inevitable conditional. "When/if A, B always happens".',
    structure: 'V-dict/Adj + と',
    example_jp: '春になると、桜が咲く。', example_es: 'Cuando llega la primavera, los cerezos florecen.',
  },
  {
    id: 'n4-23', jlpt: 'N4', pattern: 'ために', name_es: 'Para/por causa de ために', name_en: 'For the purpose of / Due to ために',
    meaning_es: 'Indica propósito (para hacer X) o causa (debido a X).',
    meaning_en: 'Indicates purpose (in order to do X) or cause (due to X).',
    structure: 'V-る/N の ために',
    example_jp: '健康のために運動します。', example_es: 'Hago ejercicio por la salud.',
  },
  {
    id: 'n4-24', jlpt: 'N4', pattern: 'ように', name_es: 'Para que / De manera que ように', name_en: 'In order to / So that ように',
    meaning_es: 'Indica propósito o una meta a alcanzar. Seguido de verbos de esfuerzo o petición.',
    meaning_en: 'Indicates purpose or goal to achieve. Followed by verbs of effort or request.',
    structure: 'V-ように',
    example_jp: '聞こえるように大きな声で話してください。', example_es: 'Por favor, habla en voz alta para que se pueda escuchar.',
  },
  {
    id: 'n4-25', jlpt: 'N4', pattern: 'まま', name_es: 'Sin cambiar de estado まま', name_en: 'Leaving as is / While still まま',
    meaning_es: 'Indica que una acción ocurre mientras el estado previo permanece sin cambiar.',
    meaning_en: 'Indicates an action occurs while a previous state remains unchanged.',
    structure: 'V-た/Adj まま',
    example_jp: '靴を履いたまま部屋に入った。', example_es: 'Entró al cuarto con los zapatos puestos.',
  },
  {
    id: 'n4-26', jlpt: 'N4', pattern: 'ところ', name_es: 'Momento/punto ところ', name_en: 'Just about to / In the middle of ところ',
    meaning_es: 'Indica el punto exacto en el tiempo de una acción (a punto de, en proceso, recién terminado).',
    meaning_en: 'Indicates the exact point in time of an action (about to, in progress, just finished).',
    structure: 'V-る/ている/た ところ',
    example_jp: '今出かけるところです。', example_es: 'Estoy a punto de salir ahora.',
  },
  {
    id: 'n4-27', jlpt: 'N4', pattern: 'ばかり', name_es: 'Solo/recién ばかり', name_en: 'Just did / Only ばかり',
    meaning_es: 'ばかりだ: recién hecho. ばかり: solo/nada más que.',
    meaning_en: 'ばかりだ: just completed. ばかり: nothing but / only.',
    structure: 'V-た ばかり / N ばかり',
    example_jp: '日本に来たばかりです。', example_es: 'Acabo de llegar a Japón.',
  },
  {
    id: 'n4-28', jlpt: 'N4', pattern: 'まで (hasta el punto de)', name_es: 'Hasta el punto de まで', name_en: 'To the extent of / Even まで',
    meaning_es: 'Indica un límite sorprendente o extremo.',
    meaning_en: 'Indicates a surprising or extreme limit.',
    structure: 'N/V-dict まで',
    example_jp: '泣くまで笑った。', example_es: 'Reí hasta llorar.',
  },
  {
    id: 'n4-29', jlpt: 'N4', pattern: 'だけ', name_es: 'Solo/únicamente だけ', name_en: 'Only / Just だけ',
    meaning_es: 'Limita la cantidad o el alcance: "solo, únicamente, nada más que".',
    meaning_en: 'Limits quantity or scope: "only, just, nothing but".',
    structure: 'N/V-dict だけ',
    example_jp: '水だけ飲みます。', example_es: 'Solo bebo agua.',
  },
  {
    id: 'n4-30', jlpt: 'N4', pattern: 'しか～ない', name_es: 'Solo (con énfasis negativo) しか～ない', name_en: 'Only… (with negative) しか～ない',
    meaning_es: 'Equivale a "solo" pero con connotación de insuficiencia o lástima. Siempre con negativo.',
    meaning_en: 'Means "only" with a nuance of insufficiency or regret. Always used with a negative.',
    structure: 'N しか ～ない',
    example_jp: '100円しかない。', example_es: 'Solo tengo 100 yenes (y me parece poco).',
  },
  {
    id: 'n4-31', jlpt: 'N4', pattern: 'さえ', name_es: 'Incluso/hasta さえ', name_en: 'Even さえ',
    meaning_es: 'Añade énfasis: "incluso, hasta". A menudo implica algo sorprendente.',
    meaning_en: 'Adds emphasis: "even". Often implies something surprising.',
    structure: 'N さえ',
    example_jp: '子供さえ知っている。', example_es: 'Hasta los niños lo saben.',
  },
  {
    id: 'n4-32', jlpt: 'N4', pattern: 'さえ～ば', name_es: 'Con solo que さえ～ば', name_en: 'If only… さえ～ば',
    meaning_es: 'Indica que la única condición necesaria para algo es X.',
    meaning_en: 'Indicates that X is the only condition needed for something.',
    structure: 'N さえ ～ば',
    example_jp: 'お金さえあれば、旅行できる。', example_es: 'Con solo tener dinero, podría viajar.',
  },
  {
    id: 'n4-33', jlpt: 'N4', pattern: 'ても', name_es: 'Aunque / Incluso si ても', name_en: 'Even if / Even though ても',
    meaning_es: 'Indica concesión: "aunque X ocurra, Y".',
    meaning_en: 'Indicates concession: "even if X happens, Y".',
    structure: 'V-ても / Adj-ても',
    example_jp: '雨が降っても、行きます。', example_es: 'Aunque llueva, iré.',
  },
  {
    id: 'n4-34', jlpt: 'N4', pattern: 'くれる / くれない', name_es: 'Petición くれない (casual)', name_en: 'Won\'t you do…? (casual request)',
    meaning_es: 'Forma coloquial de pedir un favor. くれない es más suave que くれ.',
    meaning_en: 'Casual way to ask for a favor. くれない is softer than くれ.',
    structure: 'V-てくれない？',
    example_jp: '手伝ってくれない？', example_es: '¿No me ayudas?',
  },
  {
    id: 'n4-35', jlpt: 'N4', pattern: '〜でいい', name_es: 'Con ~ es suficiente でいい', name_en: '~ will do / ~ is fine でいい',
    meaning_es: 'Indica que algo es aceptable aunque no sea lo ideal.',
    meaning_en: 'Indicates something is acceptable even if not ideal.',
    structure: 'N/V でいい',
    example_jp: '水でいいです。', example_es: 'Con agua está bien.',
  },
  {
    id: 'n4-36', jlpt: 'N4', pattern: 'なさい', name_es: 'Mandato なさい', name_en: 'Do this! (command) なさい',
    meaning_es: 'Forma imperativa educada pero firme. Usada por superiores o padres.',
    meaning_en: 'Polite but firm imperative. Used by superiors or parents.',
    structure: 'V-stem + なさい',
    example_jp: '早く起きなさい。', example_es: '¡Levántate pronto!',
  },
  {
    id: 'n4-37', jlpt: 'N4', pattern: 'なくなる', name_es: 'Dejar de tener / desaparecer なくなる', name_en: 'Run out of / No longer なくなる',
    meaning_es: 'Indica que algo ya no existe o se ha agotado.',
    meaning_en: 'Indicates something no longer exists or has run out.',
    structure: 'N が なくなる',
    example_jp: 'お金がなくなった。', example_es: 'Se me acabó el dinero.',
  },
  {
    id: 'n4-38', jlpt: 'N4', pattern: 'くなる / になる', name_es: 'Cambio de estado くなる/になる', name_en: 'Become くなる/になる',
    meaning_es: 'Indica un cambio de estado. くなる para adj-い, になる para adj-な y sustantivos.',
    meaning_en: 'Indicates a change of state. くなる for i-adj, になる for na-adj and nouns.',
    structure: 'Adj-くなる / N/Adj-な になる',
    example_jp: '外が暗くなった。', example_es: 'Se ha oscurecido afuera.',
  },
  {
    id: 'n4-39', jlpt: 'N4', pattern: 'させる (causativo)', name_es: 'Causativo させる', name_en: 'Causative させる',
    meaning_es: 'Indica que el sujeto hace que alguien haga algo, o le permite hacerlo.',
    meaning_en: 'Indicates the subject makes or lets someone do something.',
    structure: 'V-させる',
    example_jp: '子供に野菜を食べさせた。', example_es: 'Hice que el niño comiese verduras.',
  },
  {
    id: 'n4-40', jlpt: 'N4', pattern: 'られる (pasivo)', name_es: 'Pasiva られる', name_en: 'Passive られる',
    meaning_es: 'El sujeto recibe la acción. Puede tener nuance negativa (pasiva de sufrimiento).',
    meaning_en: 'The subject receives the action. Can have a negative nuance (passive of suffering).',
    structure: 'V-られる',
    example_jp: '犬に噛まれた。', example_es: 'Me mordió un perro (lit. fui mordido por un perro).',
  },
  {
    id: 'n4-41', jlpt: 'N4', pattern: 'られる (potencial)', name_es: 'Potencial られる', name_en: 'Potential られる',
    meaning_es: 'Indica capacidad o posibilidad de hacer algo.',
    meaning_en: 'Indicates capacity or possibility to do something.',
    structure: 'V-られる (grupo 2 y 3)',
    example_jp: '漢字が読められる。', example_es: 'Puedo leer kanji.',
    notes: 'Para verbos del grupo 1 (五段), se usa la forma える (行ける, 書ける, etc.).',
  },
  {
    id: 'n4-42', jlpt: 'N4', pattern: 'させてください', name_es: 'Permiso para hacer させてください', name_en: 'Please let me do させてください',
    meaning_es: 'Solicita permiso educadamente para hacer algo.',
    meaning_en: 'Politely requests permission to do something.',
    structure: 'V-させてください',
    example_jp: '説明させてください。', example_es: 'Por favor, déjeme explicarlo.',
  },
  {
    id: 'n4-43', jlpt: 'N4', pattern: 'まま (estado continuo)', name_es: 'Estado continuo まま', name_en: 'Remaining state まま',
    meaning_es: 'Indica que algo permanece en el mismo estado que antes.',
    meaning_en: 'Indicates something remains in the same state as before.',
    structure: 'V-た まま',
    example_jp: 'ドアを開けたまま寝てしまった。', example_es: 'Me quedé dormido con la puerta abierta.',
  },
  {
    id: 'n4-44', jlpt: 'N4', pattern: 'でも～でも', name_es: 'Ya sea A o B でも～でも', name_en: 'Whether A or B でも～でも',
    meaning_es: 'Expresa que ambas opciones se aplican, sin importar cuál.',
    meaning_en: 'Expresses that both options apply, regardless of which.',
    structure: 'N でも N でも',
    example_jp: '赤でも青でもいいです。', example_es: 'Está bien, ya sea rojo o azul.',
  },
  {
    id: 'n4-45', jlpt: 'N4', pattern: 'といえば', name_es: 'Hablando de といえば', name_en: 'Speaking of / When you mention といえば',
    meaning_es: 'Introduce un tema relacionado con algo mencionado. "A propósito de / Hablando de".',
    meaning_en: 'Introduces a topic related to something mentioned. "Speaking of / When you mention".',
    structure: 'N といえば',
    example_jp: '日本といえば、富士山ですね。', example_es: 'Hablando de Japón, está el monte Fuji, ¿verdad?',
  },
  {
    id: 'n4-46', jlpt: 'N4', pattern: 'について', name_es: 'Sobre / Acerca de について', name_en: 'About / Concerning について',
    meaning_es: 'Indica el tema del que se trata o habla.',
    meaning_en: 'Indicates the topic being discussed or treated.',
    structure: 'N について',
    example_jp: '日本の文化について話しましょう。', example_es: 'Hablemos sobre la cultura japonesa.',
  },
  {
    id: 'n4-47', jlpt: 'N4', pattern: 'によって', name_es: 'Según / Por medio de によって', name_en: 'Depending on / By means of によって',
    meaning_es: 'Indica agente en pasiva, causa, medio, o variación según el factor.',
    meaning_en: 'Indicates passive agent, cause, means, or variation depending on the factor.',
    structure: 'N によって',
    example_jp: '人によって考え方が違う。', example_es: 'La forma de pensar varía según la persona.',
  },
  {
    id: 'n4-48', jlpt: 'N4', pattern: 'にとって', name_es: 'Para (desde el punto de vista de) にとって', name_en: 'For / From the perspective of にとって',
    meaning_es: 'Indica la perspectiva o posición de alguien respecto a algo.',
    meaning_en: 'Indicates someone\'s perspective or position regarding something.',
    structure: 'N にとって',
    example_jp: '私にとって家族が一番大切です。', example_es: 'Para mí, la familia es lo más importante.',
  },
  {
    id: 'n4-49', jlpt: 'N4', pattern: 'に対して', name_es: 'Hacia / En respuesta a に対して', name_en: 'Toward / In response to に対して',
    meaning_es: 'Indica la dirección de una acción, sentimiento u opinión hacia algo/alguien.',
    meaning_en: 'Indicates the direction of an action, feeling, or opinion toward something/someone.',
    structure: 'N に対して',
    example_jp: '質問に対して答えた。', example_es: 'Respondí a la pregunta.',
  },
  {
    id: 'n4-50', jlpt: 'N4', pattern: 'だけでなく', name_es: 'No solo sino también だけでなく', name_en: 'Not only but also だけでなく',
    meaning_es: 'Indica que algo abarca más de lo esperado: "no solo X sino también Y".',
    meaning_en: 'Indicates something encompasses more than expected: "not only X but also Y".',
    structure: 'N/V-plain だけでなく',
    example_jp: '日本語だけでなく英語も話せる。', example_es: 'Habla no solo japonés sino también inglés.',
  },

  // ─────────────────────────────────────────────
  // N3
  // ─────────────────────────────────────────────
  {
    id: 'n3-01', jlpt: 'N3', pattern: 'わけだ', name_es: 'Conclusión/razón わけだ', name_en: 'That means / It follows that わけだ',
    meaning_es: 'Expresa una conclusión lógica basada en la situación o explicación dada.',
    meaning_en: 'Expresses a logical conclusion based on the situation or explanation given.',
    structure: '～わけだ',
    example_jp: 'あの子は3年間日本にいた。日本語が上手なわけだ。', example_es: 'Ese chico estuvo 3 años en Japón. Por eso tiene buen japonés.',
  },
  {
    id: 'n3-02', jlpt: 'N3', pattern: 'わけがない', name_es: 'No hay razón para わけがない', name_en: 'There\'s no way that… わけがない',
    meaning_es: 'Expresa que algo es imposible o no tiene lógica.',
    meaning_en: 'Expresses that something is impossible or doesn\'t make logical sense.',
    structure: '～わけがない',
    example_jp: 'あの人がうそをつくわけがない。', example_es: 'No hay manera de que esa persona mienta.',
  },
  {
    id: 'n3-03', jlpt: 'N3', pattern: 'わけにはいかない', name_es: 'No puedo permitirme わけにはいかない', name_en: 'Cannot afford to / Mustn\'t わけにはいかない',
    meaning_es: 'Indica que no se puede hacer algo por razones sociales, morales o de circunstancia.',
    meaning_en: 'Indicates something cannot be done for social, moral, or circumstantial reasons.',
    structure: 'V-dict わけにはいかない',
    example_jp: '試験があるから遊ぶわけにはいかない。', example_es: 'Como hay examen, no me puedo permitir salir a divertirme.',
  },
  {
    id: 'n3-04', jlpt: 'N3', pattern: 'ものだ', name_es: 'Naturaleza/norma ものだ', name_en: 'That\'s how things are / Expected to ものだ',
    meaning_es: 'Expresa una norma social, costumbre o verdad general.',
    meaning_en: 'Expresses a social norm, custom, or general truth.',
    structure: '～ものだ',
    example_jp: '人は誰でも失敗するものだ。', example_es: 'Todo el mundo comete errores, así son las cosas.',
  },
  {
    id: 'n3-05', jlpt: 'N3', pattern: 'ものだから', name_es: 'Porque (con excusa) ものだから', name_en: 'Because (as an excuse) ものだから',
    meaning_es: 'Ofrece una razón o excusa, a menudo con tono justificativo.',
    meaning_en: 'Provides a reason or excuse, often with a justifying tone.',
    structure: '～ものだから',
    example_jp: '電車が遅れたものだから、遅刻しました。', example_es: 'El tren se retrasó, por eso llegué tarde.',
  },
  {
    id: 'n3-06', jlpt: 'N3', pattern: 'ものの', name_es: 'Aunque (pero en realidad) ものの', name_en: 'Although (but in reality) ものの',
    meaning_es: 'Introduce una concesión donde el resultado no es el esperado.',
    meaning_en: 'Introduces a concession where the result is not as expected.',
    structure: '～ものの',
    example_jp: '日本語を勉強したものの、まだ話せない。', example_es: 'Aunque estudié japonés, todavía no puedo hablarlo.',
  },
  {
    id: 'n3-07', jlpt: 'N3', pattern: 'ことだ', name_es: 'Consejo ことだ', name_en: 'You should / The thing to do is ことだ',
    meaning_es: 'Da un consejo o indica lo que se debería hacer.',
    meaning_en: 'Gives advice or indicates what should be done.',
    structure: 'V-dict/ない ことだ',
    example_jp: '健康のためによく寝ることだ。', example_es: 'Para la salud, lo que hay que hacer es dormir bien.',
  },
  {
    id: 'n3-08', jlpt: 'N3', pattern: 'ことから', name_es: 'Desde el hecho de ことから', name_en: 'From the fact that ことから',
    meaning_es: 'Indica una razón u origen basado en un hecho observable.',
    meaning_en: 'Indicates a reason or origin based on an observable fact.',
    structure: '～ことから',
    example_jp: '毎日練習することから上達した。', example_es: 'A partir del hecho de practicar todos los días, mejoró.',
  },
  {
    id: 'n3-09', jlpt: 'N3', pattern: 'ことに', name_es: 'Para sorpresa mía ことに', name_en: 'To my surprise/regret ことに',
    meaning_es: 'Expresa el estado emocional del hablante ante un hecho.',
    meaning_en: 'Expresses the speaker\'s emotional state regarding a fact.',
    structure: 'Adj-な/い ことに',
    example_jp: '残念なことに、彼は来なかった。', example_es: 'Lamentablemente, él no vino.',
  },
  {
    id: 'n3-10', jlpt: 'N3', pattern: 'てみせる', name_es: 'Lo haré sin falta てみせる', name_en: 'I\'ll definitely do it てみせる',
    meaning_es: 'Expresa determinación de hacer algo para mostrar/demostrar.',
    meaning_en: 'Expresses determination to do something to show or prove.',
    structure: 'V-てみせる',
    example_jp: '絶対に合格してみせる。', example_es: 'Me las arreglaré para aprobar sin falta.',
  },
  {
    id: 'n3-11', jlpt: 'N3', pattern: 'てはじめて', name_es: 'Solo después de てはじめて', name_en: 'Only after doing てはじめて',
    meaning_es: 'Indica que algo se comprende o se puede hacer solo tras cierta experiencia.',
    meaning_en: 'Indicates something is understood or possible only after a certain experience.',
    structure: 'V-てはじめて',
    example_jp: '失って、はじめてその大切さに気づいた。', example_es: 'Solo tras perderlo me di cuenta de su importancia.',
  },
  {
    id: 'n3-12', jlpt: 'N3', pattern: 'てたまらない', name_es: 'Insoportablemente てたまらない', name_en: 'Unbearably / Can\'t stand てたまらない',
    meaning_es: 'Expresa un sentimiento o sensación tan intenso que es difícil soportar.',
    meaning_en: 'Expresses a feeling or sensation so intense it\'s hard to bear.',
    structure: 'V-て/Adj たまらない',
    example_jp: '眠くてたまらない。', example_es: 'Tengo un sueño insoportable.',
  },
  {
    id: 'n3-13', jlpt: 'N3', pattern: 'てしかたがない', name_es: 'Sin poder evitarlo てしかたがない', name_en: 'Can\'t help but feel てしかたがない',
    meaning_es: 'Expresa que un sentimiento o estado es inevitable o incontrolable.',
    meaning_en: 'Expresses that a feeling or state is unavoidable or uncontrollable.',
    structure: 'V-て/Adj しかたがない',
    example_jp: '心配でしかたがない。', example_es: 'No puedo evitar estar preocupado.',
  },
  {
    id: 'n3-14', jlpt: 'N3', pattern: 'さえ～ない (ni siquiera)', name_es: 'Ni siquiera さえ～ない', name_en: 'Not even さえ～ない',
    meaning_es: 'Indica que incluso lo mínimo no se cumple.',
    meaning_en: 'Indicates that even the minimum is not achieved.',
    structure: 'N さえ ～ない',
    example_jp: '名前さえ知らない。', example_es: 'Ni siquiera sé su nombre.',
  },
  {
    id: 'n3-15', jlpt: 'N3', pattern: 'に違いない', name_es: 'Sin duda / Seguro que に違いない', name_en: 'Must be / No doubt に違いない',
    meaning_es: 'Expresa una convicción fuerte del hablante.',
    meaning_en: 'Expresses strong conviction of the speaker.',
    structure: '～に違いない',
    example_jp: '彼は疲れているに違いない。', example_es: 'Sin duda está cansado.',
  },
  {
    id: 'n3-16', jlpt: 'N3', pattern: 'に決まっている', name_es: 'Es seguro que に決まっている', name_en: 'It must be / Definitely に決まっている',
    meaning_es: 'Expresa certeza subjetiva muy alta del hablante.',
    meaning_en: 'Expresses very high subjective certainty of the speaker.',
    structure: '～に決まっている',
    example_jp: 'そんな話は嘘に決まっている。', example_es: 'Seguro que esa historia es mentira.',
  },
  {
    id: 'n3-17', jlpt: 'N3', pattern: 'かどうか', name_es: 'Si (o no) かどうか', name_en: 'Whether or not かどうか',
    meaning_es: 'Introduce una oración subordinada de duda: "si es que X o no".',
    meaning_en: 'Introduces a subordinate clause of doubt: "whether or not X".',
    structure: '～かどうか',
    example_jp: '彼が来るかどうか分からない。', example_es: 'No sé si él vendrá o no.',
  },
  {
    id: 'n3-18', jlpt: 'N3', pattern: 'かな', name_es: 'Me pregunto si かな', name_en: 'I wonder if かな',
    meaning_es: 'Expresa duda o deseo propio de forma suave. Registro informal.',
    meaning_en: 'Expresses personal doubt or wish softly. Informal register.',
    structure: '～かな',
    example_jp: '明日晴れるかな。', example_es: 'Me pregunto si mañana hará sol.',
  },
  {
    id: 'n3-19', jlpt: 'N3', pattern: 'において / における', name_es: 'En el ámbito de において', name_en: 'In / At (formal) において',
    meaning_es: 'Equivalente formal de で o に. Indica el contexto o lugar (escrito, formal).',
    meaning_en: 'Formal equivalent of で or に. Indicates context or place (written, formal).',
    structure: 'N において/における',
    example_jp: '現代社会において、技術は重要だ。', example_es: 'En la sociedad actual, la tecnología es importante.',
  },
  {
    id: 'n3-20', jlpt: 'N3', pattern: 'に関して / に関する', name_es: 'Con respecto a に関して', name_en: 'Regarding / Related to に関して',
    meaning_es: 'Indica el tema al que hace referencia. Más formal que について.',
    meaning_en: 'Indicates the topic being referenced. More formal than について.',
    structure: 'N に関して/に関する',
    example_jp: 'この問題に関して話し合いましょう。', example_es: 'Hablemos sobre este asunto.',
  },
  {
    id: 'n3-21', jlpt: 'N3', pattern: 'に加えて', name_es: 'Además de に加えて', name_en: 'In addition to に加えて',
    meaning_es: 'Indica que algo se añade a lo ya mencionado.',
    meaning_en: 'Indicates something is added to what was already mentioned.',
    structure: 'N に加えて',
    example_jp: '雨に加えて、風も強い。', example_es: 'Además de lluvia, también hay viento fuerte.',
  },
  {
    id: 'n3-22', jlpt: 'N3', pattern: 'に反して', name_es: 'Contrariamente a に反して', name_en: 'Against / Contrary to に反して',
    meaning_es: 'Indica que algo va en contra de lo esperado, una norma o una expectativa.',
    meaning_en: 'Indicates something goes against what was expected, a rule, or an expectation.',
    structure: 'N に反して',
    example_jp: '予想に反して、試験は簡単だった。', example_es: 'Contrariamente a lo esperado, el examen fue fácil.',
  },
  {
    id: 'n3-23', jlpt: 'N3', pattern: 'たとえ～ても', name_es: 'Aunque (hipotético) たとえ～ても', name_en: 'Even if (hypothetical) たとえ～ても',
    meaning_es: 'Condición hipotética concesiva: "aunque incluso suponiendo que X".',
    meaning_en: 'Hypothetical concessive condition: "even if we suppose X".',
    structure: 'たとえ ～ ても',
    example_jp: 'たとえ失敗しても、諦めない。', example_es: 'Aunque fracase, no me rendiré.',
  },
  {
    id: 'n3-24', jlpt: 'N3', pattern: 'にしては', name_es: 'Para ser にしては', name_en: 'For / Considering にしては',
    meaning_es: 'Indica que algo es inesperado o diferente considerando la circunstancia.',
    meaning_en: 'Indicates something is unexpected given the circumstance.',
    structure: 'N/V-dict にしては',
    example_jp: '子供にしては、字がきれいだ。', example_es: 'Para ser un niño, tiene buena letra.',
  },
  {
    id: 'n3-25', jlpt: 'N3', pattern: 'に従って', name_es: 'Siguiendo / A medida que に従って', name_en: 'Following / As に従って',
    meaning_es: 'Indica que algo cambia en paralelo con otro factor, o que se sigue una regla.',
    meaning_en: 'Indicates something changes in parallel with another factor, or that a rule is followed.',
    structure: 'N/V-dict に従って',
    example_jp: '規則に従って行動した。', example_es: 'Actué siguiendo las normas.',
  },
  {
    id: 'n3-26', jlpt: 'N3', pattern: 'につれて', name_es: 'A medida que につれて', name_en: 'As ~ increases につれて',
    meaning_es: 'Indica un cambio proporcional: a medida que A aumenta, B también cambia.',
    meaning_en: 'Indicates proportional change: as A increases, B also changes.',
    structure: 'V-dict/N につれて',
    example_jp: '年をとるにつれて、体が弱くなる。', example_es: 'A medida que envejecemos, el cuerpo se debilita.',
  },
  {
    id: 'n3-27', jlpt: 'N3', pattern: 'ながらも', name_es: 'A pesar de ながらも', name_en: 'Although / Despite ながらも',
    meaning_es: 'Concesión: aunque simultáneamente existe A, ocurre B (contradictorio).',
    meaning_en: 'Concession: although A simultaneously exists, B happens (contradictory).',
    structure: 'V-stem/Adj ながらも',
    example_jp: '忙しいながらも楽しんでいる。', example_es: 'Aunque estoy ocupado, me lo estoy pasando bien.',
  },
  {
    id: 'n3-28', jlpt: 'N3', pattern: 'というより', name_es: 'Más bien que というより', name_en: 'Rather than というより',
    meaning_es: 'Corrige o matiza una descripción anterior: "no tanto X, sino más bien Y".',
    meaning_en: 'Corrects or nuances a previous description: "not so much X, but rather Y".',
    structure: '～というより',
    example_jp: '好きというより、必要だから勉強している。', example_es: 'Más que porque me guste, estudio porque lo necesito.',
  },
  {
    id: 'n3-29', jlpt: 'N3', pattern: 'かわりに', name_es: 'En lugar de / A cambio de かわりに', name_en: 'Instead of / In exchange for かわりに',
    meaning_es: 'Indica sustitución o compensación.',
    meaning_en: 'Indicates substitution or compensation.',
    structure: 'N/V-dict かわりに',
    example_jp: 'バスのかわりに歩いて行った。', example_es: 'Fui andando en lugar de en autobús.',
  },
  {
    id: 'n3-30', jlpt: 'N3', pattern: 'ほど', name_es: 'Tanto como / Al punto de ほど', name_en: 'To the extent of / As much as ほど',
    meaning_es: 'Indica grado o comparación: "tanto ～ que", "cuanto más ～ más ～".',
    meaning_en: 'Indicates degree or comparison: "so ~ that", "the more ~ the more ~".',
    structure: 'V/Adj ほど',
    example_jp: '泣くほど笑った。', example_es: 'Me reí tanto que lloré.',
  },

  // ─────────────────────────────────────────────
  // N2
  // ─────────────────────────────────────────────
  {
    id: 'n2-01', jlpt: 'N2', pattern: 'はもちろん', name_es: 'Por supuesto, incluso はもちろん', name_en: 'Not only but also (of course) はもちろん',
    meaning_es: 'Indica que A es obvio y encima también B.',
    meaning_en: 'Indicates A is obvious and on top of that B applies too.',
    structure: 'N はもちろん N も',
    example_jp: '日本語はもちろん、英語も話せる。', example_es: 'Habla japonés, claro, y encima también inglés.',
  },
  {
    id: 'n2-02', jlpt: 'N2', pattern: 'はおろか', name_es: 'Ni siquiera はおろか', name_en: 'Let alone / Not even はおろか',
    meaning_es: 'Ni siquiera A (y mucho menos B). Indica extremo negativo o positivo.',
    meaning_en: 'Not even A (let alone B). Indicates an extreme negative or positive.',
    structure: 'N はおろか N も',
    example_jp: '漢字はおろか、ひらがなも読めない。', example_es: 'No puede leer ni siquiera hiragana, para qué hablar de kanji.',
  },
  {
    id: 'n2-03', jlpt: 'N2', pattern: 'をはじめ', name_es: 'Empezando por をはじめ', name_en: 'Starting with / Including をはじめ',
    meaning_es: 'Indica que N₁ es el representante de una lista de cosas similares.',
    meaning_en: 'Indicates N₁ is representative of a list of similar things.',
    structure: 'N をはじめ（として）',
    example_jp: '東京をはじめ、多くの都市が影響を受けた。', example_es: 'Empezando por Tokio, muchas ciudades se vieron afectadas.',
  },
  {
    id: 'n2-04', jlpt: 'N2', pattern: 'に基づいて', name_es: 'Basándose en に基づいて', name_en: 'Based on に基づいて',
    meaning_es: 'Indica que algo se hace tomando como base o fundamento N.',
    meaning_en: 'Indicates something is done based on or grounded in N.',
    structure: 'N に基づいて',
    example_jp: 'データに基づいて判断した。', example_es: 'Tomé la decisión basándome en los datos.',
  },
  {
    id: 'n2-05', jlpt: 'N2', pattern: 'にもかかわらず', name_es: 'A pesar de にもかかわらず', name_en: 'Despite / In spite of にもかかわらず',
    meaning_es: 'Contraste fuerte: aunque existe A, ocurre B en sentido contrario.',
    meaning_en: 'Strong contrast: although A exists, B happens contrary to expectation.',
    structure: 'N/V-plain にもかかわらず',
    example_jp: '雨にもかかわらず、試合は行われた。', example_es: 'A pesar de la lluvia, el partido se celebró.',
  },
  {
    id: 'n2-06', jlpt: 'N2', pattern: 'に限らず', name_es: 'No solo sino también に限らず', name_en: 'Not limited to に限らず',
    meaning_es: 'No se limita únicamente a N; incluye también otras cosas.',
    meaning_en: 'Not limited only to N; includes other things as well.',
    structure: 'N に限らず',
    example_jp: '日本に限らず、世界中で問題がある。', example_es: 'No es solo en Japón, hay problemas en todo el mundo.',
  },
  {
    id: 'n2-07', jlpt: 'N2', pattern: 'をきっかけに', name_es: 'Aprovechando / Motivado por をきっかけに', name_en: 'Taking the opportunity of / Triggered by をきっかけに',
    meaning_es: 'N sirve de detonante o de oportunidad para que ocurra algo.',
    meaning_en: 'N serves as a trigger or opportunity for something to happen.',
    structure: 'N をきっかけに',
    example_jp: 'この出来事をきっかけに人生が変わった。', example_es: 'A raíz de este suceso, mi vida cambió.',
  },
  {
    id: 'n2-08', jlpt: 'N2', pattern: 'にともなって', name_es: 'A medida que / Al acompañar にともなって', name_en: 'Along with / Accompanying にともなって',
    meaning_es: 'Indica que B ocurre paralelamente a A o como consecuencia de A.',
    meaning_en: 'Indicates B occurs in parallel with A or as a consequence of A.',
    structure: 'N/V-dict にともなって',
    example_jp: '経済成長にともなって、生活水準が上がった。', example_es: 'Al compás del crecimiento económico, el nivel de vida mejoró.',
  },
  {
    id: 'n2-09', jlpt: 'N2', pattern: 'に先立って', name_es: 'Antes de (previo a) に先立って', name_en: 'Prior to / Before に先立って',
    meaning_es: 'Indica que una acción se realiza como preparación antes de N.',
    meaning_en: 'Indicates an action is done in preparation before N.',
    structure: 'N/V-dict に先立って',
    example_jp: '式典に先立って、準備が行われた。', example_es: 'Antes de la ceremonia, se hicieron los preparativos.',
  },
  {
    id: 'n2-10', jlpt: 'N2', pattern: 'を通して / を通じて', name_es: 'A través de を通して', name_en: 'Through / Via を通して',
    meaning_es: 'Indica el medio, periodo o intermediario a través del cual ocurre algo.',
    meaning_en: 'Indicates the medium, period, or intermediary through which something occurs.',
    structure: 'N を通して/を通じて',
    example_jp: '友人を通して知り合った。', example_es: 'Nos conocimos a través de un amigo en común.',
  },
  {
    id: 'n2-11', jlpt: 'N2', pattern: 'さえ～ば (mínima condición)', name_es: 'Con solo que さえ～ば', name_en: 'If only… さえ～ば',
    meaning_es: 'Expresa que con cumplir únicamente la condición mínima, el resultado se logra.',
    meaning_en: 'Expresses that fulfilling just the minimum condition achieves the result.',
    structure: 'N さえ～ば / V-stem さえ～すれば',
    example_jp: 'やる気さえあれば、何でもできる。', example_es: 'Con solo tener motivación, se puede hacer cualquier cosa.',
  },
  {
    id: 'n2-12', jlpt: 'N2', pattern: 'うえで', name_es: 'Para / Al うえで', name_en: 'For the purpose of / After うえで',
    meaning_es: 'Indica condición o etapa previa necesaria para que ocurra algo.',
    meaning_en: 'Indicates a prior condition or stage necessary for something to occur.',
    structure: 'V-dict/た うえで',
    example_jp: '話し合ったうえで決めます。', example_es: 'Decidiré después de haber hablado.',
  },
  {
    id: 'n2-13', jlpt: 'N2', pattern: 'にしたがって', name_es: 'Conforme a / Siguiendo にしたがって', name_en: 'According to / As にしたがって',
    meaning_es: 'Indica seguimiento de una instrucción o un cambio progresivo.',
    meaning_en: 'Indicates following an instruction or a progressive change.',
    structure: 'N/V-dict にしたがって',
    example_jp: '説明書にしたがって組み立てた。', example_es: 'Lo ensambló siguiendo las instrucciones.',
  },
  {
    id: 'n2-14', jlpt: 'N2', pattern: 'にしろ / にせよ', name_es: 'Ya sea que にしろ/にせよ', name_en: 'Whether or not にしろ/にせよ',
    meaning_es: 'Indica que la acción es válida independientemente de la condición.',
    meaning_en: 'Indicates the action is valid regardless of the condition.',
    structure: 'V/N にしろ/にせよ',
    example_jp: '賛成にしろ反対にしろ、意見を言ってください。', example_es: 'Ya sea a favor o en contra, por favor di tu opinión.',
  },
  {
    id: 'n2-15', jlpt: 'N2', pattern: 'ないことはない', name_es: 'No es que no pueda ないことはない', name_en: 'It\'s not that I can\'t ないことはない',
    meaning_es: 'Doble negativo que equivale a afirmar con matices: "no es que sea imposible".',
    meaning_en: 'Double negative equivalent to affirming with nuance: "it\'s not impossible".',
    structure: 'V-ない ことはない',
    example_jp: '行けないことはないが、時間がかかる。', example_es: 'No es que no pueda ir, pero llevaría tiempo.',
  },
  {
    id: 'n2-16', jlpt: 'N2', pattern: 'ばかりか', name_es: 'No solo sino que además ばかりか', name_en: 'Not only but also ばかりか',
    meaning_es: 'Añade información que supera la ya mencionada: "no solo X sino encima Y".',
    meaning_en: 'Adds information that exceeds what was mentioned: "not only X but on top of that Y".',
    structure: 'N/V-plain ばかりか',
    example_jp: '遅刻したばかりか、宿題も忘れた。', example_es: 'No solo llegó tarde sino que encima se olvidó los deberes.',
  },
  {
    id: 'n2-17', jlpt: 'N2', pattern: 'かねない', name_es: 'Podría fácilmente (negativo) かねない', name_en: 'Might easily / Could well かねない',
    meaning_es: 'Indica que algo negativo podría ocurrir con facilidad.',
    meaning_en: 'Indicates a negative outcome could easily occur.',
    structure: 'V-stem かねない',
    example_jp: 'このままでは失敗しかねない。', example_es: 'Así como está, podría fácilmente terminar en fracaso.',
  },
  {
    id: 'n2-18', jlpt: 'N2', pattern: 'かねる', name_es: 'No poder hacer (educado) かねる', name_en: 'Find it difficult to / Cannot かねる',
    meaning_es: 'Indica que el hablante no puede o le resulta difícil hacer algo (con cortesía).',
    meaning_en: 'Indicates the speaker cannot or finds it difficult to do something (politely).',
    structure: 'V-stem かねる',
    example_jp: 'その要求にはお応えしかねます。', example_es: 'Lamentablemente no puedo atender esa solicitud.',
  },
  {
    id: 'n2-19', jlpt: 'N2', pattern: 'っけ', name_es: 'Recordar/confirmar っけ', name_en: 'What was it again? / Recall っけ',
    meaning_es: 'Partícula coloquial que expresa que el hablante está intentando recordar algo.',
    meaning_en: 'Colloquial particle expressing the speaker is trying to recall something.',
    structure: '～っけ',
    example_jp: '彼の名前、なんだっけ？', example_es: '¿Cómo se llamaba él, a ver?',
  },
  {
    id: 'n2-20', jlpt: 'N2', pattern: 'ところ (a punto de, acabar de)', name_es: 'A punto de / Acabando de ところ', name_en: 'Just about to / Just finished ところ',
    meaning_es: 'V-るところ: a punto de; V-ているところ: en proceso; V-たところ: recién terminado.',
    meaning_en: 'V-るところ: about to; V-ているところ: in progress; V-たところ: just finished.',
    structure: 'V-る/ている/た ところ',
    example_jp: '今電話しようとしていたところです。', example_es: 'Justamente estaba a punto de llamar.',
  },
  {
    id: 'n2-21', jlpt: 'N2', pattern: 'はずがない', name_es: 'No puede ser que はずがない', name_en: 'There\'s no way / Cannot be はずがない',
    meaning_es: 'Expresa convicción de que algo es imposible o no debería ser así.',
    meaning_en: 'Expresses conviction that something is impossible or should not be so.',
    structure: '～はずがない',
    example_jp: '彼がそんなことを言うはずがない。', example_es: 'No puede ser que él haya dicho eso.',
  },
  {
    id: 'n2-22', jlpt: 'N2', pattern: 'に反して', name_es: 'Contrariamente a に反して', name_en: 'Against / Contrary to に反して',
    meaning_es: 'Algo va en contra de una expectativa, norma o deseo.',
    meaning_en: 'Something goes against an expectation, norm, or wish.',
    structure: 'N に反して',
    example_jp: '期待に反して、結果はよくなかった。', example_es: 'Contrariamente a lo esperado, el resultado no fue bueno.',
  },
  {
    id: 'n2-23', jlpt: 'N2', pattern: 'をもとに', name_es: 'Basándose en をもとに', name_en: 'Based on / Using as a basis をもとに',
    meaning_es: 'Indica que N sirve como base o material de partida para crear algo.',
    meaning_en: 'Indicates N serves as the base or starting material to create something.',
    structure: 'N をもとに',
    example_jp: '実話をもとに映画が作られた。', example_es: 'La película fue hecha basándose en una historia real.',
  },
  {
    id: 'n2-24', jlpt: 'N2', pattern: 'を中心に', name_es: 'Con ~ en el centro を中心に', name_en: 'Centered on / Focusing on を中心に',
    meaning_es: 'Indica que N es el eje central de algo.',
    meaning_en: 'Indicates N is the central axis of something.',
    structure: 'N を中心に',
    example_jp: '子供を中心に家族が集まった。', example_es: 'La familia se reunió con el niño en el centro.',
  },
  {
    id: 'n2-25', jlpt: 'N2', pattern: 'に当たって', name_es: 'Al hacer / En la ocasión de に当たって', name_en: 'On the occasion of / When doing に当たって',
    meaning_es: 'Indica que algo se hace en el momento o en la ocasión de N.',
    meaning_en: 'Indicates something is done at the time or on the occasion of N.',
    structure: 'N/V-dict に当たって',
    example_jp: '卒業に当たって、感謝の言葉を述べた。', example_es: 'Con motivo de la graduación, expresó su agradecimiento.',
  },

  // ─────────────────────────────────────────────
  // N1
  // ─────────────────────────────────────────────
  {
    id: 'n1-01', jlpt: 'N1', pattern: 'いかん', name_es: 'Dependiendo de いかん', name_en: 'Depending on いかん',
    meaning_es: 'Indica que el resultado depende de N. Registro muy formal/escrito.',
    meaning_en: 'Indicates the result depends on N. Very formal/written register.',
    structure: 'N いかん(によって)',
    example_jp: '努力のいかんによって結果が変わる。', example_es: 'El resultado cambia según el nivel de esfuerzo.',
  },
  {
    id: 'n1-02', jlpt: 'N1', pattern: 'いかんにかかわらず', name_es: 'Sin importar いかんにかかわらず', name_en: 'Regardless of いかんにかかわらず',
    meaning_es: 'Independientemente de N, el resultado es siempre el mismo.',
    meaning_en: 'Regardless of N, the result is always the same.',
    structure: 'N のいかんにかかわらず',
    example_jp: '結果のいかんにかかわらず、最善を尽くす。', example_es: 'Independientemente del resultado, haré mi mayor esfuerzo.',
  },
  {
    id: 'n1-03', jlpt: 'N1', pattern: 'をおいて', name_es: 'Aparte de / Nadie más que をおいて', name_en: 'Other than / No one but をおいて',
    meaning_es: 'Indica que no hay nadie ni nada más adecuado que N. Muy formal.',
    meaning_en: 'Indicates there is no one or nothing more suitable than N. Very formal.',
    structure: 'N をおいて ～ない',
    example_jp: '彼をおいて適任者はいない。', example_es: 'Aparte de él, no hay nadie más apropiado.',
  },
  {
    id: 'n1-04', jlpt: 'N1', pattern: 'をもって', name_es: 'Con / Por medio de をもって', name_en: 'With / By means of をもって',
    meaning_es: 'Indica el medio, la razón, o el momento límite. Registro muy formal.',
    meaning_en: 'Indicates the means, reason, or deadline. Very formal register.',
    structure: 'N をもって',
    example_jp: '本日をもってこの店は閉店します。', example_es: 'A partir de hoy, esta tienda cierra definitivamente.',
  },
  {
    id: 'n1-05', jlpt: 'N1', pattern: 'ならでは', name_es: 'Solo posible para / Único de ならでは', name_en: 'Only possible for / Unique to ならでは',
    meaning_es: 'Indica algo que solo es posible gracias a N o que es exclusivo de N.',
    meaning_en: 'Indicates something only possible thanks to N or unique to N.',
    structure: 'N ならでは（の）',
    example_jp: '日本ならではの文化を体験した。', example_es: 'Experimenté una cultura propia y única de Japón.',
  },
  {
    id: 'n1-06', jlpt: 'N1', pattern: 'に至って / に至っては', name_es: 'Llegando al extremo de に至って', name_en: 'Going as far as / Even に至って',
    meaning_es: 'Indica que se ha llegado a un estado extremo o punto límite.',
    meaning_en: 'Indicates reaching an extreme state or limit.',
    structure: 'N に至って(は)',
    example_jp: '今に至っても答えが見つからない。', example_es: 'Incluso ahora, no se ha encontrado respuesta.',
  },
  {
    id: 'n1-07', jlpt: 'N1', pattern: 'を余儀なくされる', name_es: 'Verse obligado a を余儀なくされる', name_en: 'Be forced to を余儀なくされる',
    meaning_es: 'Indica que alguien se ve obligado a hacer algo por circunstancias externas.',
    meaning_en: 'Indicates someone is forced to do something by external circumstances.',
    structure: 'N を余儀なくされる',
    example_jp: '台風で帰宅を余儀なくされた。', example_es: 'El tifón nos obligó a volver a casa.',
  },
  {
    id: 'n1-08', jlpt: 'N1', pattern: 'にほかならない', name_es: 'No es nada más que にほかならない', name_en: 'Nothing other than / Precisely にほかならない',
    meaning_es: 'Enfatiza que la causa o esencia es exactamente N, sin duda alguna.',
    meaning_en: 'Emphasizes that the cause or essence is exactly N, without any doubt.',
    structure: 'N にほかならない',
    example_jp: '成功したのは努力にほかならない。', example_es: 'El éxito no es sino fruto del esfuerzo.',
  },
  {
    id: 'n1-09', jlpt: 'N1', pattern: 'とはいえ', name_es: 'Dicho esto / Aunque とはいえ', name_en: 'That said / Even so とはいえ',
    meaning_es: 'Reconoce A pero introduce B que lo matiza o contradice.',
    meaning_en: 'Acknowledges A but introduces B that qualifies or contradicts it.',
    structure: '～とはいえ',
    example_jp: '春とはいえ、まだ寒い。', example_es: 'Aunque es primavera, aún hace frío.',
  },
  {
    id: 'n1-10', jlpt: 'N1', pattern: 'とはいうものの', name_es: 'Aunque se diga とはいうものの', name_en: 'Although it is said / Even though とはいうものの',
    meaning_es: 'Reconoce un hecho general pero introduce un matiz contrario.',
    meaning_en: 'Acknowledges a general fact but introduces a contrary nuance.',
    structure: '～とはいうものの',
    example_jp: '健康にいいとはいうものの、毎日運動するのは難しい。', example_es: 'Aunque dicen que es bueno para la salud, hacer ejercicio todos los días es difícil.',
  },
  {
    id: 'n1-11', jlpt: 'N1', pattern: 'に相違ない', name_es: 'Sin duda que に相違ない', name_en: 'Without a doubt / Must be に相違ない',
    meaning_es: 'Certeza muy alta del hablante. Forma más formal de に違いない.',
    meaning_en: 'Very high certainty of the speaker. More formal version of に違いない.',
    structure: '～に相違ない',
    example_jp: 'あれが犯人に相違ない。', example_es: 'Aquel es el culpable sin ninguna duda.',
  },
  {
    id: 'n1-12', jlpt: 'N1', pattern: 'ずにはいられない', name_es: 'No poder evitar ずにはいられない', name_en: 'Cannot help but ずにはいられない',
    meaning_es: 'El hablante no puede evitar hacer algo aunque quisiera.',
    meaning_en: 'The speaker cannot help doing something even if they wanted to avoid it.',
    structure: 'V-ず にはいられない',
    example_jp: '彼の冗談を聞いて笑わずにはいられなかった。', example_es: 'Al escuchar sus chistes, no pude evitar reírme.',
  },
  {
    id: 'n1-13', jlpt: 'N1', pattern: 'てやまない', name_es: 'No cesar de / Sinceramente てやまない', name_en: 'Sincerely / Never cease to てやまない',
    meaning_es: 'Expresa un sentimiento continuo e intenso (amor, esperanza, deseo).',
    meaning_en: 'Expresses a continuous and intense feeling (love, hope, desire).',
    structure: 'V-て やまない',
    example_jp: '皆さんのご活躍を願ってやみません。', example_es: 'Sinceramente espero que todos ustedes prosperen.',
  },
  {
    id: 'n1-14', jlpt: 'N1', pattern: '極まりない / 極まる', name_es: 'Sumamente / Extremadamente 極まりない', name_en: 'Extremely / In the extreme 極まりない',
    meaning_es: 'Expresa que algo es en extremo negativo. Tono muy formal y literario.',
    meaning_en: 'Expresses something is extremely negative. Very formal and literary tone.',
    structure: 'Adj-な 極まりない',
    example_jp: 'その態度は失礼極まりない。', example_es: 'Esa actitud es de lo más irrespetuosa.',
  },
  {
    id: 'n1-15', jlpt: 'N1', pattern: 'に至るまで', name_es: 'Hasta llegar a に至るまで', name_en: 'Right up to / All the way to に至るまで',
    meaning_es: 'Indica la amplitud exhaustiva de algo: "desde ~ hasta ~".',
    meaning_en: 'Indicates exhaustive breadth: "from ~ all the way to ~".',
    structure: 'N₁ から N₂ に至るまで',
    example_jp: '子供から大人に至るまで楽しめる。', example_es: 'Pueden disfrutarlo desde niños hasta adultos.',
  },
  {
    id: 'n1-16', jlpt: 'N1', pattern: 'ともなく / ともなしに', name_es: 'Sin intención especial ともなく', name_en: 'Without particular intention ともなく',
    meaning_es: 'Indica hacer algo sin un propósito o intención específicos.',
    meaning_en: 'Indicates doing something without a specific purpose or intention.',
    structure: 'V-dict ともなく',
    example_jp: 'ラジオを聴くともなく流していた。', example_es: 'Tenía la radio puesta sin escucharla en particular.',
  },
  {
    id: 'n1-17', jlpt: 'N1', pattern: 'とたんに', name_es: 'En el momento en que とたんに', name_en: 'The moment / As soon as とたんに',
    meaning_es: 'Justo en el instante en que se termina A, ocurre B (a menudo inesperado).',
    meaning_en: 'The very instant A is finished, B happens (often unexpectedly).',
    structure: 'V-た とたんに',
    example_jp: '立ち上がったとたんに転んだ。', example_es: 'En el mismo momento en que se levantó, se cayó.',
  },
  {
    id: 'n1-18', jlpt: 'N1', pattern: 'に際して', name_es: 'En la ocasión de に際して', name_en: 'On the occasion of / When に際して',
    meaning_es: 'Indica que se hace algo en un momento importante o especial. Formal.',
    meaning_en: 'Indicates something done at an important or special moment. Formal.',
    structure: 'N/V-dict に際して',
    example_jp: '入学に際して、心構えを新たにした。', example_es: 'Con motivo de su ingreso, renovó su actitud mental.',
  },
  {
    id: 'n1-19', jlpt: 'N1', pattern: 'べく', name_es: 'Con el fin de べく', name_en: 'In order to べく',
    meaning_es: 'Expresa propósito formal: "con el fin de, para". Equivale a ために pero más formal.',
    meaning_en: 'Expresses formal purpose: "in order to". Equivalent to ために but more formal.',
    structure: 'V-dict べく',
    example_jp: '夢を実現すべく努力した。', example_es: 'Se esforzó con el fin de realizar su sueño.',
  },
  {
    id: 'n1-20', jlpt: 'N1', pattern: 'べからず', name_es: 'Prohibición formal べからず', name_en: 'Must not / Forbidden べからず',
    meaning_es: 'Prohibición formal y absoluta. Se usa en carteles, normas o textos formales.',
    meaning_en: 'Formal and absolute prohibition. Used in signs, rules, or formal texts.',
    structure: 'V-dict べからず',
    example_jp: '立ち入るべからず。', example_es: 'Prohibido el paso.',
  },
]

export const BUNPRO_JLPT_LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'] as const

export function getBunproByLevel(level: BunproGrammarPoint['jlpt']) {
  return BUNPRO_GRAMMAR.filter(g => g.jlpt === level)
}

export function getBunproById(id: string) {
  return BUNPRO_GRAMMAR.find(g => g.id === id)
}

// ── Adapter: BunproGrammarPoint → GrammarPoint ─────────────────────────────
// Converts a BunPro point to the GrammarPoint shape expected by GrammarPractice
// and GrammarDetail. Only the fields used by those components are filled.
import type { GrammarPoint } from './grammar-mnn1'

export function bunproToGrammarPoint(bp: BunproGrammarPoint): GrammarPoint {
  return {
    id: bp.id,
    lesson: 0,
    number: 0,
    jlpt: bp.jlpt,
    pattern: bp.pattern,
    name_es: bp.name_es,
    name_ca: bp.name_es,
    name_en: bp.name_en,
    explanation_es: bp.meaning_es,
    explanation_ca: bp.meaning_es,
    explanation_en: bp.meaning_en,
    structure: [{ text: bp.structure, role: 'key', isSlot: false }],
    example: [],
    tip_es: bp.notes,
    tip_ca: bp.notes,
    tip_en: bp.notes,
  }
}
